<h2 class="page-header"><a href="<?php echo $this->basePath()?>/usuario"><i class="fa fa-arrow-circle-left fa-1x"></i></a> <?php echo $this->titulo?> </h2>

<div class="col-lg-8 col-lg-offset-2">
<h4 class="page-header" style="text-align: center;"> Aqui podrás encontrar descuentos en diferentes productos y servicios</h4>
 </div>
<div class="row">
<a href="<?php echo $this->basePath()?>/usuario/club">
                <div class="col-lg-4 col-md-6">
                    <div class="panel panel-blue">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-bicycle fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Bicicletas</div>                                  
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalles</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
                </a>
<a href="<?php echo $this->basePath()?>/usuario/club">
                <div class="col-lg-4 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-cubes fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Juguetes</div>
                                    <div class="huge">Shingu Toys</div>                                  
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalles</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
                </a>
<a href="<?php echo $this->basePath()?>/usuario/club">
                <div class="col-lg-4 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-calendar-o fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Cortinajes</div>
                                    <div class="huge">???</div>                                  
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalles</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
                </a>
</div>