
	<div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <tbody>
                                        <tr class="odd gradeX">
                                            <td>Encomienda N&deg; </td>
                                            <td><label>01</label></td>
                                        </tr>
                                        <tr class="odd gradeX">
                                            <td>Departamento: </td>
                                            <td><label>602</label></td>
                                        </tr>
                                        <tr class="odd gradeX">
                                            <td>Para: </td>
                                            <td><label>Francisco Abarca</label></td>
                                        </tr>
                                        <tr class="odd gradeX">
                                            <td>Descripcion </td>
                                            <td><label>Televisor LED 38"</label></td>
                                        </tr>
                                    </tbody>
                                </table>
                                <div class="form-group" style="text-align: center;">                            
                                        <button type="submit" class="btn btn-success">Encomienda Entregada!</button>                                                                                                             
 
                                        </div>
                            </div>
                        </div>
                    </div>
                </div>
      </div>




