            <div class="row">
                <div class="col-xs-12">
                    <div class="panel panel-info">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <?php 
                                    $form = $this->form;
                                    $form->prepare();
                                    $form->setAttributes(array(
                                    //'action' =>$this->url.'/usuario/reclamo/nuevo',
                                    'action' =>$this->basePath('/usuario/comunicacion/nuevoreclamo'),
                                    'id'=> 'form_reclamo',
                                    'method' => 'post'
                                    ));
                                    echo $this->form()->openTag($form);
                                    echo $this->formRow($this->form->get('nombre'));
                                    ?>
                                        <div class="form-group">
                                            <label>Departamento</label>
                                            <?php                                             
                                              echo $this->formRow($this->form->get('nombre'));
                                            ?>
                                        </div>
                                        <div class="form-group">
                                            <label>Para</label>
                                            <?php 
                                              echo $this->formInput($this->form->get('nombre'));
                                            ?>                                            
                                        </div> 
                                        <div class="form-group">
                                            <label>Asunto</label>
                                            <?php 
                                              echo $this->formRow($this->form->get('asunto'));
                                            ?>
                                        </div>                                                                                  
                                        <div class="form-group">
                                            <label>Descripcion</label>                                            
                                            <?php 
                                              echo $this->formRow($this->form->get('nombre'));
                                            ?>
                                        </div>                                    
                                        <div class="form-group">
                                        <p class="help-block">Su reclamo sera notificado por nuestro sistema al Administrador</p>            
                                        <?php
                          
                                         echo " ".$this->formRow($this->form->get('reset')) ;
                                         echo " ".$this->formRow($this->form->get('send'));
                                        ?>
                                        </div>
                                    <?php echo $this->form()->closeTag()?>
                                </div>
                                <!-- /.col-lg-6 (nested) -->
                                <div class="col-lg-6">                                   
                                </div>
                                <!-- /.col-lg-6 (nested) -->
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
<script>
$("#form_reclamo").submit(function(e){
    $("#asunto_reclamo").prop("disabled", false);    
    var postData = $(this).serializeArray();
    var formURL = $(this).attr("action");
    $.ajax(
    {
        url : formURL,
        type: "POST",
        data : postData,
        dataType : 'json',
        success : function(response) {
            if(response.status == 'ok'){              
                toastr.success(response.desc)             
            }                                                       
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {            
         toastr.error("Ups! Ocurrio un problema, favor contacta con al equipo de soporte");      
        } 
    });
    e.preventDefault(); //STOP default action    
});
</script>                                  