

                <div class="col-xs-12">
                    <div class="panel panel-info">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <?php 
                                    $form = $this->form;
                                    $form->prepare();
                                    $form->setAttributes(array(
                                    //'action' =>$this->url.'/usuario/reclamo/nuevo',
                                    'action' =>$this->basePath('/usuario/comunicacion/nuevoreclamo'),
                                    'id'=> 'form_reclamo',
                                    'method' => 'post'
                                    ));
                                    echo $this->form()->openTag($form);
                                        ?>
                                             <div class="form-group">
                                                 <?php
                                               
                                                 echo $this->formRow($this->form->get('id_usuario'));
                                           ?>
                                        <div class="form-group">
                                        <div class="btn-group" data-toggle="buttons">
                                        <label class="btn btn-default">
                                            <input type="radio" name="ReclamoSugerencia" value="Reclamo"  id="ReclamoSugerencia"class="toggle">Reclamo</label>
                                        <label class="btn btn-default active">
                                        <input type="radio" name="ReclamoSugerencia" value="Sugerencia" checked="true" id="ReclamoSugerencia"class="toggle">Sugerencia</label>
                                        </div>
                                        </div>
                                        <div class="form-group">
                                            <label>Departamento</label>
                                            <?php  
                                        echo $this->formRow($this->form->get('id_unidad'));
                                
                                    ?>
                                             </div>
                                                 
                                        <div class="form-group">
                                            <label>Titulo</label>
                                            <?php                                             
                                              echo $this->formRow($this->form->get('titulo'));
                                            ?>
                                        </div>
                                        <div class="form-group">
                                            <label>Para</label>
                                            <?php 
                                              echo $this->formRow($this->form->get('id_reseptor'));
                                            ?>                                            
                                        </div> 
                                        <div class="form-group">
                                            <label>Asunto</label>
                                            <?php 
                                              echo $this->formRow($this->form->get('id_asunto'));
                                            ?>
                                        </div>
                                            <div class="form-group">
                                            <label>Mensaje</label>
                                            <?php 
                                              echo $this->formRow($this->form->get('mensaje'));
                                            ?>
                                        </div>  
                                                                 
                                        <div class="form-group">
                                        <p class="help-block">Su reclamo sera notificado por nuestro sistema al Administrador</p>            
                                        <?php
                          
                                         echo " ".$this->formRow($this->form->get('reset')) ;
                                         echo " ".$this->formRow($this->form->get('send'));
                                        ?>
                                        </div>
                                    <?php echo $this->form()->closeTag()?>
                                </div>
                                <!-- /.col-lg-6 (nested) -->
                                <div class="col-lg-6">                                   
                                </div>
                                <!-- /.col-lg-6 (nested) -->
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
<script>
    
$("#form_reclamo").submit(function(e){
    $("#id_unidad").prop("disabled", false);    
    var postData = $(this).serializeArray();
    var formURL = $(this).attr("action");
    $.ajax(
    {
        url : formURL,
        type: "POST",
        data : postData,
        dataType : 'json',
        success : function(response) {
            
            if(response.status == 'ok'){              
                toastr.success(response.desc) 
             $.ajax({            
            url: '<?php echo $this->basePath() . "/usuario/comunicacion/reclamo" ?>',
            type: 'post',
            success: function (response) {                             
                $('#menu_usuario').fadeIn('slow');
                $("#menu_usuario").html(response);

            }
        });    
            }                                                       
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {            
             $("#id_unidad").prop("disabled", true); 
         toastr.error("Ups! Ocurrio un problema, favor contacta con al equipo de soporte");      
        } 
    });
    e.preventDefault(); //STOP default action    
});
</script>                                  