  <br><br>
<br><br><br> 

<div class="row">
				<div class="col-md-12 ">
					<!-- BEGIN SAMPLE FORM PORTLET-->
					<div class="portlet box green">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-bullhorn"></i>  Reclamos del condominio  
							</div>                            
						</div>                                                                    
						<div class="portlet-body">                 
                            
                           <!-- 
                           <a onclick="modalNuevoReclamo()" data-toggle="modal" data-target="#modalNuevoReclamo" class="btn btn-success"> 
                           --> 
                           <a onclick="submenu('comunicacion/nuevoreclamo')" class="btn btn-success"> 
                           
                           <i class="fa fa-plus"></i> &nbsp;
                                    Nuevo Reclamo                            
                            </a>
                            
                            <br />
                              <br />
                            <table class="table">
								<thead>
								<tr>
									<th>
										 N&deg;
									</th>
                                                                      <!--  <th>
										 Titulo
									</th>-->
									<th>
										 Asunto
									</th>
									<th>
										 Origen
									</th>
									<th>
										 Me gusta
									</th>
								</tr>
								</thead>
								<tbody>
                                                                    <?php
                                                                    
                                                   if (!empty($reclamos)) {
                                                        foreach ($reclamos as $rcm) {
                                                            ?>
                                                        
								<tr>
									<td>
									 <?php echo $rcm['id']; ?>
									</td>
								<!--	<td>
							  	 <?php //echo $rcm['titulo']; ?>
									</td> -->
                                                                        <td>
							   <?php echo $rcm['id_asunto']; ?>
									</td>
									<td>
							  <?php echo "Dpto ".$rcm['id_unidad']; ?>
									</td>
                                                                        <td>
										<a class="btn btn-circle btn-default">
								            <i class="fa fa-thumbs-up"></i> <?php echo $rcm['cant_votos_pos']; ?>
                                        </a>	
                                                                            					<a class="btn btn-circle btn-default">
								            <i class="fa fa-thumbs-down"></i> <?php echo $rcm['cant_votos_neg']; ?>
                                        </a>	
							
									</td>
								</tr>
                                                    <?php }
                                                   
                                                                        }else{echo '<tr><td colspan="5">No existen reclamos pendientes</td> </tr>';}?>
								</tbody>
								</table>

                            
                            
                        </div>
                    </div>
                </div>
</div>                                                                         


<!-- MODAL Nuevo Reclamo -->

 
<!-- FIN MODAL Nuevo Reclamo -->
                    
<script>
toastr.options = {
  "positionClass": "toast-top-center",
}

 
</script>                                                   
