  <br><br>
<br><br><br> 
 

<div class="row">
				<div class="col-md-12 ">
					<!-- BEGIN SAMPLE FORM PORTLET-->
					<div class="portlet box green">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-bullhorn"></i>  Reclamos del condominio  
							</div>                            
						</div>                                                                    
						<div class="portlet-body">                 
                            
                           <!-- 
                           <a onclick="modalNuevoReclamo()" data-toggle="modal" data-target="#modalNuevoReclamo" class="btn btn-success"> 
                           --> 
                           <a onclick="submenu('comunicacion/nuevoreclamo')" class="btn btn-success"> 
                           
                           <i class="fa fa-plus"></i> &nbsp;
                                    Nuevo Reclamo                            
                            </a>
                            
                            <br />
                              <br />
                            <table class="table">
								<thead>
								<tr>
									<th>
										 N&deg;
									</th>
                                                                      <!--  <th>
										 Titulo
									</th>-->
									<th>
										 Asunto
									</th>
									<th>
										 Origen
									</th>
									<th>
										 Me gusta
									</th>
								</tr>
								</thead>
								<tbody>
                                                                    <?php
                                                                   
                                                   if (!empty($reclamos)) {
                                                        foreach ($reclamos as $rcm) {
                                                            ?>
                                                        
								<tr>
									<td>
									 <?php echo $rcm['id']; ?>
									</td>
								<!--	<td>
							  	 <?php //echo $rcm['titulo']; ?>
									</td> -->
                                                                        <td>


<div class="dropdown dropdown-extended dropdown-notification dropdown-dark " id="<?php echo $rcm['id']; ?>">
    
<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" 
   data-close-others="true" aria-expanded="true">
    
<?php echo $rcm['asunto'] ?>
 
</a>
<ul class="dropdown-menu">
 <div class="slimScrollDiv text-left" style="position: relative; overflow: hidden; width: auto; height: auto;">
     Titulo:<b><?php echo $rcm['titulo'] ?> </b> <hr>    
     Estado:<B><?php echo $rcm['estado'] ?> </b>  <hr>    
     
     Mensaje:<br><b>  
<?php echo $rcm['mensaje'] ?>
     </b>
    </div>
</ul>
</div>

                                                                 
                                                                        
                                                                        
                                                                        </td>
									<td>
							  <?php echo "Dpto ".$rcm['id_unidad']; ?>
									</td>
                                                                        <td>
                                                                         <a class="btn btn-circle btn-default" onclick="updown('comunicacion/megustareclamo','<?php echo$rcm['id']; ?>' )" >
								         <i class="fa fa-thumbs-up"></i> <?php echo $rcm['cant_votos_pos']; ?>
                                                                         </a>	
                                                                         <a class="btn btn-circle btn-default" onclick="updown('comunicacion/nomegustareclamo','<?php echo$rcm['id']; ?>' )" >
								         <i class="fa fa-thumbs-down"></i> <?php echo $rcm['cant_votos_neg']; ?>
                                                                         </a>
							
									</td>
								</tr>
                                                    <?php }
                                                   
                                                                        }else{echo '<tr><td colspan="5">No existen reclamos pendientes</td> </tr>';}?>
								</tbody>
								</table>

                            
                            
                        </div>
                    </div>
                </div>
</div>                                                                         


<!-- MODAL Nuevo Reclamo -->

 
<!-- FIN MODAL Nuevo Reclamo -->
                    
<script>
toastr.options = {
  "positionClass": "toast-top-center",
}

 
</script>                                                   
