<?php echo $this->doctype(); ?>
<?php

use Zend\Session\Container;
$sid = new Container('base');
$url = $this->basePath();
$perfil = $sid->offsetGet('perfil');
 if ($sid->offsetExists('usuario')){
 }else{
    header ("Location: $url/application/login");
    exit;
 }
 //si tiene el perfil de Conserje o Super Administrador
 if($perfil!="Conserje" && $perfil!="SuperAdmin"){
     header ("Location: $url/application/login/7");
    exit;
 }


?>
<html lang="es">
    <head>
        <?php echo $this->headTitle('Portal Conserjer&iacute;a ')->setSeparator(' - ')->setAutoEscape(false) ?>

       <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
      <link href="<?php echo $this->basePath()?>/img/check.ico" rel="shortcut icon" type="image/vnd.microsoft.icon"/>    
    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>    
    <link href="<?php echo $this->basePath()?>/sb2/css/bootstrap.css" rel="stylesheet" media="screen" type="text/css"/>
    <link href="<?php echo $this->basePath()?>/sb2/css/plugins/metisMenu/metisMenu.min.css" rel="stylesheet" media="screen" type="text/css"/>
    <link href="<?php echo $this->basePath()?>/sb2/css/plugins/timeline.css" rel="stylesheet" media="screen" type="text/css"/>
    <link href="<?php echo $this->basePath()?>/sb2/css/plugins/morris.css" rel="stylesheet" media="screen" type="text/css"/>
    <link href="<?php echo $this->basePath()?>/sb2/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" type="text/css"/>    
    <link href="<?php echo $this->basePath()?>/sb2/css/datepicker.css" rel="stylesheet"/>
    <link href="<?php echo $this->basePath()?>/sb2/css/calendar.css" rel="stylesheet"/>
    <link href="<?php echo $this->basePath()?>/sb2/css/custom2.css" rel="stylesheet"/>
    <link href="<?php echo $this->basePath()?>/sb2/css/plugins/dataTables.bootstrap.css" rel="stylesheet"/>
    <link href="<?php echo $this->basePath()?>/sb2/css/sb-admin-2.css" rel="stylesheet" media="screen" type="text/css"/>
    <link href="<?php echo $this->basePath()?>/sb2/css/backmodulos.css" rel="stylesheet" media="screen" type="text/css"/>
    <link href="<?php echo $this->basePath()?>/sb2/css/conserje.css" rel="stylesheet" media="screen" type="text/css"/>

    <script src="<?php echo $this->basePath()?>/sb2/js/jquery-1.11.0.js"></script>
    <script src="<?php echo $this->basePath()?>/sb2/js/jquery-ui.min.js"></script>
    <script src="<?php echo $this->basePath()?>/sb2/js/moments.min.js"></script>
    <script src="<?php echo $this->basePath()?>/sb2/js/bootstrap.min.js"></script>
    <script src="<?php echo $this->basePath()?>/sb2/js/bootstrap-datepicker.js"></script>
    <script src="<?php echo $this->basePath()?>/sb2/js/sb-admin-2.js"></script>
    
    <script src="<?php echo $this->basePath()?>/sb2/js/classie.js"></script>
    <script src="<?php echo $this->basePath()?>/sb2/js/jquery.calendario.js"></script>
    <script src="<?php echo $this->basePath()?>/sb2/js/plugins/metisMenu/metisMenu.min.js"></script>
    <script src="<?php echo $this->basePath()?>/sb2/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="<?php echo $this->basePath()?>/sb2/js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script src="<?php echo $this->basePath()?>/sb2/js/jquery.rut.js"></script>
    

    </head>
    <body>
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><img src="<?php echo $this->basePath()?>/img/logo2.png" style="max-width: 80px; margin-top: -12px;"/></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<?php echo $this->basePath()?>/conserje"> <i class="fa fa-home"></i> &nbsp;&nbsp;Inicio <span class="sr-only">(current)</span></a></li>
        <!--li><a href="#">Link</a></li-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-code-fork"></i> &nbsp;&nbsp;Atajos <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->basePath()?>/conserje/visita/registrar"> <i class="fa fa-user-plus"></i> &nbsp;&nbsp;Nueva visita</a></li>
            <li><a href="<?php echo $this->basePath()?>/conserje/encomienda/nuevo"> <i class="fa fa-archive"></i> &nbsp;&nbsp;Nueva encomienda</a></li>
            <li><a href="<?php echo $this->basePath()?>/conserje/notificacion"> <i class="fa fa-paper-plane"></i> &nbsp;&nbsp;Notificar comunidad</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input id="dptoSearchLayout" type="text" class="form-control" placeholder="Ingrese N&deg; Dpto" />
          <!-- se coloca capa para evitar el doble refresco del enter de la caja de dpto (ver que sucede) -->
          <div style="display:none"><input type="text" size="1"/></div>
        </div>
        <a id="verDptoLayout" class="btn btn-default"><i class="fa fa-search"> </i></a>
      </form>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><strong><?php  setlocale(LC_TIME, '').': ';echo iconv('ISO-8859-1', 'UTF-8', strftime('%A %d de %B de %Y', time()));?></strong></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mi perfil <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#"><i class="fa fa-user"></i> &nbsp;Mi perfil</a></li>
            <li><a href="#"><i class="fa fa-envelope"></i> &nbsp;Mensajes</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="<?php echo $this->basePath()?>/application/login/salir"><i class="fa fa-arrow-left"></i> &nbsp;Salir</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>
   <div id="wrapper">

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                     <?php echo $this->content; ?>
                </div>
            </div>
        </div>
    </div>

<!--button id="mm-menu-toggle" class="mm-menu-toggle">Toggle Menu</button>
  <div id="mm-menu" class="mm-menu">
    
        
                    <div class="col-lg-12" style="text-align: center;">

<img src="<?php echo $this->basePath()?>/img/logo2.png" style="max-width: 40%; margin-bottom: 20px; margin-top: 20px;"/>



</div>
    <ul class="mm-menu__items">

      <li class="mm-menu__item">

        <a class="mm-menu__link" href="<?php echo $this->basePath()?>/conserje" style="text-decoration: none;">

          <i class="fa fa-home fa-2x"></i>&nbsp;&nbsp; Inicio

        </a>

      </li>

      <li class="mm-menu__item">

        <a class="mm-menu__link" href="<?php echo $this->basePath()?>/conserje/visita" style="text-decoration: none;">

          <i class="fa fa-book fa-2x"></i>&nbsp;&nbsp; Libro de Visitas

        </a>

      </li>

      <li class="mm-menu__item">

        <a class="mm-menu__link" href="<?php echo $this->basePath()?>/conserje/finanzas" style="text-decoration: none;">

          <i class="fa fa-book fa-2x"></i>&nbsp;&nbsp; Libro de Encomiendas

        </a>

      </li>

      <li class="mm-menu__item">

        <a class="mm-menu__link" href="<?php echo $this->basePath()?>/application/index/db" style="text-decoration: none;">

          <i class="fa fa-book fa-2x"></i>&nbsp;&nbsp; Libro de Quinchos

        </a>

      </li>

      <li class="mm-menu__item">

        <a class="mm-menu__link" href="<?php echo $this->basePath()?>/application/perfil" style="text-decoration: none;">

          <i class="fa fa-user fa-2x"></i>&nbsp;&nbsp; Perfil

        </a>

      </li>

      <li class="mm-menu__item">

        <a class="mm-menu__link" href="<?php echo $this->basePath()?>/application/login/salir" style="text-decoration: none;">

          <i class="fa fa-sign-out fa-2x"></i>&nbsp;&nbsp; Salir

        </a>

      </li>    
    </ul>
  </div><!-- /nav -->
    <script>
    
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="//v2.zopim.com/?367fnhOP9mA9OB2vzEM72HnbitGVWMDY";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
  </script>

        <?php echo $this->inlineScript() ?>
<div class="modal fade" id="modalVerDptoLayout" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
               <div class="modal-dialog">
                 <div class="modal-content" >
                        
                         <div >
                         &nbsp;
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="panel panel-info">
                                            <div class="panel-heading">
                                            Resultado
                                             </div>
                                              <div id="msjVerDptoLayout"></div>  
                                                <div class="panel-body"  id="cuerpoDatosDptoLayout">
                                                <div class="form-group input-group">
                                                   <span class="input-group-addon"><i class="fa fa-home"></i> Dpto</span>
                                                   <input type="text" class="form-control" id="numeroDptoLayout"/>
                                                </div>
                                            <div class="form-group input-group">
                                                <span class="input-group-addon"><i class="fa fa-user"></i> Titular</span>
                                                <input type="text" id="titularDptoLayout" class="form-control"/>
                                            </div>
                                            <div class="form-group input-group">
                                                   <span class="input-group-addon">Contacto</span>
                                                <input type="text" id="contactoDptoLayout" class="form-control"/>
                                            </div>
                                            <div class="form-group input-group">
                                                <span class="input-group-addon">Condicion</span>
                                                <input type="text" class="form-control" id="condicionDptoLayout"/>
                                            </div>
                                            <div class="form-group" id="verTablaDptoLayout" align="left"></div>                                            
                                        </div>
                                           
                                        <div align="right" >
                                            
                                            <button data-dismiss="modal"  class="btn btn-danger">Cerrar</button>
                                            
                                        </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            </div>

                    </div>
                </div>
</div>
    </body>
    
</html>

<script>
    
    //evento click del boton
    $("#verDptoLayout").click(function(){
        getDpto();
    });
    //evento enter de la caja de texto del dpto
    $('#dptoSearchLayout').keypress(function (e) {
       if (e.which == 13){
           getDpto();
        }
     });
    
function getDpto()
{
    
$("#modalVerDptoLayout").modal('show');
$("#cuerpoDatosDptoLayout").hide();
if($("#dptoSearchLayout").val().length<1){
    $("#msjVerDptoLayout").html('<br/><div class="alert alert-danger alert-dismissable">Ingrese numero de departamento para encontrar...</div><br/>');
    return;
}
var dataPost = {'dpto' : $("#dptoSearchLayout").val()};

$("#msjVerDptoLayout").html('<div align="center"><br/><p class="text-success"><i class="fa fa-circle-o-notch fa-spin fa-3x"></i></p><br/></div>');
    
$.ajax( {
        url : '<?php echo $this->basePath()."/conserje/index/getdpto"?>',
        type : 'post', 
        data : 	dataPost,       	
		beforeSend : function() {			
			//
		},
		success : function(r) {
                   if(r.status=="ok"){
                    $("#numeroDptoLayout").val($("#dptoSearchLayout").val());
                    $("#titularDptoLayout").val(r.titular);
                    $("#contactoDptoLayout").val(r.contacto);
                    $("#condicionDptoLayout").val(r.condicion);
                    $("#verTablaDptoLayout").html(r.tabla);   
                    $("#msjVerDptoLayout").html('');
		    $("#cuerpoDatosDptoLayout").fadeIn(500);
                   }else{
                       
                    $("#msjVerDptoLayout").html('<br/><div class="alert alert-danger alert-dismissable">'+r.error+'</div><br/>');
		    $("#cuerpoDatosDptoLayout").hide();
                       
                   }   
		},
                error:function(e){
                    $("#msjVerDptoLayout").html('<br/><div class="alert alert-danger alert-dismissable">Error interno del sistema</div><br/>');
		    $("#cuerpoDatosDptoLayout").hide();

                }
});  
    
}
</script>