<div class="row">       
        <div class="col-lg-12">
                        <div class="panel panel-primary">
                        <div class="panel-heading">
                            <i class="fa fa-dollar" style="color: #fff;"></i> &nbsp;&nbsp;Egresos del condominio
                        </div>                            
                        <div class="panel-body text-center">                     

                 <!--1 2 3-->                                  
            <div class="row udt">
                        <?php  
                                        $form = $this->form;
                                        $form->prepare();
                                        $form->setAttributes(array(
                                        'action' => $this->url."/admin/finanzas/pagoegreso",                                  
                                        ));
                                        echo $this->form()->openTag($form);                                                                                                                                                                                                                                             
                        ?>  
            <!--Titulo-->
                  <div class="col-lg-12" style="margin-bottom: 20px;" >
                  <h3>En 3 pasos simples registre egresos del condominio</h3>
                  </div>
            <!--Fin Titulo-->                
            <!--1-->
                 <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                    <br /><br /> 
                        <div class="col-lg-12">                        
                            <i class="fa fa-hand-o-up" style="color: #585DA0; font-size: 42px;"></i> <br /><br />
                        </div>
                    
                        <div class="col-lg-12">
                        <?php                                             
                            echo $this->formRow($this->form->get('tipo_egreso'));
                        ?>     
                        </div>                    
                  </div>
             <!--Fin 1-->                  
             <!--Flecha 1-->  
              <div id="paso2" style="display: none;">      
                  <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1" style="display: table; height:122px;">                 
                    <i class="fa fa-arrow-circle-o-right" style="display: table-cell; vertical-align: middle; font-size: 28px;"></i>                    
                  </div>
             <!--Fin Flecha 1--> 
             <!--2-->              
                  <div id="div_prov" class="col-lg-3 col-md-3 col-sm-3 col-xs-3" style="display: none;">
                    <br /><br />
                        <div class="col-lg-12">                        
                            <i class="fa fa-truck" style="color: #585DA0; font-size: 42px;"></i><br /><br />
                        </div>                        
                        <div class="col-lg-12">                            
                            <?php                                             
                            echo $this->formRow($this->form->get('proveedores'));
                            ?>                           
                        </div>                    
                  </div>
                  <div id="div_trab" class="col-lg-3 col-md-3 col-sm-3 col-xs-3" style="display: none;">
                    <br /><br />
                        <div class="col-lg-12">                        
                            <i class="fa fa-users" style="color: #585DA0; font-size: 42px;"></i><br /><br />
                        </div>                        
                        <div class="col-lg-12"> 
                            <?php                                             
                            echo $this->formRow($this->form->get('trabajadores'));
                            ?>                        
                        </div>                    
                  </div>    
                  </div>         
             <!--Fin 2-->                  
             <!--Flecha 2-->   
             <div id="paso3" style="display: none;">                              
                  <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1" style="display: table; height:122px;">                 
                    <i class="fa fa-arrow-circle-o-right" style="display: table-cell; vertical-align: middle; font-size: 28px;"></i>                    
                  </div>
                        
             <!--Fin Flecha 2--> 
             <!--3-->                  
                <div id="div_3_proveedor" class="col-lg-3 col-md-3 col-sm-3 col-xs-3" style="display: none;">
                    <br /><br />
                        <div class="col-lg-12">                        
                            <i class="fa fa-dollar" style="color: #585DA0; font-size: 42px;"></i><br /><br />
                        </div>
                    
                        <div class="col-lg-12">
                            <?php                                             
                            echo $this->formRow($this->form->get('enviar'));
                            ?> 
                        </div>                    
                  </div> 
                  <div id="div_3_trabajador" class="col-lg-3 col-md-3 col-sm-3 col-xs-3" style="display: none;">
                    <br /><br />
                        <div class="col-lg-12">                        
                            <i class="fa fa-dollar" style="color: #585DA0; font-size: 42px;"></i><br /><br />
                        </div>
                    
                        <div class="col-lg-12">
                            <?php                                             
                            echo $this->formRow($this->form->get('enviar2'));
                            ?> 
                        </div>                    
                  </div> 
             </div>          
             <!--Fin 3--> 
                        <?php  
                            echo $this->form()->closeTag($form);                                                                                                                                                                                                     
                        ?>                                                 
            </div>
     <!--FIN 1 2 3-->                 
        
        
     <!-- TABLA -->
      <div id="tabla_egresos">

     </div>   
       <!-- FIN TABLA -->                   





            </div>
          </div>
        </div>       
     
     
                         
     </div> 
     
     
     
              
     
<!-- MODAL Pago Proveedor -->

<div class="modal fade bs-example-modal-lg" id="pagoprov" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>                    
                    <h4 class="modal-title" id="myModalLabel" style="text-align: center;">Pago Proveedores</h4>
            </div>
                <div id="modalpago" class="modal-body">Cargando...</div>
        </div>
    </div>             
</div>
<!-- FIN MODAL Pago Proveedor -->

<!-- MODAL Pago Trabajador -->

<div class="modal fade bs-example-modal-lg" id="pagotrab" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>                    
                    <h4 class="modal-title" id="myModalLabel" style="text-align: center;">Pago Remuneraciones</h4>
            </div>
                <div id="modalpagotrab" class="modal-body">Cargando...</div>
        </div>
    </div>             
</div>
<!-- FIN MODAL Pago Trabajador -->     

<!-- MODAL Cuotas -->

<div class="modal fade bs-example-modal-lg" id="modalCuotas" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>                    
                    <h4 class="modal-title" id="myModalLabel" style="text-align: center;">Pago Proveedores</h4>
            </div>
                <div id="bodycuotas" class="modal-body">Cargando...</div>
        </div>
    </div>             
</div>
<!-- FIN MODAL Cuotas -->         

<script>
function getTablaEgresos(){
    $.ajax( {  
        url  : '<?php echo $this->basePath()."/admin/finanzas/tablaegreso"?>',        
		type : 'post', 
        beforeSend: function(){
            $("#tabla_egresos").html("<div class='text-center'><i class='fa fa-spinner fa-spin' style='font-size:20px;'></i></div>");
        },     
		success : function(response) {
		  $("#tabla_egresos").html(response);                           
       }   
});    
}
toastr.options = {
  "positionClass": "toast-top-center",
}
getTablaEgresos();
/*$("#cproveedores").change(function(){
    var parametros = {"nombre_prov" : $("#cproveedores option:selected").text()};
    $.ajax( {  
        url  : '<?php echo $this->basePath()."/admin/finanzas/servicioprov"?>',
        data : parametros,
		type : 'post',      
		success : function(response) {
            if(response.flag=='si'){                    
                $("#cservicios").fadeIn(400);
                $("#irpagarprov").fadeOut(1);  
                var sel = $("#cservicios :input");
                sel.empty();
                    for (var i=0; i<response.cantidad; i++) {                    
                        sel.append('<option value="' + response.servicio[i][0]['id'] + '">' + response.servicio[i][0]['nombre'] + '</option>');
                        }
                  $("#irpagarprov").fadeIn(800);                    
            }else{
                $("#cservicios").fadeOut(400);
                $("#irpagarprov").fadeIn(400);                
            }                                
       }   
});     
});*/
function modalPago(){ 
   if ($("#combo_proveedores").val()=='0'){
        toastr.info("Debes seleccionar un proveedor");
   }
    var parametros =  {
        "nombre_prov" : $("#combo_proveedores option:selected").text(),
        "tipo_egreso" : $("#tipo_egreso option:selected").val(),                
                      };
	$.ajax( {  
        url  : '<?php echo $this->basePath()."/admin/finanzas/pagoegreso"?>',
        data : parametros,
		type : 'post',      
		success : function(response) {
		  $("#modalpago").html(response);
          return false;                              
       }   
});    
}
function modalPagoTrabajador(){ 
    var parametros =  {
        "nombre_trabajador" : $("#combo_trabajadores option:selected").text(),
        "id_trabajador" : $("#combo_trabajadores option:selected").val(),
        "id_tipo_egreso" : $("#tipo_egreso option:selected").val(),                
                      };
	$.ajax( {  
        url  : '<?php echo $this->basePath()."/admin/finanzas/modalpagotrabajador"?>',
        data : parametros,
		type : 'post',      
		success : function(response) {
		  $("#modalpagotrab").html(response);                              
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {            
         toastr.error("Ups! Ocurrio un problema, favor contacta con al equipo de soporte");      
        } 
});    
}
function modalCuotas(id){ 
    var parametros = {"id_egreso":id};
	$.ajax( {  
        url  : '<?php echo $this->basePath()."/admin/finanzas/modalcuotas"?>',
        data : parametros,
		type : 'post',      
		success : function(response) {
		  $("#bodycuotas").html(response);
          return false;                                  
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {            
         toastr.error("Ups! Ocurrio un problema, favor contacta con al equipo de soporte");      
        } 
});    
}
function paso2(){
    if($("#tipo_egreso").val()=="0"){
        hidePaso2();
    }else if ($("#tipo_egreso").val()=="1"){
        showP2trab(); 
        $("#paso3").fadeOut();      
    }else {
        showP2prov();
        $("#paso3").fadeOut(); 
    }
}
function paso3a(){
    if ($("#combo_proveedores").val()=='0'){
        $("#paso3").fadeOut(0);
    }else{
        $("#paso3").fadeIn(800);
        $("#div_3_proveedor").fadeIn(800);
        $("#div_3_trabajador").fadeOut();
    }   
}
function paso3b(){
    if ($("#combo_trabajadores").val()=='0'){
        $("#paso3").fadeOut(0);
    }else{
        $("#paso3").fadeIn(800);
        $("#div_3_trabajador").fadeIn(800);
        $("#div_3_proveedor").fadeOut();
    }    
}
function hidePaso2 (){
        $("#paso2").fadeOut();
        $("#paso3").fadeOut();        
}
function showP2prov (){
        $("#paso2").fadeIn(800);
        $("#div_trab").fadeOut(0);
        $("#div_prov").fadeIn(800);        

}
function showP2trab (){
        $("#paso2").fadeIn(800);
        $("#div_prov").fadeOut(0);    
        $("#div_trab").fadeIn(800);        

}
function borra_egreso(id){
bootbox.confirm("<strong>Se eliminar&aacute; este egreso, estas seguro...?</strong>", function(result) 
{
    if(result){
        var postData = {'id':id}
    	$.ajax({  
            url  : '<?php echo $this->basePath()."/admin/finanzas/borraegreso"?>',
            data : postData,
            type : 'post',      
            success : function(response) {
                if(response.status =='nok'){
                    toastr.error(response.desc);
                }else{
                    toastr.success(response.desc);
                } 
                getTablaEgresos();                                                   
            },
            error: function(jqXHR, textStatus, errorThrown) 
            {            
                toastr.error("Ups! Ocurrio un problema, favor contacta con al equipo de soporte");      
            }   
        }); 
     }else{
        toastr.info('Acci&oacute;n cancelada');
     }
});    
}
</script>                                                         