<div class="row">
   <div class="col-lg-12">
      <div class="panel panel-primary">
         <div class="panel-heading">
            <i class="fa fa-dollar" style="color: #fff;"></i> &nbsp;&nbsp;Ingresos del condominio
         </div>
         <div class="panel-body">
            <div class="row">
               <!--div class="col-lg-12" style="margin-bottom: 20px;" >
                  <h2 class="text-center"> <i class="fa fa-money"></i> Pago Gastos comunes</h2>
                  </div-->
               <div class="col-lg-12">
                  <div class="form-group form-md-line-input">
                     <div class="col-md-6">
                        <div class="input-group input-group-lg" style="margin-bottom: 40px;">
                           <div class="input-group-control">
                              <input id="nombre_dpto" type="text" class="form-control input-lg" placeholder="Ingrese N&deg; vivienda" >
                              <div class="form-control-focus">
                              </div>
                           </div>
                           <span class="input-group-btn btn-right">
                           <button id="btn_busca_dpto" onclick="buscaDpto()" class="btn green-haze" type="button"><i style="font-size: 18px;"class="fa fa-search"></i> &nbsp;Buscar!</button>
                           </span>
                        </div>
                     </div>
                     <div class="col-md-6" style="display: block;">
                                <a onclick="modalAbono()" data-target="#modalAbono" data-toggle="modal" class="btn btn-info"><i class="fa fa-plus"></i>&nbsp; Realizar Abono</a>
                                
                                <a class="btn btn-info"><i class="fa fa-plus"></i>&nbsp; Pagos Masivos</a>
                     </div>
                  </div>
                  <br />  <br />
                  <div id="resultado_ingresos">
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

<div class="modal fade bs-example-modal-md" id="modalingreso" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>                    
                    <h4 class="modal-title" id="myModalLabel" style="text-align: center;">Realizar Ingreso de Dinero</h4>
            </div>
                <div id="modalpagogc" class="modal-body">Cargando ...</div>
        </div>
                 <!-- /.modal-content -->
    </div>
               <!-- /.modal-dialog -->
</div>

<div class="modal fade bs-example-modal-md" id="modalAbono" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>                    
                    <h4 class="modal-title" id="myModalLabel" style="text-align: center;">Realizar Abono de Dinero</h4>
            </div>
                <div id="modalAbonobody" class="modal-body">Cargando ...</div>
        </div>
                 <!-- /.modal-content -->
    </div>
               <!-- /.modal-dialog -->
</div>
<script>
$("#pagogc").click(function(){
	$.ajax( {  
        url : '<?php echo $this->basePath()."/admin/finanzas/pagogc"?>',
		type : 'post',
        beforeSend : function() {
           $('#tablapagoun2').DataTable().clear();          
            },        
		success : function(response) {
	           console.log(response)                     
       }   
});
});  

function modalPago(dpto){   
postData = {'id_unidad' : dpto}  
	$.ajax( {
        url : '<?php echo $this->basePath()."/admin/finanzas/modalpago"?>',
        type : 'post', 
        data : 	postData,       	
		success : function(response) {
			$("#modalpagogc").html(response);
		}
	});  
}     
function modalAbono(){   
postData = {'id_unidad' : $("#id_uni_abono").val()}  
	$.ajax( {
        url : '<?php echo $this->basePath()."/admin/finanzas/modalabono"?>',
        type : 'post', 
        data : 	postData,       	
		success : function(response) {
			$("#modalAbonobody").html(response);
		}
	});  
}   
function buscaDpto(){
    var postData = {'nombre' : $("#nombre_dpto").val()}
    $.ajax( {
        url : '<?php echo $this->basePath()."/admin/finanzas/getingresos"?>',
        type : 'post', 
        data : 	postData,   
        beforeSend: function(){
            $("#btn_busca_dpto").attr('disabled','disabled');
            $("#resultado_ingresos").html("<i class='fa fa-spinner fa-spin' style='font-size:25px;'></i>");
        },    	
		success : function(response) {
		  if(response.status=="nok"){
		      $("#resultado_ingresos").html("");
              $("#btn_busca_dpto").removeAttr('disabled');
              toastr.clear();
		      toastr.info(response.desc);
              $("#nombre_dpto").val("")               
		  }else{
            $("#resultado_ingresos").html("");
			$("#resultado_ingresos").html(response);
            $("#btn_busca_dpto").removeAttr('disabled');
            toastr.clear();
            toastr.success("Busqueda Exitosa para vivienda "+$("#nombre_dpto").val());
          } 
		},        
	}); 
}
</script>    
                        