<div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>N&deg; Cuota</th>
                                            <th>Fecha Vencimiento</th>
                                            <th>Valor</th>
                                            <th>Estado</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                       <?php for($i=0;$i<count($cobros);$i++){ 
                                       $pf = strtotime($cobros[$i]['fecha_cobro']);
                                       setlocale(LC_ALL,"es_CL");
                                        $mostrarFi = date("d F Y", $pf);
                                        if($cobros[$i]['estado']=="impaga"){$label="danger";$icn="close";}else{$label="success";$icn="check";}
                                       echo "
                                       
                                        <tr>
                                            <td>".$cobros[$i]['desc']."</td>
                                            <td>".$mostrarFi."</td>
                                            <td>$ ".number_format($cobros[$i]['valor'],"0",".",".")."</td>
                                            <td><span class='label label-sm label-".$label."'>".ucfirst($cobros[$i]['estado'])." <i class = 'fa fa-$icn'></i></span></td>
                                        </tr>";
                                         }?>
                                    </tbody>
                                </table>
</div>