<div class="row">

<?php  
                                        $form = $this->form;
                                        $form->prepare();
                                        $form->setAttributes(array(
                                        'action' => $this->basePath()."/admin/finanzas/pagoegreso",
                                        'method' => 'post', 
                                        'id' => 'form_pago_egreso'                                   
                                        ));
                                        echo $this->form()->openTag($form);
                                        echo $this->formRow($this->form->get('id_tipo_egreso'));
                                        echo $this->formRow($this->form->get('id_prov')); 
                                        echo $this->formRow($this->form->get('concepto'));
                                        echo $this->formRow($this->form->get('foto'));
                                        echo $this->formRow($this->form->get('cuota1'));                                                                           
                                        echo $this->formRow($this->form->get('cuota2'));
                                        echo $this->formRow($this->form->get('cuota3'));
                                        echo $this->formRow($this->form->get('cuota4'));
                                        echo $this->formRow($this->form->get('cuota5'));
                                        echo $this->formRow($this->form->get('cuota6'));
                                        echo $this->formRow($this->form->get('cuota7'));
                                        echo $this->formRow($this->form->get('cuota8'));
                                        echo $this->formRow($this->form->get('cuota9'));
                                        echo $this->formRow($this->form->get('cuota10'));
                                        echo $this->formRow($this->form->get('cuota11'));
                                        echo $this->formRow($this->form->get('cuota12'));                                        
                                        ?> 
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="col-lg-5 col-md-5 col-sm-5 col-xs-5" style="text-align: center;">
    <div class="form-group">
        <label>Origen</label>
            <div class="form-group">
                <?php                                             
                    echo $this->formRow($this->form->get('origen'));
                 ?>                                  
            </div>
    </div>
</div> 

<div class="col-lg-1 col-md-1 col-sm-1 col-xs-1" style="margin-top: 27px;">
&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-arrow-circle-o-right fa-2x"></i>
</div>

<div class="col-lg-6 col-md-6 col-sm-6 col-xs-5" style="text-align: center;">
    <div class="form-group">
        <label>Destino</label>
            <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-truck"></i>
            </span>
                 <?php                                             
                    echo $this->formRow($this->form->get('destino'));
                 ?>                                            
            </div>
    </div>
</div>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="divformapago">
    <div class="form-group">
        <label>Pago :</label><br />
        <label class="radio-inline" >
               <?php                                             
                    echo $this->formRow($this->form->get('radiototal'));
                 ?>
        </label>
        <label class="radio-inline">
               <?php                                             
                    echo $this->formRow($this->form->get('radiocuotas'));
                 ?>
        </label>
    </div>
</div>
<!--Pago Total -->

<div id="divpagototal">

<div class="col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3 text-center">
    <div class="form-group">
        <label style="font-size: 19px;">Monto</label>
            <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-dollar"></i>
            </span>
                 <?php                                             
                    echo $this->formRow($this->form->get('monto'));
                 ?>                                            
            </div>
    </div>
</div>
</div>

<!--Pago Cuotas-->
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="divpagocuotas">
<div class="col-lg-6">
<div class="col-lg-12 col-md-4 col-xs-6">
    <div class="form-group">
        <label>Monto</label>
            <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-dollar"></i>
            </span>
                 <?php                                             
                    echo $this->formRow($this->form->get('montocuota'));
                 ?>                                            
            </div>
    </div>
</div>
<div class="col-lg-12 col-md-4 col-xs-6">
    <div class="form-group">
        <label>Seleecione cantidad</label>
            <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-sort-numeric-asc"></i>
            </span>
                 <?php                                             
                    echo $this->formRow($this->form->get('nmro_cuotas'));
                 ?>                                            
            </div>
    </div>
</div>
</div>

<div class="col-lg-6">
    <table class="table table-striped table-bordered table-hover" >
       <tbody id="listacuota"> 
            <tr>
                <th>Cuota</th>
                <th>Valor</th>                                 
            </tr>         
            <tr>                                                                  
              </tr>                                                                                           
        </tbody>
    </table>
</div>  

</div>

</div>

<hr width="80%"/>


<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div id="formaspago" class="form-group">
        <label>M&eacute;todo de Pago :</label><br />
        <label class="radio-inline">
               <?php                                             
                    echo $this->formRow($this->form->get('efectivo'));
                 ?>
        </label>
        <label class="radio-inline">
               <?php                                             
                    echo $this->formRow($this->form->get('transferencia'));
                 ?>
        </label>
        <label class="radio-inline">
               <?php                                            
                    echo $this->formRow($this->form->get('cheque'));
                 ?>
        </label>
        <label class="radio-inline">
               <?php                                             
                    echo $this->formRow($this->form->get('debito'));
                 ?>
        </label>
    </div>
</div> 
<!--EFECTIVO-->
<div id="divefectivo" style="display: none;">
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style=" display: inline-block; ">
    <div class="form-group">
        <label>Fecha de Pago</label>
            <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-calendar"></i>
            </span>
                 <?php                                             
                    echo $this->formRow($this->form->get('fecha'));
                    
                 ?>                                                        
            </div>
    </div>
</div>
</div>
<!--TRANSFERENCIA-->
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="divtransferencia" style="display: none;">
<div class="col-lg-5 col-md-5 col-sm-5 col-xs-5" style="text-align: center;">
    <div class="form-group">
        <label>N&deg; Operaci&oacute;n</label>
            <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-info"></i>
            </span>
                 <?php                                             
                    echo $this->formRow($this->form->get('nmrooperacion'));
                 ?>                                            
            </div>
    </div>
</div>
<div class="col-lg-5 col-md-5 col-sm-5 col-xs-5" style="text-align: center;">
    <div class="form-group">
        <label>Banco Destino</label>
            <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-university"></i>
            </span>
                 <?php                                             
                    echo $this->formRow($this->form->get('id_banco'));
                 ?>                                            
            </div>
    </div>
</div>
<div class="col-lg-5 col-md-5 col-sm-5 col-xs-5" style="text-align: center;">
    <div class="form-group">
        <label>Fecha de Pago</label>
            <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-calendar"></i>
            </span>
                 <?php                                             
                    echo $this->formRow($this->form->get('fecha'));
                 ?>                                            
            </div>
    </div>
</div>
</div>
<!--CHEQUE-->
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="divcheque" style="display: none;">
<div class="col-lg-5 col-md-5 col-sm-5 col-xs-5" style="text-align: center;">
    <div class="form-group">
        <label>N&deg; Cheque</label>
            <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-info"></i>
            </span>
                 <?php                                             
                    echo $this->formRow($this->form->get('nmrocheque'));
                 ?>                                            
            </div>
    </div>
</div>
<div class="col-lg-5 col-md-5 col-sm-5 col-xs-5" style="text-align: center;">
    <div class="form-group">
        <label>Fecha de Pago</label>
            <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-calendar"></i>
            </span>
                 <?php                                             
                    echo $this->formRow($this->form->get('fecha'));
                 ?>                                            
            </div>
    </div>
</div>
</div>
<!--DEBITO-->
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="divdebito" style="display: none;">
<div class="col-lg-5 col-md-5 col-sm-5 col-xs-5" style="text-align: center;">
    <div class="form-group">
        <label>N&deg; Operaci&oacute;n</label>
            <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-dollar"></i>
            </span>
                 <?php                                             
                    echo $this->formRow($this->form->get('nmrooperacion'));
                 ?>                                            
            </div>
    </div>
</div>
<div class="col-lg-5 col-md-5 col-sm-5 col-xs-5" style="text-align: center;">
    <div class="form-group">
        <label>Fecha de Pago</label>
            <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-calendar"></i>
            </span>
                 <?php                                             
                    echo $this->formRow($this->form->get('fecha'));
                 ?>                                            
            </div>
    </div>
</div>
</div>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
<div class="col-lg-4 col-lg-offset-8 col-md-4 col-md-offset-8 col-sm-4 col-sm-offset-8 col-xs-6 col-xs-offset-6">
    <div class="form-group">
        <label style="font-size: 19px;">Total a Pagar</label>
            <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-dollar"></i>
            </span>
                 <?php                                             
                    echo $this->formRow($this->form->get('montototal'));
                 ?>                                            
            </div>
    </div>
</div>
<div id="noktotal" class="col-lg-1" style="margin: 32px 0 0 -20px; display: none; ">

<i class="fa fa-close"></i>

</div>

<div id="oktotal" class="col-lg-1" style="margin: 32px 0 0 -20px; display: none; ">

<i class="fa fa-check"></i>

</div>
</div>
<hr width="80%"/>
<div class="col-lg-6 col-sm-6 col-md-6 col-xs-6" style="text-align: center;">
    <div class="form-group">
        <label>Observaci&oacute;n</label>
            <div class="form-group">
                 <?php                                             
                    echo $this->formRow($this->form->get('observacion'));
                 ?>                                            
            </div>
    </div>
</div>

<div class="col-lg-6">
<div class="col-lg-4  udt">
<br />
<a>
  <a id="mostrarnombre" class="btn btn-success"><i id="icnAdjuntarEgreso" class="fa fa-file"></i> Adjuntar Boleta</a>      
        <?php 
            echo $this->formRow($this->form->get('nombrefile'));
        ?>                                                                                                                                                                                                                                                                              
</a> 
</div>
</div>
<!--BOTONES-->
<div class="col-lg-12 col-md-12 col-xs-12 text-right">

    <?php                                             
        echo $this->formRow($this->form->get('cancel'));
    ?>

    <?php                                             
        echo $this->formRow($this->form->get('sendpago'));
    ?>                                                                                                                 

</div> 
</div>
<script>
toastr.options = {
  "positionClass": "toast-top-center",
}
function isNumber(e) {
k = (document.all) ? e.keyCode : e.which;
if (k==8 || k==0) return true;
patron = /\d/;
n = String.fromCharCode(k);
return patron.test(n);
}
function selecciona(){
    if(document.getElementById('egreso_file').files[0].size<2000000){  	                        
            var file_data = $('#egreso_file').prop('files')[0];
            var parametros = new FormData();                  
                           parametros.append('fileData', file_data);
                           $.ajax( {
                                    contentType:false,
                                    processData:false,	
                                    cache:false,
                                    data : parametros,
                                    url : '<?php echo $this->basePath()."/admin/finanzas/egresofile"?>',
                                    type : 'post',
                                    beforeSend : function() {
                                        loadImg();
                                    },
                                    success : function(response) {
                                        if(response.status == "nok"){
                                            toastr.warning(response.desc);
                                            unloadImg()
                                        }else{
                                            toastr.success(response.desc);       
                                            $("#sendpago").removeAttr('disabled');                                                                                                                            
                                            $("#sendpago").val('Ingresar Pago al sistema');                                        
                                            document.getElementById("mostrarnombre").innerHTML="Archivo subido OK: [<strong>"+document.getElementById('egreso_file').files[0].name+"</strong>]";
                                            $("#foto").val(response.name);   
                                        }
                                                                                                              
                                    },      
                            });
        
    }else{
     document.getElementById("mostrarnombre").innerHTML="<font color='red'>Error Ha superado el limite permitido (2Mb): [<strong>"+document.getElementById('egreso_file').files[0].name+"</strong>] NOK</font>";
    }
}    
function loadImg(){
    $("#sendpago").attr('disabled','disabled');
    $("#egreso_file").add('class','btn-warning');                                        
    $("#sendpago").val('Subiendo imagen...');
    $("#icnAdjuntarEgreso").attr("class","fa fa-spinner fa-spin");    
}  
function unloadImg(){
    $("#sendpago").removeAttr('disabled');
    $("#egreso_file").add('class','btn-success');                                        
    $("#sendpago").val('Adjuntar Boleta');
    $("#icnAdjuntarEgreso").attr("class","fa fa-file"); 
    $("#sendpago").val('Ingresar Pago al sistema');      
}   

function closeModal(){
    $('#pagoprov').modal('hide');
}
function mostrarTotal(){
    $('#divpagocuotas').css("display","none");    
    $("#montocuota").attr("disabled","disabled");
    
    $('#monto').removeAttr("disabled");
    $('#divpagototal').css("display","block"); 
    $('#montototal').val($('#montototal').val());          
}
function validaDestino(){
     var index = $('#destino').find('option:selected').val();
        if (index == '0'){
            alert("Selecciona el destino del dinero!");
            $('#sendpago').attr("disabled","disabled");
        }else{
            
        }    
    
}
function mostrarCuotas(){    
    $('#divpagototal').css("display","none");
    $('#montocuota').removeAttr("disabled");    
    $('#montototal').val("");
    $('#total').attr("disabled","disabled");
    $('#monto').attr("disabled","disabled"); 
    $('#divpagocuotas').css("display","block");                   
}
function calculaCuota(){
   $("#listacuota").find("tr:gt(0)").remove();
   $("#montocuota").attr("disabled","disabled");
   var cuotas =  $("#cuotas option:selected" ).text()
   var monto  =  $("#montocuota").val().replace(/\./g,'')
   var valor  = monto/cuotas;
   var resto = Math.round((valor%1)*cuotas);
        for (i=0;i<cuotas;i++){
        $("#listacuota").append('<tr><td  style="text-align: center;">Cuota '+(i+1)+'</td><td  id="f'+i+'"style="text-align: center;">$ '+(Math.floor(valor)+"").replace(/\B(?=(\d{3})+(?!\d))/g, ".")+'</td></tr>')
        $("input[name=cuota"+(i+1)+"]").val((Math.floor(valor)));
        }
   var cuota1 = parseInt($("#f0").text().replace("$ ","").replace(/\./g,''))+resto
   var cuota1 = (cuota1+"").replace(/\B(?=(\d{3})+(?!\d))/g, ".")
   $("#f0").text("$ "+cuota1);
   $("#montototal").val(cuota1);                
}
function formatMonto(){  
    var format = $("#monto").val().replace(/\./g,'').replace(/\B(?=(\d{3})+(?!\d))/g, ".")
    $("#monto").val(format);
    $("#montototal").val(format);
}
function formatMonto2(){  
    var format = $("#montocuota").val().replace(/\./g,'').replace(/\B(?=(\d{3})+(?!\d))/g, ".")
    $("#montocuota").val(format);
    $("#montototal").val(format);
    if ($("#montocuota").val().replace(/\./g,'')>0){$("#cuotas").removeAttr("disabled")}
}
function mostrarEfectivo(){    
    $('#divtransferencia').css("display","none");
    $('#divdebito').css("display","none");
    $('#divcheque').css("display","none");     
    $('#divcheque :input').attr("disabled","disabled");   
    $('#divdebito :input').attr("disabled","disabled"); 
    $('#divtransferencia :input').attr("disabled","disabled");
    
    $('#divefectivo :input').removeAttr("disabled");
    $('#divefectivo').css("display","block");  
}
function mostrarTrans(){       
    $('#divefectivo').css("display","none");
    $('#divdebito').css("display","none");
    $('#divcheque').css("display","none");       
    $('#divcheque :input').attr("disabled","disabled");   
    $('#divdebito :input').attr("disabled","disabled");
    $('#divefectivo :input').attr("disabled","disabled");
    $('#divtransferencia :input').removeAttr("disabled");
    $('#divtransferencia').css("display","block");     
}
function mostrarCheque(){   
    $('#divefectivo').css("display","none");  
    $('#divtransferencia').css("display","none");
    $('#divdebito').css("display","none");
    $('#divdebito :input').attr("disabled","disabled");
    $('#divtransferencia :input').attr("disabled","disabled");    
    $('#divefectivo :input').attr("disabled","disabled");
    
    $('#divcheque :input').removeAttr("disabled");
    $('#divcheque').css("display","block");         
}
function mostrarDebito(){       
    $('#divefectivo').css("display","none");  
    $('#divtransferencia').css("display","none");
    $('#divcheque').css("display","none"); 
    $('#divcheque :input').attr("disabled","disabled");
    $('#divtransferencia :input').attr("disabled","disabled");    
    $('#divefectivo :input').attr("disabled","disabled");
    $('#divdebito :input').removeAttr("disabled");
    $('#divdebito').css("display","block");     
}
/*function validaMonto(){
    var select = $('#divdetalle2').find('input:checkbox:checked').length;
    //Valido si selecciona checkbox 
    if (select > 0){
         a=0;
         $("#noktotal").css('display','none');
         $('#divdetalle2').find('input:checkbox:checked').each( function(){a = a + parseInt($(this).val());});    
         var monto = $('#monto').val().replace(".","");
            //Valido que monto sea superior a lo seleccionado
            if (monto > a){
                    $("#noktotal").css('display','inline-block');                    
                    $("#oktotal").css('display','none');         
                    alert("El monto debe ser igual o superior \n con respecto a los items seleccionados");           
                    $('#monto').val('');
            }else{
                    $("#oktotal").css('display','inline-block');
                    $("#noktotal").css('display','none');
        
       }
    }else{
        
        
    }
}*/
/*
$("#monto").keyup(function () {
      var value = $(this).val();
      $("monto").text(value);
    }).keyup();
*/
/*
function sumar(){
a = 0;
$('#divdetalle2').find('input:checkbox:checked').each( function(){a = a + parseInt($(this).val());});
    var formatotal = a.toFixed(1).replace(/\d(?=(\d{3})+\.)/g, '$&.');
    var respuesta = formatotal.substring(0,formatotal.length-2);          
$('#total2').text('$ '+respuesta);
$('#monto').val(respuesta);
$("#noktotal").css('display','none');
$("#oktotal").css('display','inline-block');
} 
$("#divformapago input[type='radio']").change(function () {
        var pago =  $("#divformapago input[type='radio']:checked").val();
            if(pago =='total'){
                    var monto = $("#total1").text().replace("$ ","");
                    
                        $("#monto").val(monto);
                        $("#monto").attr('disabled','disabled');
                        $("#oktotal").css('display','inline-block'); 
            }else{
                        $("#oktotal").css('display','none');
                        $("#monto").removeAttr('disabled');
                        $("#monto").val('');                         
}});*/
$("#radiototal").trigger('click'); 
$("#radioefectivo").trigger('click');        
$("#form_pago_egreso").submit(function(e){
    $("#destino").prop("disabled", false);
    $("#montototal").prop("disabled", false); 
    var postData = $(this).serializeArray();
    var formURL = $(this).attr("action");
    $.ajax(
    {
        url : formURL,
        type: "POST",
        data : postData,
        dataType : 'json',
        success : function(response) {
            if(response.status == 'ok'){
             $("#pagoprov").modal('hide');  
             toastr.success(response.desc)
            }                                           
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {   alert("error");         
            /*$("#todo").css("display","none");
            $("#respuestanok").css("display","block");
            $("#descrnok").text("Ups! Ocurrio un problema, favor intenta nuevamente"); */     
        }
    });
    e.preventDefault(); //STOP default action
    e.unbind(); //unbind. to stop multiple form submit.
});
</script>