<div class="row">
				<div class="col-md-12 ">
					<!-- BEGIN SAMPLE FORM PORTLET-->
					<div class="portlet box green">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-dollar"></i>  Resumen financiero  
							</div>                            
						</div>
                        <div class="portlet-body"> 
                        
                        <div class="row">
                        <div class="col-lg-6 col-md-6">
                             <div class="table-responsive text-center" >
                                  <table class="table table-striped table-bordered table-hover" id="data-table-conserje">
                                                <tbody>
                                                <tr>
                                                        <th  class="text-center" WIDTH="200" style="font-size: large;">Fondo Operacional</th>
                                                        <td id="saldo"  style="font-size: 22px;"><strong>$ <?php echo number_format($this->fondo,"0",".",".") ;?></strong></td>
                                                </tr>
                                                <tr>
                                                        <th  class="text-center" style="font-size: large;">Fondo Reserva</th>
                                                        <td style="font-size: 22px;"><strong>$ <?php echo number_format($this->fondores,"0",".",".");?></strong></td>
                                                </tr>                                                
                                                <tr>
                                                        <th class="text-center" style="font-size: large;">Caja Chica</th>
                                                        <td style="font-size: 22px;"><strong>$ <?php echo $this->morosos;?></strong></td>
                                                </tr>
                                                <tr>
                                                        <th class="text-center" style="font-size: large;">Morosos</th>
                                                        <td style="font-size: 22px;"><strong>$<?php echo $this->cajachica;?></strong></td>
                                                </tr>
                                                </tbody>
                                  </table>
                            </div>
                  
                        </div>  
                                                        
                        <div class="col-lg-6 col-md-6">
                            <div class="panel panel-default">
                                <div class="panel-heading" style="background: none;">
                                    <i class="fa fa-user"></i>&nbsp; Estimado Antonio Cebada
                                </div>
                                <div class="panel-body">
                                    <p><i class="fa fa-clock-o"></i>&nbsp; Quedan <strong><?php echo $this->dias_restantes?> d&iacute;as</strong> para el cierre del mes administrativo</p>
                                    <p><p><i class="fa fa-dollar"></i>&nbsp; Aun existen <strong>18 Pagos</strong> pendientes</p>
                                    <p><p><i class="fa fa-wrench"></i>&nbsp; Este mes hay <strong>4 Mantenciones</strong> programadas</p>
                                    <p><p><i class="fa fa-bullhorn"></i>&nbsp; Se registran <strong>2 Reclamos</strong> por Gastos Comunes</p>
                                </div>
                            </div>
                        </div>
                        
                        </div>
                  
                  
                  <div class="row">
                  <div class="col-md-6 ">
					<!-- BEGIN SAMPLE FORM PORTLET-->
					<div class="portlet box red">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-upload"></i>  Ultimos 30 Egresos  
							</div>                            
						</div>
                        <div class="portlet-body"> 
                        <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>N&deg;</th>                                            
                                            <th>Fecha</th>
                                            <th>Destino</th>
                                            <th>Monto</th>
                                        </tr>
                                    </thead>
                                    <tbody style="text-align: center;">
                                       <?php for($i=0;$i<count($this->egresos);$i++){ 
                                       echo "
                                       
                                        <tr>
                                            <td>".$this->egresos[$i]['id']."</td>
                                            <td>".$this->egresos[$i]['fecha_pago']."</td>
                                            <td>".$this->egresos[$i]['destino']."</td>
                                            <td>$ ".number_format($this->egresos[$i]['monto'],"0",".",".")."</td>
                                        </tr>";
                                         }?>
                                    </tbody>
                                </table>
                            </div>
 
                        </div>
                    </div>
                    </div>
                   <div class="col-md-6 ">
					<!-- BEGIN SAMPLE FORM PORTLET-->
					<div class="portlet box blue-madison">
						<div class="portlet-title blue-madison">
							<div class="caption">
								<i class="fa fa-upload"></i>  Ultimos 30 Ingresos  
							</div>                            
						</div>
                        <div class="portlet-body"> 
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>N&deg;</th>
                                            <th>Fecha</th>
                                            <th>Origen</th>
                                            <th>Monto</th>
                                        </tr>
                                    </thead>
                                    <tbody style="text-align: center;">
                                       <?php for($i=0;$i<count($this->ingresos);$i++){ 
                                       echo "
                                       
                                        <tr>
                                            <td>".$this->ingresos[$i]['id']."</td>
                                            <td>".$this->ingresos[$i]['fecha_pago']."</td>
                                            <td>".$this->ingresos[$i]['origen']."</td>
                                            <td>$ ".number_format($this->ingresos[$i]['monto'],"0",".",".")."</td>
                                        </tr>";
                                         }?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                     </div>
                   </div>
                </div>
            </div>
        </div>
     </div>
</div>

               
                 
                  
<script>
function format(td)
{
var num = input.value.replace(/\./g,'');
num = num.toString().split('').reverse().join('').replace(/(?=\d*\.?)(\d{3})/g,'$1.');
num = num.split('').reverse().join('').replace(/^[\.]/,'');
input.value = num;
}
else{ alert('Solo se permiten numeros');
input.value = input.value.replace(/[^\d\.]*/g,'');
}
}
</script>                        