      <div class="col-lg-12">
                <h3 class="page-header" ><i class="fa fa-check" style="font-size: 20px;"></i> &nbsp;&nbsp;Proveedores Activos</h3>    
      </div>
       <div class="col-lg-12">
     <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                    <tr>
                                            <th>Nombre</th>
                                            <th>Servicio</th>
                                            <th>Tel&eacute;fono</th>
                                            <th>&Uacute;ltimo Pago</th>
                                            <th>Acci&oacute;n</th>
                                            
                                    </tr>
                                    </thead>
                                    <tbody style="text-align: center;">
                                       <?php 
                                       echo $tabla;
                                         ?>
                                    </tbody>
                                </table>
                            </div>
     </div> 