      <div class="col-lg-12">
                <h3 class="page-header" ><i class="fa fa-list-alt" style="font-size: 20px;"></i> &nbsp;&nbsp;Egresos del condominio</h3>    
      </div>
       <div class="col-lg-12">
     <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>N&deg;</th>
                                            <th>Fecha del Egreso</th>
                                            <th>Origen</th>
                                            <th>Destino</th>
                                            <th>Monto</th>
                                            <th>Boleta</th>
                                            <th>Cuotas</th>
                                            <th>Acci&oacute;n</th>
                                        </tr>
                                    </thead>
                                    <tbody style="text-align: center;">
                                       <?php 
                                       echo $tabla;
                                         ?>
                                    </tbody>
                                </table>
     </div>
     </div> 