<script>
function button(val) {
 
 $(".btns").css("height", "70px");
 $(".btns").css("width", "105px");
 $(".btns").css("border", "2px solid #ffffff");
  
    val.style.height = "80px";
    val.style.width = "105px";
    val.style.border="2px solid #00FFE6";
}
</script>



<div class="row col-xs-12 col-sm-12  col-md-12  col-lg-12"> 

    <div class=" col-xs-6 col-sm-6  col-md-6  col-lg-6 col-lg-push-3"> 
    
                        <a   onclick="submenu('index/miunidad'), button(this)" class="icon-btn btns">
                                <i class="fa fa-home"></i>
                                <div>
                                    Mi unidad
				</div>
                        </a>
    </div>
    <div class=" col-xs-6 col-sm-6  col-md-6  col-lg-3"> 
       <a  onclick="submenu('index/micondominio'), button(this)" class="icon-btn btns">
						  						<i class="fa fa-building"></i>
												<div>
													 Mi condomiio
												</div>
                        </a>
    </div>

    
</div>

<div id="menu_usuario" style="display:none;"></div>
