<?php 
use Zend\Session\Container; 

?>

<h2 class="page-header"> <?php echo $this->titulo?> </h2>
<section id="menu">
<div class="row">
<a href="<?php echo $this->basePath()?>/usuario/comunicacion">
                <div class="col-lg-4 col-md-6 col-xs-4">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <i class="fa fa-bullhorn"></i>
                                </div>                                
                            </div>
                        </div>
                            <div class="panel-footer text-center">
                                <span>Comunicaci&oacute;n</span>                                
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
</a>
<a href="<?php echo $this->basePath()?>/usuario/sugerencia">
                <div class="col-lg-4 col-md-6 col-xs-4">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <i class="fa fa-archive"></i>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer text-center">
                                <span>Sugerencias</span>                                
                                
                            </div>
                    </div>
                </div>
</a>
<a href="<?php echo $this->basePath()?>/usuario/gcomunes">
                <div class="col-lg-4 col-md-6 col-xs-4">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <i class="fa fa-money"></i>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer text-center">
                                <span>G. Comunes</span>                                
                                
                            </div>
                    </div>
                </div>
</a>
<a href="<?php echo $this->basePath()?>/usuario/gcomunes">
                <div class="col-lg-4 col-md-6 col-xs-4">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <i class="fa fa-dollar"></i>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer text-center">
                                <span>Conserjeria</span>                                
                                
                            </div>
                    </div>
                </div>
</a>
<a href="<?php echo $this->basePath()?>/usuario/conserjeria">
                <div class="col-lg-4 col-md-6 col-xs-4">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-user fa-3x"></i>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Conserjer&iacute;a</span>                                
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
                </a>
<a href="<?php echo $this->basePath()?>/usuario/reclamo">
                <div class="col-lg-4 col-md-6 col-xs-4">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-bar-chart-o fa-3x"></i>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalles</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
                </a>
<a href="<?php echo $this->basePath()?>/usuario/club">
                <div class="col-lg-4 col-md-6 col-xs-4">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-gift fa-3x"></i>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalles</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
                </a>
</div>
</section>