 
<div class=" row col-xs-12 col-sm-12  col-md-12  col-lg-12	" > 
<div class=" row col-xs-6  col-sm-4  col-md-4  col-lg-2 " > 

 	<input type="button" class="btnss" onclick="submenu('miunidad')" 
  	style="background-image:url(<?php echo $this->basePath()?>/img/edifi.png)"/> 
	<center><font SIZE="4" COLOR="#5C9ACF"><b>Mis boletas GC</b></font> </center>
</div>
<div class=" row col-xs-6  col-sm-4  col-md-4  col-lg-2 " > 
  <input type="button" class="btnss" onclick="submenu('miunidad')" 
  style="background-image:url(<?php echo $this->basePath()?>/img/edifi.png)"/>      

<center><font SIZE="4" COLOR="#5C9ACF"><b>Histórico Pagos</b></font> </center>


</div>
 <div class=" row col-xs-6  col-sm-4  col-md-4  col-lg-2 " > 
  <input type="button" class="btnss" onclick="submenu('miunidad')" 
  style="background-image:url(<?php echo $this->basePath()?>/img/edifi.png)"/>      
<center><font SIZE="4" COLOR="#5C9ACF"><b>Mensajes</b></font> </center>


</div>
 <div class=" row col-xs-6  col-sm-4  col-md-4  col-lg-2 " > 
 <input type="button" class="btnss" onclick="submenu('Mis Reservas')" 
  style="background-image:url(<?php echo $this->basePath()?>/img/edifi.png)"/>  
 
<center><font SIZE="4" COLOR="#5C9ACF"><b>Mi perfil</b></font> </center>


</div>
 <div class=" row col-xs-6  col-sm-4  col-md-4  col-lg-2 " > 
 <input type="button" class="btnss" onclick="submenu('mis-encomiendas')" 
  style="background-image:url(<?php echo $this->basePath()?>/img/edifi.png)"/>  
<center><font SIZE="4" COLOR="#5C9ACF"><b>Mis Reservas</b></font> </center>
 </div>

  <div class=" row col-xs-6  col-sm-4  col-md-4  col-lg-2 " > 
 <input type="button" class="btnss" onclick="submenu('mis-encomiendas')" 
  style="background-image:url(<?php echo $this->basePath()?>/img/edifi.png)"/>  
<center><font SIZE="4" COLOR="#5C9ACF"><b>Mis Encomiendas</b></font> </center>
 </div>
 <div class=" row col-xs-12 col-sm-12  col-md-12  col-lg-12	" > 

 
 
 
 </div>
  
  