<h2 class="page-header"><a href="<?php echo $this->basePath()?>/usuario/reclamo"><i class="fa fa-arrow-circle-left fa-1x"></i></a> <?php echo $this->titulo?> </h2>
    <div class="col-lg-8 col-lg-offset-2" >
            <ul class="nav nav-pills">
                    <li class="active">
                        <a href="#fecha-pills" data-toggle="tab">Fecha</a>
                    </li>
                    <li>
                        <a href="#abiertos-pills" data-toggle="tab">Reclamos Abiertos</a>
                    </li>
                    <li>
                        <a href="#cerrados-pills" data-toggle="tab">Reclamos Cerrados</a>
                    </li>
                    <li>
                        <a href="#gastos-pills" data-toggle="tab">Gastos Comunes</a>
                    </li>
                    <li>
                        <a href="#ruidos-pills" data-toggle="tab">Ruidos</a>
                    </li>
                    <li>
                        <a href="#instalaciones-pills" data-toggle="tab">Instalaciones</a>
                    </li>
                    
            </ul>                        
                            <div class="tab-content">
                                <div class="tab-pane fade in active" id="fecha-pills">
                                    <div class="col-lg-12" >                                
                                    <div class="row">
                                    <div>
                                        <h3 style="text-align: center;">Reclamos ordenados por fecha</h3><br />
                                    </div>                       
                                        <div class="table-responsive" style="text-align:center">
                                            <table class="table table-striped table-bordered table-hover" id="data-table-reclamo">
                                                <thead>
                                                    <tr>
                                                      <th>Fecha</th>
                                                      <th>Dpto</th>                                            
                                                      <th>Estado</th>
                                                      <th>Detalle</th>
                                                    </tr>
                                                </thead>
                                                    <tbody>
                                                        <?php for($i=0;$i<count($this->lista);$i++){
                                                         $urlEdit = $this->basePath()."/usuario/reclamo/responder/";
                                                         $urlDelete = $this->basePath()."/usuario/reclamo/eliminar/".$this->lista[$i]['id']."/c"; 
                                                         ?>
                                                       <tr class="odd gradeX">
                                                        <td><?php echo $this->lista[$i]['date_corta']?></td> 
                                                        <td><?php echo $this->lista[$i]['dpto']?></td>                                                                                    
                                                        <td><?php echo $this->lista[$i]['estado']?></td>
                                                        <td>                                           
                                                        <a href="javascript:void(0)" onclick="verDatos('<?php echo $this->lista[$i]['id']?>');" data-toggle="modal" data-target="#myModal"><i class="fa fa-eye fa-fw fa-2x"></i></a>
                                                        </td>
                                                       </tr>
                                                        <?php }; ?>   
                                                               
                                                    </tbody>
                                            </table>
                                        </div>
                    <!-- /.panel -->
                                    </div>
                <!-- /.col-lg-12 -->
                                </div>
                            </div>
                                <div class="tab-pane fade" id="abiertos-pills">
                                <div class="col-lg-12" >                                
                                    <div class="row"> 
                                    <div>
                                        <h3 style="text-align: center;">Reclamos sin finalizaci&oacute;n</h3><br />
                                    </div>                       
                                        <div class="table-responsive" style="text-align:center">
                                            <table class="table table-striped table-bordered table-hover" id="data-table-reclamo">
                                                <thead>
                                                    <tr>
                                                      <th>Fecha</th>
                                                      <th>Dpto</th>                                            
                                                      <th>Asunto</th>
                                                      <th>Detalle</th>
                                                    </tr>
                                                </thead>
                                                    <tbody>
                                                        <?php for($i=0;$i<count($this->lista);$i++){
                                                         $urlEdit = $this->basePath()."/usuario/reclamo/responder/";
                                                         $urlDelete = $this->basePath()."/usuario/reclamo/eliminar/".$this->lista[$i]['id']."/c"; 
                                                         ?>
                                                       <tr class="odd gradeX">
                                                        <td><?php echo $this->lista[$i]['date_corta']?></td> 
                                                        <td><?php echo $this->lista[$i]['dpto']?></td>                                                                                    
                                                        <td><?php echo $this->lista[$i]['asunto']?></td>
                                                        <td>                                           
                                                        <a href="javascript:void(0)" onclick="verDatos('<?php echo $this->lista[$i]['id']?>');" data-toggle="modal" data-target="#myModal"><i class="fa fa-eye fa-fw fa-2x"></i></a>
                                                        </td>
                                                       </tr>
                                                        <?php }; ?>   
                                                               
                                                    </tbody>
                                            </table>
                                        </div>
                    <!-- /.panel -->
                                    </div>
                <!-- /.col-lg-12 -->
                                </div>
                            </div>                                
                                <div class="tab-pane fade" id="cerrados-pills">
                                    <div class="col-lg-12" >                                
                                    <div class="row"> 
                                    <div>
                                        <h3 style="text-align: center;">Reclamos finalizados</h3><br />
                                    </div>                       
                                        <div class="table-responsive" style="text-align:center">
                                            <table class="table table-striped table-bordered table-hover" id="data-table-reclamo">
                                                <thead>
                                                    <tr>
                                                      <th>Fecha</th>
                                                      <th>Dpto</th>                                            
                                                      <th>Asunto</th>
                                                      <th>Detalle</th>
                                                    </tr>
                                                </thead>
                                                    <tbody>
                                                        <?php for($i=0;$i<count($this->lista);$i++){
                                                         $urlEdit = $this->basePath()."/usuario/reclamo/responder/";
                                                         $urlDelete = $this->basePath()."/usuario/reclamo/eliminar/".$this->lista[$i]['id']."/c"; 
                                                         ?>
                                                       <tr class="odd gradeX">
                                                        <td><?php echo $this->lista[$i]['date_corta']?></td> 
                                                        <td><?php echo $this->lista[$i]['dpto']?></td>                                                                                    
                                                        <td><?php echo $this->lista[$i]['asunto']?></td>
                                                        <td>                                           
                                                        <a href="javascript:void(0)" onclick="verDatos('<?php echo $this->lista[$i]['id']?>');" data-toggle="modal" data-target="#myModal"><i class="fa fa-eye fa-fw fa-2x"></i></a>
                                                        </td>
                                                       </tr>
                                                        <?php }; ?>   
                                                               
                                                    </tbody>
                                            </table>
                                        </div>
                    <!-- /.panel -->
                                    </div>
                <!-- /.col-lg-12 -->
                                </div>
                            </div>                                 
                                <div class="tab-pane fade" id="gastos-pills">
                                    <div class="col-lg-12" >                                
                                    <div class="row"> 
                                    <div>
                                        <h3 style="text-align: center;">Reclamos sobre Gastos Comunes</h3><br />
                                    </div>                       
                                        <div class="table-responsive" style="text-align:center">
                                            <table class="table table-striped table-bordered table-hover" id="data-table-reclamo">
                                                <thead>
                                                    <tr>
                                                      <th>Fecha</th>
                                                      <th>Dpto</th>                                            
                                                      <th>Estado</th>
                                                      <th>Detalle</th>
                                                    </tr>
                                                </thead>
                                                    <tbody>
                                                        <?php for($i=0;$i<count($this->lista);$i++){
                                                         $urlEdit = $this->basePath()."/usuario/reclamo/responder/";
                                                         $urlDelete = $this->basePath()."/usuario/reclamo/eliminar/".$this->lista[$i]['id']."/c"; 
                                                         ?>
                                                       <tr class="odd gradeX">
                                                        <td><?php echo $this->lista[$i]['date_corta']?></td> 
                                                        <td><?php echo $this->lista[$i]['dpto']?></td>                                                                                    
                                                        <td><?php echo $this->lista[$i]['estado']?></td>
                                                        <td>                                           
                                                        <a href="javascript:void(0)" onclick="verDatos('<?php echo $this->lista[$i]['id']?>');" data-toggle="modal" data-target="#myModal"><i class="fa fa-eye fa-fw fa-2x"></i></a>
                                                        </td>
                                                       </tr>
                                                        <?php }; ?>   
                                                               
                                                    </tbody>
                                            </table>
                                        </div>
                    <!-- /.panel -->
                                    </div>
                <!-- /.col-lg-12 -->
                                </div>
                                </div>
                                <div class="tab-pane fade" id="ruidos-pills">
                                    <div class="col-lg-12" >                                
                                    <div class="row"> 
                                    <div>
                                        <h3 style="text-align: center;">Reclamos de Ruidos Molestos</h3><br />
                                    </div>                       
                                        <div class="table-responsive" style="text-align:center">
                                            <table class="table table-striped table-bordered table-hover" id="data-table-reclamo">
                                                <thead>
                                                    <tr>
                                                      <th>Fecha</th>
                                                      <th>Dpto</th>                                            
                                                      <th>Estado</th>
                                                      <th>Detalle</th>
                                                    </tr>
                                                </thead>
                                                    <tbody>
                                                        <?php for($i=0;$i<count($this->lista);$i++){
                                                         $urlEdit = $this->basePath()."/usuario/reclamo/responder/";
                                                         $urlDelete = $this->basePath()."/usuario/reclamo/eliminar/".$this->lista[$i]['id']."/c"; 
                                                         ?>
                                                       <tr class="odd gradeX">
                                                        <td><?php echo $this->lista[$i]['date_corta']?></td> 
                                                        <td><?php echo $this->lista[$i]['dpto']?></td>                                                                                    
                                                        <td><?php echo $this->lista[$i]['estado']?></td>
                                                        <td>                                           
                                                        <a href="javascript:void(0)" onclick="verDatos('<?php echo $this->lista[$i]['id']?>');" data-toggle="modal" data-target="#myModal"><i class="fa fa-eye fa-fw fa-2x"></i></a>
                                                        </td>
                                                       </tr>
                                                        <?php }; ?>   
                                                               
                                                    </tbody>
                                            </table>
                                        </div>
                    <!-- /.panel -->
                                    </div>
                <!-- /.col-lg-12 -->
                                </div>
                                </div>
                                <div class="tab-pane fade" id="instalaciones-pills">
                                    <div class="col-lg-12" >                                
                                    <div class="row"> 
                                    <div>
                                        <h3 style="text-align: center;">Reclamos de Instalaciones de su Comunidad</h3><br />
                                    </div>                       
                                        <div class="table-responsive" style="text-align:center">
                                            <table class="table table-striped table-bordered table-hover" id="data-table-reclamo">
                                                <thead>
                                                    <tr>
                                                      <th>Fecha</th>
                                                      <th>Dpto</th>                                            
                                                      <th>Estado</th>
                                                      <th>Detalle</th>
                                                    </tr>
                                                </thead>
                                                    <tbody>
                                                        <?php for($i=0;$i<count($this->lista);$i++){
                                                         $urlEdit = $this->basePath()."/usuario/reclamo/responder/";
                                                         $urlDelete = $this->basePath()."/usuario/reclamo/eliminar/".$this->lista[$i]['id']."/c"; 
                                                         ?>
                                                       <tr class="odd gradeX">
                                                        <td><?php echo $this->lista[$i]['date_corta']?></td> 
                                                        <td><?php echo $this->lista[$i]['dpto']?></td>                                                                                    
                                                        <td><?php echo $this->lista[$i]['estado']?></td>
                                                        <td>                                           
                                                        <a href="javascript:void(0)" onclick="verDatos('<?php echo $this->lista[$i]['id']?>');" data-toggle="modal" data-target="#myModal"><i class="fa fa-eye fa-fw fa-2x"></i></a>
                                                        </td>
                                                       </tr>
                                                        <?php }; ?>   
                                                               
                                                    </tbody>
                                            </table>
                                        </div>
                    <!-- /.panel -->
                                    </div>
                <!-- /.col-lg-12 -->
                                </div>
                                </div>
                </div>

            <div class="modal fade" id="myModal" tabindex="-2" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
               <div class="modal-dialog">
                 <div class="modal-content">
                     <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                          <h4 class="modal-title" id="myModalLabel">Detalle del Reclamo</h4>
                           </div>
                           <div id="mostrarDatos" class="modal-body">Hello</div>
                 </div>
                 <!-- /.modal-content -->
                </div>
               <!-- /.modal-dialog -->
            </div>
</div>
<script>
 $(document).ready(function() {
        $('#data-table-reclamo').dataTable();
    });


function verDatos(reclamoId)
{
    
	
	var parametros = {
		"reclamoId" : reclamoId,
	};
	$.ajax( {
		data : parametros,
        url : '<?php echo $this->basePath()."/admin/reclamo/detalle"?>',
		type : 'post',
		beforeSend : function() {
			
			$("#mostrarDatos").html("<img src='<?php echo $this->basePath()?>/img/loading.gif'/>");
		},
		success : function(response) {
			
			$("#mostrarDatos").html(response);
		}
	});
	
    
}
</script>


            