<h2 class="page-header"><a href="<?php echo $this->basePath()?>/usuario"><i class="fa fa-arrow-circle-left fa-1x"></i></a>   Seleccione su opci&oacute;n </h2>
<br /><br />
<div class="row">
            <a href="<?php echo $this->basePath()?>/usuario/reclamo/nuevo">
               <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-9 text-left">
                                    <div class="huge">Ingresar</div>
                                    <div class="huge">Reclamo</div>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Seleccionar</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                             </a>
                    </div>
                </div>
               
            <a href="<?php echo $this->basePath()?>/usuario/reclamo/consultar">
               <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-9 text-left">
                                    <div class="huge">Ver</div>
                                    <div class="huge">Reclamos</div>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Seleccionar</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
            </a>
                    </div>
                </div>                            
</div>

<div class="row">
<div class="col-lg-9" style="margin-top: 25px;">
                    <div class="panel panel-info">
                        <div class="panel-heading" style="background: #428bca; color: #fff;">
                           <i class="fa fa-bullhorn" style="color: #fff;"></i>&nbsp;&nbsp; Ultimas Reclamos Registrados
                        </div>
                        <div class="panel-body">
                             <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>Dpto</th>
                                            <th>Asunto</th>
                                            <th>Fecha</th>
                                            <th></th>
                                            <th>Estado</th>
                                            <th>Valoraci&oacute;n</th>
                                        </tr>
                                    </thead>
                                    <tbody style="text-align: center;">
                                        <?php echo $this->info ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                       
                    </div>
                </div>

</div>