
<h2 class="page-header"><a href="<?php echo $this->basePath()?>/conserje/sugerencia"><i class="fa fa-arrow-circle-left fa-1x"></i></a> <?php echo $this->titulo?> </h2>



            <!-- /.row -->

			<div class="row">

                <div class="col-lg-12">

                    <div class="panel panel-info">

                        <div class="panel-heading">

                        </div>

                        <!-- /.panel-heading -->

                        <div class="panel-body">

                            <div class="table-responsive">

                                <table class="table table-striped table-bordered table-hover" id="data-table-sugerencia">

                                    <thead>

                                        <tr>

                                            <th>Ticket</th>

                                            <th>Remite</th>

                                            <th>Para</th>

                                            <th>Asunto</th>

                                            <th>Descripcion</th>

                                            <th>Archivo</th>

                                            <th></th>

                                        </tr>

                                    </thead>

                                    <tbody>

                                    <?php for($i=0;$i<count($this->lista);$i++){

                                           $urlEdit = $this->basePath()."/conserje/sugerencia/nuevo/".$this->lista[$i]['id']."/1";

                                           $urlDelete = $this->basePath()."/conserje/sugerencia/eliminar/".$this->lista[$i]['id']."/c";

                                           $fichero =  "/files/db/4/conserje/sugerencia/".$this->lista[$i]['nombre_file'];

                                        ?>

                                        <tr class="odd gradeX">

                                            <td><?php echo $this->lista[$i]['id']?></td>

                                            <td><?php echo $this->lista[$i]['dpto']?></td>

                                            <td><?php echo $this->lista[$i]['receptor']?></td>

                                            <td><?php echo $this->lista[$i]['asunto']?></td>

                                            <td><?php echo $this->lista[$i]['descripcion_corta']." ..."?></td>

                                            <td><a href="<?php echo $fichero?>"><?php echo $this->lista[$i]['descripcion_file']?></a></td> 

                                            <td><a href="<?php echo $urlEdit ?>"><i class="fa fa-edit fa-fw"></i></a> | 

                                            <a href="<?php echo $urlDelete ?>"><i class="fa fa-trash-o fa-fw"></i></a> |

                                            <a href="javascript:void(0)" onclick="verDatos('<?php echo $this->lista[$i]['id']?>');" data-toggle="modal" data-target="#myModal"><i class="fa fa-eye fa-fw"></i></a>

                                            </td>

                                        </tr>

                                     <?php } ?>   

                                       

                        

                                    </tbody>

                                </table>

                            </div>

                        </div>

                        <!-- /.panel-body -->

                    </div>

                    <!-- /.panel -->

                </div>

                <!-- /.col-lg-12 -->

            </div>

            <!-- /.row -->

            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">

               <div class="modal-dialog">

                 <div class="modal-content">

                     <div class="modal-header">

                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

                          <h4 class="modal-title" id="myModalLabel">Detalle de la Sugerencia</h4>

                           </div>

                           <div id="mostrarDatos" class="modal-body"></div>

                 </div>

                 <!-- /.modal-content -->

                </div>

               <!-- /.modal-dialog -->

            </div>



<script>

 $(document).ready(function() {

        $('#data-table-sugerencia').dataTable();

    });





function verDatos(sugerenciaId)

{

    var parametros = {

		"sugerenciaId" : sugerenciaId,

	};

	$.ajax( {

		data : parametros,

        url : '<?php echo $this->basePath()."/conserje/sugerencia/detalle"?>',

		type : 'post',

		beforeSend : function() {

			

			$("#mostrarDatos").html("<img src='<?php echo $this->basePath()?>/img/loading.gif'/>");

		},

		success : function(response) {

			

			$("#mostrarDatos").html(response);

		}

	});

    

}

</script>





            