<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath()?>/metronic/global/plugins/bootstrap-summernote/summernote.css">
<script src="<?php echo $this->basePath()?>/metronic/global/plugins/bootstrap-summernote/summernote.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath()?>/metronic/admin/pages/scripts/components-editors.js"></script>
<script>
jQuery(document).ready(function() {       
   ComponentsEditors.init();
});   
</script>
<?php // var_dump($dptos);?>

<h2 class="page-header"> <a href="<?php echo $this->basePath()?>/conserje"><i class="fa fa-arrow-circle-left fa-1x"></i></a>&nbsp;&nbsp;   Notificar comunidad v&iacute;a e-mail  </h2>
<br /><br />
<div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-red">
                        <div class="panel-body">                        
                        <?php 
                                        $form = $this->form;
                                        $form->prepare();
                                        $form->setAttributes(array(
                                        'action' => $this->basePath()."/conserje/notificacion/enviar",
                                        'method' => 'post',
                                        'id' => 'form_notificacion',   
                                        'name' => 'form_notificacion',                                 
                                        ));
                                        echo $this->form()->openTag($form);                                        
                        ?>  
                            <div class="row">  
                             <div id="alertaV" class="col-md-12"></div>                       
                                <div class="col-md-4">                                   
                                    <div class="form-group">                                      
                                      
                                                    <?php                                             
                                                        echo $this->formRow($this->form->get('destino'));
                                                    ?> 
                                                               
                                                     <?php   echo $this->formRow($this->form->get('dpto'));
                                                    ?>   Departamento 
                                           <br /> <br />                                                                                  
                                                   <?php                                             
                                                        echo $this->formRow($this->form->get('id_unidad'));
                                                    ?>                                           
                                    </div>
                                    <br />
                                    <div class="form-group">
                                         <label>Asunto</label><br/>
                                                    <?php                                             
                                                        echo $this->formRow($this->form->get('asunto'));
                                                    ?>                                         

                                    </div>
                                    <br />                                    
                                    <div class="form-group">
                                    <fieldset>
                                      <legend>Prioridad del mensaje</legend>                                      
                                                    <?php                                             
                                                        echo $this->formRow($this->form->get('prioridad'));
                                                    ?>                                              
                                    </fieldset>   
                                    </div>                                    
                                    <br /><br /><br />
                                    <div class="form-group text-center">                                         
                                        <a type="text" class="btn btn-danger">
                                        <i class="fa fa-reply"></i> &nbsp;Volver atrás
                                        </a>
                                        &nbsp;&nbsp;
                                        <button type="submit" id="sendnot" class="btn btn-success">
                                        <i class="fa fa-paper-plane"></i> &nbsp;Enviar Notificaci&oacute;n
                                        </button>                                         

                                    </div>
                                    
                                </div>                               
                                                                   
                                <div class="form-group col-md-8">                                        
                                      <label>Cuerpo del Correo</label>                                        
											<div name="summernote" id="summernote_1">
											</div>									          
                                </div>                                                                      
                                </div>
                                         <?php                                                                                         
                                            echo $this->form()->closeTag();        
                                        ?>
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                    <!-- /.panel-body -->
                </div>
            <!-- /.panel -->
        </div>
    <!-- /.col-lg-12 -->
</div>
<?php echo $rsptaOK?>        
<script>
function checkDpto(){
$("#chk_comite").attr('checked', false);
$("#chk_admin").attr('checked', false);
$("#chk_comuni").attr('checked', false);
$("#combo_dpto").removeClass('hidden');
$("#combo_dpto").removeAttr('disabled',false);     
}
function checkChk(){
   $("#radio_dpto").attr('checked', false); 
   $("#combo_dpto").addClass('hidden'); 
   $("#combo_dpto").attr('disabled','disabled');
}
$("#form_notificacion").submit(function(e)
{   $('.note-codable').val($('.note-editable').html());
    $('.note-codable').attr('name', 'textbody');
    var postData = $(this).serializeArray();
    var formURL = $(this).attr("action");
    $.ajax(
    {
        url : formURL,
        type: "POST",
        data : postData,
        dataType : 'json',
        beforeSend: function(){
            $("#sendnot").html('<i class="fa fa-spinner"></i> &nbsp;Enviando...');
        },        
        success : function(response) {        
          if(response.status == 'ok'){
            $("#descrok").text("Mensaje enviado correctamente...");
           $("#respuestaOK").modal('show');
           setTimeout(function(){
                        $("#respuestaOK").modal('hide');                        
                        $(location).attr('href','<?php echo $this->basePath()."/conserje"?>'); 
                    },1200);                   
          }else{            
            $("#alertaV").html('<div id="respuesta" class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>'+response.descripcion+'</div>');            
          }
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {
            $("#mostrarCJ").html('<div id="respuesta" class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>Error en el env&iacute;o de datos al servidor</div>')      
        }
    });
    e.preventDefault(); //STOP default action    
});

</script>            