<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath()?>/metronic/global/plugins/bootstrap-summernote/summernote.css">
<script src="<?php echo $this->basePath()?>/metronic/global/plugins/bootstrap-summernote/summernote.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath()?>/metronic/admin/pages/scripts/components-editors.js"></script>
<script>
jQuery(document).ready(function() {       
   ComponentsEditors.init();
});   
</script>


<h2 class="page-header"> <a href="<?php echo $this->basePath()?>/conserje"><i class="fa fa-arrow-circle-left fa-1x"></i></a>&nbsp;&nbsp;   Notificar comunidad v&iacute;a e-mail  </h2>
<br /><br />
<div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-red">
                        <div class="panel-body">
                            <div class="row">   
                             <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                             <div id="alertaV" class="col-lg-8"></div>
                             </div>                         
                                <div class="col-md-3">                                   
                                    <div class="form-group">
                                      <label>Seleccione Destinatario </label><br />
                                      
                                          <input type="checkbox" value="comite" name="destino[]" />  Comit&eacute; &nbsp;&nbsp;&nbsp;
                                          <input type="checkbox" value="admin"  name="destino[]" />  Administrador &nbsp;&nbsp;&nbsp;
                                          <input type="checkbox" value="comunidad" name="destino[]" />  Comunidad
                                             
                                    </div>
                                    <br />
                                    <div class="form-group">
                                         <label>Asunto</label><br/>
                                        <input type="text" class="form-control" />                                         

                                    </div>
                                    <br />
                                    <div class="form-group">
                                      <label>Marcar prioridad </label><br />
                                      
                                          <input type="checkbox" value="comite" name="destino[]" />  Urgente &nbsp;&nbsp;&nbsp;
                                          <input type="checkbox" value="admin"  name="destino[]" />  Normal &nbsp;&nbsp;&nbsp;
                                          
                                             
                                    </div>
                                    <br /><br /><br />
                                    <div class="form-group text-center">                                         
                                        <a type="text" class="btn btn-danger">
                                        <i class="fa fa-reply"></i> &nbsp;Volver atrás
                                        </a>
                                        &nbsp;&nbsp;
                                        <a type="text" class="btn btn-success">
                                        <i class="fa fa-paper-plane"></i> &nbsp;Enviar Notificaci&oacute;n
                                        </a>                                         

                                    </div>
                                    
                                </div>                               
                                                                   
                                <div class="form-group col-md-9">                                        
                                      <label>Cuerpo del Correo</label>                                        
											<div name="summernote" id="summernote_1">
											</div>									          
                                </div>                                                                      
                                </div>
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>