<h2 class="page-header"> <a href="<?php echo $this->basePath()?>/conserje"><i class="fa fa-arrow-circle-left fa-1x"></i></a>&nbsp;&nbsp;   Notificar comunidad v&iacute;a e-mail  </h2>
<br /><br />
<section id="menu_conserje">
<div class="row">
           <a onclick="nuevaNotificacion('comite');" style="cursor: pointer;" data-toggle="modal" data-target="#modalnuevanot">
               <div class="col-lg-3 col-md-6 col-sm-4">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <div>
                                    <i class="fa fa-legal fa-3x" style="color: #fff; "></i>
                                    </div>                                    
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                                <div class="col-xs-12 text-center">
                                        <div class="huge">Informar comit&eacute;</div>                                        
                                    </div>                            
                                <div class="clearfix"></div>
                            </div>
                            
                    </div>
                </div>
            </a> 

           <a onclick="nuevaNotificacion('comunidad');" style="cursor: pointer;" data-toggle="modal" data-target="#modalnuevanot">
               <div class="col-lg-3 col-md-6 col-sm-4">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <div>
                                    <i class="fa fa-users fa-3x" style="color: #fff; "></i>
                                    </div>                                    
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                                <div class="col-xs-12 text-center">
                                        <div class="huge">Informar Comunidad</div>                                        
                                    </div>                            
                                <div class="clearfix"></div>
                            </div>
                            
                    </div>
                </div>
            </a> 
               
            <a onclick="nuevaNotificacion('administrador');" style="cursor: pointer;" data-toggle="modal" data-target="#modalnuevanot">
               <div class="col-lg-3 col-md-6 col-sm-4">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <div>
                                    <i class="fa fa-suitcase fa-3x" style="color: #fff; "></i>
                                    </div>                                    
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                                <div class="col-xs-12 text-center">
                                        <div class="huge">Informar Administrador</div>                                        
                                    </div>                            
                                <div class="clearfix"></div>
                            </div>
                            
                    </div>
                </div>
            </a>  


</div>
</section>
<div class="row">
<div class="col-lg-9" style="margin-top: 25px;">
                    <div class="panel panel-info">
                        <div class="panel-heading" style="background: #428bca; color: #fff;">
                           <i class="fa fa-history" style="color: #fff;"></i>&nbsp;&nbsp; Ultimas notificaciones
                        </div>
                        <div class="panel-body">
                             <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>Dpto</th>
                                            <th>Nombre</th>
                                            <th>Fecha de Notificaci&oacute;n</th>
                                            <th>Tipo</th>                                            
                                            <th>Estado</th>
                                            <th>Ver</th>
                                        </tr>
                                    </thead>
                                    <tbody style="text-align: center;">
                                        <?php echo $this->info ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                       
                    </div>
                </div>

</div>

<!-- MODAL Nueva Tarea -->

<div class="modal fade bs-example-modal-lg" id="modalnuevanot" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel2" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>                    
                    <h4 class="modal-title" id="myModalLabel2" style="text-align: center;">Notificar a la comunidad</h4>
            </div>
                <div id="bodynuevanot" class="modal-body" style="text-align: center;">Cargando...</div>
        </div>                 
    </div>              
</div>

<!-- FIN MODAL Nueva Tarea --> 

<script>
function nuevaNotificacion(flag){
var postData = {'flag' : flag};
	$.ajax( {
        url : '<?php echo $this->basePath()."/conserje/notificacion/nueva"?>',
		type : 'post',
        data : postData,
		beforeSend : function() {
		//	$("#loading").modal('show');
		//	$("#loading").html("<img src='<?php echo $this->basePath()?>/img/loading.gif'/>");
		},
		success : function(response) {
		//	$("#loading").modal('hide');
         //   $("#loading").html("");
			$("#bodynuevanot").html(response);
		}
	});
}
</script>