<h2 class="page-header"><a href="<?php echo $this->basePath()?>/conserje/sugerencia"><i class="fa fa-arrow-circle-left fa-1x"></i></a> <?php echo $this->titulo?> </h2>

            <!-- /.row -->
			<div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                        <?php echo $this->mensaje?>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Remite</th>
                                            <th>Para</th>
                                            <th>Asunto</th>
                                            <th>Descripcion</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php for($i=0;$i<count($this->lista);$i++){?>
                                        <tr class="odd gradeX">
                                            <td><?php echo $this->lista[$i]['id']?></td>
                                            <td><?php echo $this->lista[$i]['dpto']?></td>
                                            <td><?php echo $this->lista[$i]['receptor']?></td>
                                            <td><?php echo $this->lista[$i]['asunto']?></td>
                                            <td><?php echo $this->lista[$i]['descripcion_corta']." ..."?></td>
                                            <?php 
                                            $urlEdit = $this->basePath()."/conserje/sugerencia/nuevo/".$this->lista[$i]['id']."/1";
                                            $urlDelete = $this->basePath()."/conserje/sugerencia/eliminar/".$this->lista[$i]['id']."/1"; 
                                            ?> 
                                            <td><a href="<?php echo $urlEdit ?>"><i class="fa fa-edit fa-fw"></i></a> | <a href="<?php echo $urlDelete ?>"><i class="fa fa-trash-o fa-fw"></i></a></td>
                                        </tr>
                                     <?php } ?>   
                                       
                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            