<div class="row">

<div class="col-lg-4">
    <div class="col-lg-12 text-center">
    <i id="fa_icon" class="fa fa-home" style="margin-top: 80px; font-size: 100px;"></i>
    </div>
</div>
  
<div class="col-lg-8">  
    <div class="col-lg-4">
    <div class="form-group">
        <label>N&uacute;mero</label>
            <div class="form-group input-group">
                <span class="input-group-addon"><i class="fa fa-info"></i>
                </span>     
                <input id="nombre_unidad" class="form-control" value="<?php echo $this->datos[0]['nombre']?>" disabled/>           
            </div>
    </div>
    </div>
    
    <div class="col-lg-4">
    <div class="form-group">
        <label>Piso</label>
            <div class="form-group input-group">
                <span class="input-group-addon"><i class="fa fa-building"></i>
                </span>     
                <input class="form-control" value="<?php echo $this->datos[0]['piso']?>" disabled/>           
            </div>
    </div>
    </div>
    
    <div class="col-lg-4">
    <div class="form-group">
        <label>Mts<sup>2</sup></label>
            <div class="form-group input-group">
                <span class="input-group-addon"><i class="fa fa-info"></i>
                </span>     
                <input class="form-control" value="<?php echo $this->datos[0]['mts']?>" disabled/>           
            </div>
    </div>
    </div>
    
    <div class="col-lg-4">
    <div class="form-group">
        <label>Alicuota</label>
            <div class="form-group input-group">
                <span class="input-group-addon"><i>%</i>
                </span>     
                <input class="form-control" value="<?php echo $this->datos[0]['alicuota']?>" disabled/>           
            </div>
    </div>
    </div>
    
    <div class="col-lg-4">
    <div class="form-group">
        <label>Habitaciones</label>
            <div class="form-group input-group">
                <span class="input-group-addon"><i class="fa fa-home"></i>
                </span>     
                <input class="form-control" value="<?php echo $this->datos[0]['habitaciones']?>" disabled/>           
            </div>
    </div>
    </div>
    
    <div class="col-lg-4">
    <div class="form-group">
        <label>Ba&ntilde;os</label>
            <div class="form-group input-group">
                <span class="input-group-addon"><i class="fa fa-home"></i>
                </span>     
                <input class="form-control" value="<?php echo $this->datos[0]['banos']?>" disabled/>           
            </div>
    </div>
    </div>
    
    <div class="col-lg-4">
    <div class="form-group">
        <label>Estado</label>
            <div class="form-group input-group">
                <span class="input-group-addon"><i class="fa fa-home"></i>
                </span>     
                <input class="form-control" value="<?php echo $this->datos[0]['estado']?>" disabled/>           
            </div>
    </div>
    </div>
    
    
    
</div>
<script>
function (){
    if $("#nombre_unidad")
 $("#fa_icon")   
    
}
</script>