                            <?php 
                                        $form = $this->form;
                                        $form->prepare();
                                        $form->setAttributes(array(
                                        'action' => $this->basePath()."/admin/infocom/guardarseguro",
                                        'id' => 'form1'                                    
                                        ));
                                        echo $this->form()->openTag($form);
                                        echo $this->formRow($this->form->get('origen'));
                                        echo $this->formRow($this->form->get('id_tipo_egreso'));
                                        echo $this->formRow($this->form->get('concepto'));
                                        echo $this->formRow($this->form->get('id_pk'));
                                        echo $this->formRow($this->form->get('url_poliza'));
                            ?>   
                        <div class="col-lg-9 col-md-9 col-xs-9">
                                <div class="col-lg-4 col-md-4 col-xs-6">                                                
                                    <label>Aseguradora &nbsp;&nbsp; <a onclick="nuevoProveedor()" data-toggle="modal" data-target="#modal_proveedor"><i class="fa fa-plus"></i> Nueva...</a></label>
                                    <div class="form-group input-group">                                            
                                            <span class="input-group-addon"><i class="fa fa-bank"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form->get('id_proveedor'));
                                            ?>                                             
                                    </div>                                                 
                                </div>  
                                 <div class="col-lg-4 col-md-4 col-xs-6">                                                
                                    <label>N&deg; Poliza</label>
                                    <div class="form-group input-group">                                            
                                            <span class="input-group-addon"><i class="fa fa-info"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form->get('poliza'));
                                            ?>                                             
                                    </div>                                                 
                                </div>  
                                <div class="col-lg-4 col-md-4 col-xs-6">                                                
                                    <label>Riesgo</label>
                                    <div class="form-group input-group">                                            
                                            <span class="input-group-addon"><i class="fa fa-info"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form->get('riesgo'));
                                            ?>                                             
                                    </div>                                                 
                                </div>  
                                <div class="col-lg-4 col-md-4 col-xs-6">                                                
                                    <label>Valor Prima MENSUAL</label>                                    
                                    <div class="form-group input-group">                                            
                                            <span class="input-group-addon"><i class="fa fa-dollar"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form->get('valor_prima'));
                                            ?>                                             
                                    </div>                                                 
                                </div>
                                <div class="col-lg-4 col-md-4 col-xs-6">                                                
                                    <label>N&deg; Cuotas</label>
                                    <div class="form-group input-group">                                            
                                            <span class="input-group-addon"><i class="fa fa-calendar"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form->get('cuotas'));
                                            ?>                                             
                                    </div>                                                 
                                </div> 
                                <div class="col-lg-4 col-md-4 col-xs-6">                                                
                                    <label>Inicio Cobertura</label>
                                    <div class="form-group input-group">                                            
                                            <span class="input-group-addon"><i class="fa fa-calendar"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form->get('vigencia'));
                                            ?>                                             
                                    </div>                                                 
                                </div>
                                 <div class="col-lg-4 col-md-4 col-xs-6">                                                
                                    <label>Fin Cobertura</label>
                                    <div class="form-group input-group">                                            
                                            <span class="input-group-addon"><i class="fa fa-calendar"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form->get('vigenciafin'));
                                            ?>                                             
                                    </div>                                                 
                                </div>
                                                                                                                                                                                                                   
                        </div> 
                             
                        <div class="col-lg-3 col-md-3 col-xs-3"> 
                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                        <div class="col-lg-4  udt">
                            <br />
                            <a>
                                <a class="btn btn-success"><i id="icnAdjuntarPoliza" class="fa fa-file"></i> Adjuntar Poliza</a>      
                            <?php 
                                echo $this->formRow($this->form->get('filepoliza'));
                            ?>                                                                                                                                                                                                                                                                              
                            </a> 
                        </div>
                              
                          <div class="col-md-12">
                            <span id="mostrarnombre"></span>
                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                        </div>
                        <div class="col-lg-12 col-md-12 col-xs-12">
                                        <div class="form-group">
                                        <label>Detalles</label>
                                        <div class="form-group">                                            
                                            <?php                                             
                                              echo $this->formRow($this->form->get('detalle'));
                                            ?>                                            
                                        </div>
                                        </div>
                                </div>  
                        <div class="col-lg-12 col-md-12 col-xs-12" style="text-align: center;">   
                                                                                  
                                                <?php                                             
                                              echo $this->formRow($this->form->get('sendseg'));
                                            ?> 
                                                                                      
                               </div>
                              <?php echo $this->form()->closeTag()?>
<div class="modal fade bs-example-modal-lg" id="modal_proveedor" tabindex="-2" data-backdrop="static" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
               <div class="modal-dialog modal-lg">
                 <div class="modal-content">
                     <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                          <h4 class="modal-title" id="myModalLabel">Nueva Aseguradora</h4>
                           </div>
                           <div id="mostrarDatos" class="modal-body">Cargando...</div>
                 </div>
                 <!-- /.modal-content -->
                </div>
               <!-- /.modal-dialog -->
</div>                                        
<script>
$("#sendseg").click(function()
{ 
    if( $("#id_proveedor").val()== 0){
        toastr.info("Debes seleccionar una entidad aseguradora")
    }else{
    $("#id_proveedor").removeAttr("disabled");
    var postData = $("#form1").serializeArray();
    var formURL = $("#form1").attr("action");
    $.ajax(
    {
        url : formURL,
        type: "POST",
        data : postData,
        dataType : 'json',
        success : function(response) {                    
          toastr.success(response.descripcion);          
          $('.panel-collapse.in').collapse('toggle');           
          $("#btnnuevoseguro").css("display","block");
          $("#divnuevoseguro").html("");
          $('html, body').animate({ scrollTop: 0 }, 'slow');          
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {
            toastr.error("Ups, ha ocurrido un error inesperado, favor contacta con soporte");
        }
    });
    }   
});
</script>                              