<div class="row">
				<div class="col-md-12 ">
					<!-- BEGIN SAMPLE FORM PORTLET-->
					<div class="portlet box green">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-cogs"></i> Datos Generales y Edificaci&oacute;n
							</div>
						</div>
						<div class="portlet-body form">
                        <?php 
                                        $form = $this->form;
                                        $form->prepare();
                                        $form->setAttributes(array(
                                        'action' => $this->url."/admin/infocom/guardarcomunidad",
                                        'method' => 'post'                                    
                                        ));
                                        echo $this->form()->openTag($form);
                                        echo $this->formRow($this->form->get('id_pk'));
                                        echo $this->formRow($this->form->get('tipo'));
                                        ?>                         
                        <div class="form-body">

                            <div class="row">
                               <div class="col-lg-12 col-md-12" style="text-align: center;">
                                    <img src="<?php echo $this->basePath()?>/img/camera.png" style="max-width: 5%;" >                    
                                    <a href="#">    <p style="padding: 10px;">Logotipo Comunidad</p></a>
                               </div>                                                                                      
                            </div>
                            
                            <div class="row">

                    <div class="col-lg-6 col-md-6 col-sm-6">
                            
                             <div class="col-lg-12 col-md-12 col-sm-12">                                                                
                                        <div class="form-group form-md-line-input has-success">
										<div class="input-icon">
											<?php                                             
                                              echo $this->formRow($this->form->get('nombre'));
                                            ?>
											<label for="form_control_1">Nombre</label>
											<span class="help-block">Nombre del condominio</span>
											<i class="fa fa-building"></i>
										</div>
									</div>
                            </div> 
                            <div class="col-lg-12 col-md-12 col-sm-12">                                                                
                                        <div class="form-group form-md-line-input has-success">
										<div class="input-icon">
											<?php                                             
                                              echo $this->formRow($this->form->get('rut'));
                                            ?>
											<label for="form_control_1">RUT</label>
											<span class="help-block">Sin puntos ni gui&oacute;n</span>
											<i class="fa fa-user"></i>
										</div>
									</div>
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12">                                                                
                                        <div class="form-group form-md-line-input has-success">
										<div class="input-icon">
											<?php                                             
                                              echo $this->formRow($this->form->get('direccion'));
                                            ?>
											<label for="form_control_1">Direcci&oacute;n</label>
                                            <span class="help-block">Calle y n&uacute;mero</span>											
											<i class="fa fa-map-marker"></i>
										</div>
									</div>
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12">                                                                
                                        <div class="form-group form-md-line-input has-success">
										<div class="input-icon">
											<?php                                             
                                              echo $this->formRow($this->form->get('ciudad'));
                                            ?>
											<label for="form_control_1">Ciudad</label>											
											<i class="fa fa-map-marker"></i>
										</div>
									</div>
                            </div>    
                            <div class="col-lg-12 col-md-12 col-sm-12">                                                                
                                        <div class="form-group form-md-line-input has-success">
										<div class="input-icon">
											<?php                                             
                                              echo $this->formRow($this->form->get('pais'));
                                            ?>
											<label for="form_control_1">Pa&iacute;s</label>											
											<i class="fa fa-globe"></i>
										</div>
									</div>
                            </div>                                                                                                                                                                                                                                                                                                           
                           </div>                                 
                      <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <div class="col-lg-12 col-md-12 col-sm-12">                                                                
                                        <div class="form-group form-md-line-input has-success">
										<div class="input-icon">
											<?php                                             
                                              echo $this->formRow($this->form->get('telefono'));
                                            ?>
											<label for="form_control_1">Tel&eacute;fono Administrador</label>
                                            <span class="help-block">Ingrese su n&uacute;mero de contacto</span>											
											<i class="fa fa-phone"></i>
										</div>
									</div>
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12">                                                                
                                        <div class="form-group form-md-line-input has-success">
										<div class="input-icon">
											<?php                                             
                                              echo $this->formRow($this->form->get('telefono2'));
                                            ?>
											<label for="form_control_1">Tel&eacute;fono Conserjer&iacute;a</label>
                                            <span class="help-block">En blanco si no existe</span>											
											<i class="fa fa-phone"></i>
										</div>
									</div>
                            </div>       
                            <div class="col-lg-12 col-md-12 col-sm-12">                                                                
                                        <div class="form-group form-md-line-input has-success">
										<div class="input-icon">
											<?php                                             
                                              echo $this->formRow($this->form->get('web'));
                                            ?>
											<label for="form_control_1">P&aacute;gina WEB</label>
                                            <span class="help-block">En blanco si no existe</span>											
											<i class="fa fa-globe"></i>
										</div>
									</div>
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12">                                                                
                                        <div class="form-group form-md-line-input has-success">
										<div class="input-icon">
											<?php                                             
                                              echo $this->formRow($this->form->get('emailcom'));
                                            ?>
											<label for="form_control_1">E-mail Comunidad</label>
                                            <span class="help-block">Correo de contacto</span>											
											<i class="fa fa-at"></i>
										</div>
									</div>
                            </div>                                                                                                                                            
                            <div class="col-lg-12 col-md-12 col-sm-12">                                                                
                                        <div class="form-group form-md-line-input has-success">
										<div class="input-icon">
											<?php                                             
                                              echo $this->formRow($this->form->get('emailgc'));
                                            ?>
											<label for="form_control_1">E-mail Gastos Comunes</label>                                            											
											<i class="fa fa-at"></i>
										</div>
									</div>
                            </div>                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                        </div> 
                         <div class="row" style="text-align: center;">   
                                        <div class="col-lg-12" style="margin-top: 15px;">  
                                            <?php                                             
                                              echo $this->formRow($this->form->get('send'));
                                            ?>                                                                                                                                                                                  
                                        </div>                                              
                         </div> 
                        <?php echo $this->form()->closeTag()?>
                        
                        <div class="col-md-12" style="margin-left: 15px;">         
                                <h4 class="page-header"> 
                                    <i class="fa fa-building"></i>  
                                    &nbsp; &nbsp;Edificaci&oacute;n                                  
                                </h4>
                        </div>
                      
                                          <?php 
                                        $form2 = $this->form;
                                        $form2->prepare();
                                        $form2->setAttributes(array(
                                        'action' => $this->url."/admin/infocom/guardaredif",
                                        'method' => '',
                                        'name' => 'form2'                                    
                                        ));
                                        echo $this->form()->openTag($form2);                                            
                                        echo $this->formRow($this->form2->get('id_pk'));
                                            ?>
                                        
                                              <div class="col-lg-12">
                                        <div class="row">
                                        <div class="col-lg-3 col-md-3 col-xs-6">
                                          <div class="form-group">
                                         
                                            <label>Pisos</label>
                                            <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-building"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form2->get('piso'));
                                            ?>                                            
                                            </div>                                          
                                        </div>        
                                          </div>
                                          <div class="col-lg-3 col-md-3 col-xs-6">
                                        <div class="form-group">
                                        <label>Departamentos</label>
                                        <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-info"></i>
                                            </span>                                            
                                             <?php                                             
                                              echo $this->formRow($this->form2->get('departamento'));
                                            ?> 
                                            </div>                                           
                                        </div>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-xs-6">
                                        <div class="form-group">
                                            <label>Torres</label>
                                            <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-building"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form2->get('torre'));
                                            ?> 
                                            </div>                                           
                                        </div>
                                          </div>
                                          <div class="col-lg-3 col-md-3 col-xs-6">                                                                                                    
                                        <div class="form-group">
                                            <label>Subterraneos</label>
                                            <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-info"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form2->get('subterraneo'));
                                            ?> 
                                            </div>                                           
                                        </div>
                                        </div> 
                                    </div> 
                                    <div class="row">                                    
                                        <div class="col-lg-3 col-md-3 col-xs-6">                                                                                                                                                                                                                                                                                                         
                                        <div class="form-group">
                                            <label>Estac. Visitas</label>
                                             <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-car"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form2->get('est_visita'));
                                            ?>  
                                            </div>                                          
                                        </div>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-xs-6"> 
                                        <div class="form-group">
                                            <label>Ascensores</label>
                                            <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-building"></i>
                                            </span>                                            
                                            <?php                                             
                                              echo $this->formRow($this->form2->get('ascensor'));
                                            ?> 
                                            </div>                                            
                                        </div>  
                                        </div> 
                                        <div class="col-lg-3 col-md-3 col-xs-6"> 
                                        <div class="form-group">
                                            <label>Quinchos</label>
                                            <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-glass"></i>
                                            </span>                                            
                                            <?php                                             
                                              echo $this->formRow($this->form2->get('quincho'));
                                            ?> 
                                            </div>                                            
                                        </div>  
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-xs-6"> 
                                        <div class="form-group">
                                            <label>Salones</label>
                                            <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-building"></i>
                                            </span>                                            
                                            <?php                                             
                                              echo $this->formRow($this->form2->get('salon'));
                                            ?> 
                                            </div>                                            
                                        </div>  
                                        </div>                                                                                                                                                                     
                                        </div>    
                            <div class="row">                                    
                                        <div class="col-lg-3 col-md-3 col-xs-6">                                                                                                                                                                                                                                                                                                         
                                        <div class="form-group">
                                            <label>Piscinas</label>
                                             <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-sun-o"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form2->get('piscina'));
                                            ?>  
                                            </div>                                          
                                        </div>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-xs-6"> 
                                        <div class="form-group">
                                            <label>Gimnasios</label>
                                            <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-building"></i>
                                            </span>                                            
                                            <?php                                             
                                              echo $this->formRow($this->form2->get('gimnasio'));
                                            ?> 
                                            </div>                                            
                                        </div>  
                                        </div> 
                                        <div class="col-lg-3 col-md-3 col-xs-6"> 
                                        <div class="form-group">
                                            <label>Accesos</label>
                                            <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-lock"></i>
                                            </span>                                            
                                            <?php                                             
                                              echo $this->formRow($this->form2->get('acceso'));
                                            ?> 
                                            </div>                                            
                                        </div> 
                                        </div>  
                                        <div class="col-lg-3 col-md-3 col-xs-6"> 
                                        <div class="form-group">
                                            <label>Lavanderias</label>
                                            <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-lock"></i>
                                            </span>                                            
                                            <?php                                             
                                              echo $this->formRow($this->form2->get('lavanderia'));
                                            ?> 
                                            </div>                                            
                                        </div> 
                                        </div>                                        
                                        <div class="row" style="text-align: center;">   
                                        <div class="col-lg-12">                                          
                                                <?php                                             
                                              echo $this->formRow($this->form2->get('send2'));
                                            ?>
                                        </div>                                              
                               </div>
                               <?php echo $this->form()->closeTag()?>
                                        </div>                                                                                                                                                                   
                                        </div>
                                  
                        </div>
                        
                        
                            
                            
                                                               
                                                              
                </div>
         </div>
    </div>
</div>                                                         
                     
                        

<script>
toastr.options = {
  "positionClass": "toast-top-center",
}
/*
$(function () {
  $('[data-toggle="popover"]').popover()
})
$("input#rutgral").rut({validateOn: 'change'}).on('rutInvalido', function(){ 
   $('#sendgral').attr("disabled","disabled"); 
   $("input#rutgral").attr('data-content','Rut Incorrecto').css("background","#FD8C92").popover('show');    
});
$("input#rutgral").rut({validateOn: 'blur'}).on('rutValido', function(){
    $('#sendgral').removeAttr("disabled");
   $("input#rutgral").popover('destroy').css("background","#fff");   
}); */
$("#form").submit(function(e)
{
    var postData = $(this).serializeArray();
    var formURL = $(this).attr("action");
    $.ajax(
    {
        url : formURL,
        type: "POST",
        data : postData,
        dataType : 'json',
        success : function(response) {
            toastr.success(response.descripcion)
        },                               
        error: function(jqXHR, textStatus, errorThrown) 
        {
            toastr.danger("Error! Favor contactar a nuestro equipo de soporte")
        }
    });
    e.preventDefault(); //STOP default action    
});
$("#form2").submit(function(e)
{
    var postData = $(this).serializeArray();
    var formURL = $(this).attr("action");
    $.ajax(
    {
        url : formURL,
        type: "POST",
        data : postData,
        dataType : 'json',
        success : function(response) {
            toastr.success(response.descripcion)
            $("html, body").animate({ scrollTop: 0 }, "slow");
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {
            toastr.danger("Error! Favor contactar a nuestro equipo de soporte")      
        }
    });
    e.preventDefault();     
});      
</script>  