<link rel="stylesheet" type="text/css" href="../../metronic/global/plugins/select2/select2.css"/>
<link rel="stylesheet" type="text/css" href="../../metronic/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css"/>
<script type="text/javascript" src="../../metronic/global/plugins/select2/select2.min.js"></script>
<script type="text/javascript" src="../../metronic/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="../../metronic/global/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js"></script>
<script type="text/javascript" src="../../metronic/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>


<div class="row">       
                    <div class="col-lg-12">
                        <div class="panel panel-primary">
                        <div class="panel-heading">
                            <i class="fa fa-send" style="color: #fff;"></i> &nbsp;&nbsp;Residentes del condominio
                        </div>                            
                        <div class="panel-body text-center">   
     <!--1 2 3-->                                  
            <div class="row udt">
            <!--Titulo-->
                  <div class="col-lg-12" style="margin-bottom: 20px;" >
                  <h3>En 3 simples pasos cargue a los residentes de su condominio</h3>
                  </div>
            <!--Fin Titulo-->                
            <!--1-->
                 <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                    <br /><br />
                        <div class="col-lg-12">                        
                            <i class="fa fa-file-excel-o" style="color: #585DA0; font-size: 42px;"></i><br /><br />
                        </div>
                    
                        <div class="col-lg-12">
                            <a href="#" id="descargarArchivoResidentes" class="btn btn-success"><i class="fa fa-download"></i> &nbsp;&nbsp;Descargar planilla excel</a>
                        </div>                    
                  </div>
             <!--Fin 1-->                  
             <!--Flecha 1-->     
                  <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1" style="display: table; height:122px;">                 
                    <i class="fa fa-arrow-circle-o-right" style="display: table-cell; vertical-align: middle; font-size: 28px;"></i>                    
                  </div>
             <!--Fin Flecha 1--> 
             <!--2-->      
                  <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                    <br /><br />
                        <div class="col-lg-12">                        
                            <i class="fa fa-users" style="color: #585DA0; font-size: 42px;"></i><br /><br />
                        </div>
                        
                        <div class="col-lg-12">                            
                                <a>
                                 <input required="true" id="fileSelecPlantilla" type="file"/>
                            <button id="btnSelecPlantilla" class="btn btn-success">
                                <i id="icnSelecPlantilla" class="fa fa-upload"></i> <span id="txtSelecPlantilla"> Seleccionar planilla excel </span>
                            </button>
                                </a>                            
                        </div>                    
                  </div>    
             <!--Fin 2-->                  
             <!--Flecha 2-->                                 
                  <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1" style="display: table; height:122px;">                 
                    <i class="fa fa-arrow-circle-o-right" style="display: table-cell; vertical-align: middle; font-size: 28px;"></i>                    
                  </div>
             <!--Fin Flecha 2--> 
             <!--3-->    
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                    <br /><br />
                        <div class="col-lg-12">                        
                            <i class="fa fa-cogs" style="color: #585DA0; font-size: 42px;"></i><br /><br />
                        </div>
                    
                        <div class="col-lg-12">
                            <a href="#" id="importarResidentes" class="btn btn-success"><i id="icnImportarResidentes" class="fa fa-spinner"></i><span id="txtImportarResidentes"> Importar Copropietarios</span></a>
                        </div>                    
                  </div>           
             <!--Fin 3-->                                                
            </div>
     <!--FIN 1 2 3-->                 
                    <br /><br /><br />
                      
        <!-- INICIO -->
        
<div class="row">
				<div class="col-md-12">
					<!-- BEGIN EXAMPLE TABLE PORTLET-->
					<div class="portlet box blue-hoki">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-globe"></i>Listado de Residentes
							</div>
						</div>
						<div class="portlet-body">
                                                    <table class='table table-striped table-bordered table-hover' id='sample_1'>
                                                        <thead><tr><th>Dpto</th><th>Bodega</th><th>Estaci</th><th>Nombres</th><th>Rut</th><th>Telefono</th><th>Correo</th><th>Cond</th></tr></thead>
                                                        <tbody><?php echo $this->tabla?></tbody>
                                                    </table>
						</div>
					</div>
        <!-- FIN -->
        
            </div>           
        </div>           
     </div>            
</div>           

<script>

$("#importarResidentes").addClass('disabled');

$("#importarResidentes").click(function(){

        bootbox.confirm("<strong>Estas seguro que deseas cargar los residentes hacia la base de datos...?</strong>", function(result) {
                   
                   if(result){
                       
                       var file_data = $('#fileSelecPlantilla').prop('files')[0];
                       var parametros = new FormData();                  
                           parametros.append('fileData', file_data);
                           $.ajax( {
                                    contentType:false,
                                    processData:false,	
                                    cache:false,
                                    data : parametros,
                                    url : '<?php echo $this->basePath()."/admin/infocom/cargarresidentes"?>',
                                    type : 'post',
                                    beforeSend : function() {
                                        cec(0);
                                    },
                                    success : function(r) {
                                        if(r.status=='ok'){
                                            //$(location).attr('href',r.url);
                                            messageRspta('success',r.mensaje,'Aviso');
                                             /*setTimeout(function(){
                                                $(location).attr('href','<?php echo $this->basePath()."/admin/infocom/residentes"?>'); 
                                                },7500); */
                                            
                                        }else{
                                             messageRspta('error',r.mensaje,'Aviso');
                                        }
                                        cec(1);
                                    },
                                    error:function(e){
                                        messageRspta('error','Error Tecnico','Aplicacion');
                                        cec(1);
                                    }        
                            });
                   }else{
                       messageRspta('warning','has cancelado la importacion','Aviso');
                   }
     });
});

$("#fileSelecPlantilla").change(function(){
    
          var txtNombreFile = $(this).val().replace("C:\\fakepath\\", "  ");
          $("#txtSelecPlantilla").text(txtNombreFile);
          if(this.files[0].size<2000000 && txtNombreFile.indexOf('Copropietarios.xlsx')>0){
              $("#btnSelecPlantilla").attr("class","btn btn-primary");
              $("#icnSelecPlantilla").attr("class","fa fa-check");
              $("#importarResidentes").removeClass('disabled');
          }else{
              if(txtNombreFile.indexOf('Copropietarios.xlsx')>0){
                messageRspta('error','Error: Mayor a 2Mb','Error'); 
              }else{
                  messageRspta('error','Error: Archivo incompatible','Error'); 
              }
              $("#btnSelecPlantilla").attr("class","btn btn-danger");
              $("#icnSelecPlantilla").attr("class","fa fa-times");
              $("#importarResidentes").addClass('disabled');
              
          }
         
              
     });

$("#descargarArchivoResidentes").click(function(){
    
     var parametros = {"id" : "0"};
    	$.ajax( {  
		data : parametros,
                url : '<?php echo $this->basePath()."/admin/infocom/vfresidentes"?>',
		type : 'post',
		beforeSend : function() {
		},
		success : function(r) {
                    if(r.status=='ok'){
                       //descargar archivo
                       $(location).attr('href',r.url);
                    }else{
                       messageRspta('error',r.mensaje,'Error');
                    }
		},
                error:function(e){
                    messageRspta('error','Error Tecnico en el envio','Aplicacion');
               }
        });
    
});

 function messageRspta(tipo,msg,titulo)
     {
       toastr.options.closeButton=true;
       toastr.options.positionClass='toast-top-center';
       toastr.options.onclick=null;
       toastr.options.showDuration = 1000;
       toastr.options.hideDuration = 1000;
       toastr.options.timeOut = 7000;
       toastr.options.extendedTimeOut = 1000;
       toastr.options.showEasing = 'swing';
       toastr.options.hideEasing = 'linear';
       toastr.options.showMethod = 'fadeIn';
       toastr.options.hideMethod = 'fadeOut';
       toastr[tipo](msg, titulo);
    }
    
function selecciona(nombre){
    if(document.getElementById('file'+nombre).files[0].size<2000000){
  	 document.getElementById("mostrarnombre"+nombre).innerHTML="Archivo seleccionado: [<strong>"+document.getElementById('file'+nombre).files[0].name+"</strong>] OK";
    }else{
     document.getElementById("mostrarnombre"+nombre).innerHTML="<font color='red'>Error Ha superado el limite permitido (2Mb): [<strong>"+document.getElementById('fileupload').files[0].name+"</strong>] NOK</font>";
    }
    
    
  }
/*function importame(n,from){    
if (n==1){    
var data = new FormData();
    jQuery.each(jQuery('#file'+from)[0].files, function(i, file) {
    data.append('file-'+i, file);
    });    
    data.append('flag', from);
	$.ajax( {
	    url : '<?php //echo $this->basePath()."/admin/infocom/excelpropietario"?>',
		data : data,
        cache: false,
        contentType: false,
        processData: false,
        type: 'POST',   
		success : function(response) {					                     
          if(response.status = 'ok'){
            $("#text").text(response.descripcion);
            $("#iconmodal").attr('class',"fa fa-check fa-3x");             
            $("#aceptaimportar").css('display',"none");
            $("#cancelarmodal").css('display',"none");                                       
            setTimeout(function(){             
             $('#importarconfirm').modal('hide');             
            }, 3000); 	 
          }else
          {
            $("#text").text(response.descripcion);
            $("#iconmodal").attr('class',"fa fa-close fa-3x"); 
          }
		}
	}); 
}else{
$('#importarconfirm').modal('show');    
$('#aceptaimportar').click(function(){importame(1,from);});      
} 
}*/


/*function verResidentes(){
    //se deja esa opcion si vamos a filtrar
        var parametros = {"id_residente" : ""};
    	$.ajax( {  
		data : parametros,
                url : '<?php //echo $this->basePath()."/admin/infocom/verlistadoresidentes"?>',
		type : 'post',
		beforeSend : function() {
		  $("#tablaResidentes").html("<i class='fa fa-spinner fa-spin'></i> Cargando...");
		},
		success : function(r) {
                    if(r.status=='ok'){
                        $("#tablaResidentes").html(r.tabla);
                    }else{
                        messageRspta('error',r.mensaje,'Aviso');
                        $("#tablaResidentes").html("Error inesperado");
                    }
		},
                error:function(e){
                    messageRspta('error','Error Tecnico en la consulta','Aplicacion');
               }
        });
}*/

function cec(id){
        if(id==0){
            $("#txtImportarResidentes").text("  Espere un momento...");
            $("#icnImportarResidentes").attr("class","fa fa-spinner fa-spin");
            $("#importarResidentes").addClass('disabled');
            
        }else{
            $("#txtImportarResidentes").text("  Importar Copropietarios");
            $("#icnImportarResidentes").attr("class","fa fa-spinner");
            $("#importarResidentes").removeClass('disabled');
        }
    }


</script>
<script>
var table = $('#sample_1');

        /* Table tools samples: https://www.datatables.net/release-datatables/extras/TableTools/ */

        /* Set tabletools buttons and button container */

        $.extend(true, $.fn.DataTable.TableTools.classes, {
            "container": "btn-group tabletools-dropdown-on-portlet",
            "buttons": {
                "normal": "btn btn-sm default",
                "disabled": "btn btn-sm default disabled"
            },
            "collection": {
                "container": "DTTT_dropdown dropdown-menu tabletools-dropdown-menu"
            }
        });

        var oTable = table.dataTable({

            // Internationalisation. For more info refer to http://datatables.net/manual/i18n
            "language": {
                "aria": {
                    "sortAscending": ": activate to sort column ascending",
                    "sortDescending": ": activate to sort column descending"
                },
                "emptyTable": "No hay datos",
                "info": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                "infoEmpty": "No encontrado",
                "infoFiltered": "(filtered1 desde _MAX_ total registros)",
                "lengthMenu": "Ver _MENU_ entradas",
                "search": "Buscar:",
                "zeroRecords": "No se encontraron registros"
            },

            // Or you can use remote translation file
            //"language": {
            //   url: '//cdn.datatables.net/plug-ins/3cfcc339e89/i18n/Portuguese.json'
            //},

            "order": [
                [0, 'asc']
            ],
            
            "lengthMenu": [
                [5, 10, 15, 20, -1],
                [5, 10, 15, 20, "All"] // change per page values here
            ],
            // set the initial value
            "pageLength": 10,

            "dom": "<'row' <'col-md-12'T>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>", // horizobtal scrollable datatable

            // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
            // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js). 
            // So when dropdowns used the scrollable div should be removed. 
            //"dom": "<'row' <'col-md-12'T>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>",

            "tableTools": {
                "sSwfPath": "../../metronic/global/plugins/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf",
                "aButtons": [{
                    "sExtends": "pdf",
                    "sButtonText": "<i class='fa fa-file-pdf-o'></i>"
                },{
                    "sExtends": "xls",
                    "sButtonText": "<i class='fa fa-file-excel-o'></i>"
                },{
                    "sExtends": "csv",
                    "sButtonText": "CSV"
                }]
            }
        });

        var tableWrapper = $('#sample_1_wrapper'); // datatable creates the table wrapper by adding with id {your_table_jd}_wrapper

        tableWrapper.find('.dataTables_length select').select2(); // initialize select2 dropdown    
</script>
