<div class="row">        
    <div class="col-lg-12">
        <div class="panel panel-green">
            <div class="panel-body">
                        <div class="panel-group" id="accordion2">
                            <div class="col-lg-12">
<!--SEGUROS-->               <h4> <i class="fa fa-shield"></i>  &nbsp; &nbsp;<a data-toggle="collapse" id="seguro" data-parent="#accordion2" href="#seguros">Seguros</a></h4>
                            </div>                            
                <div id="seguros" class="row panel-collapse collapse">
                <?php 
                                        $form = $this->form;
                                        $form->prepare();
                                        $form->setAttributes(array(
                                        'action' => $this->url."/admin/infocom/guardarseguro",
                                        'id' => 'form1'                                    
                                        ));
                                        echo $this->form()->openTag($form);
                                        echo $this->formRow($this->form->get('id_pk'));
                                        ?>                         
                        <div class="col-lg-12">
                             <div class="table-responsive">
                                <table id="stabla1" class="table table-hover" style="text-align: center;">
                                    <thead>
                                        <tr>
                                            <th>N&deg; Poliza</th>
                                            <th>Riesgo</th>
                                            <th>Prima</th>
                                            <th>Cuota</th>
                                            <th>Fecha Termino</th>
                                            <th>Estado</th>
                                            <th>Mas</th>
                                        </tr>
                                    </thead>
                                    <tbody id="segtable" class="text-center">
                                    </tbody>
                                </table>
                            </div> 
                            </div>
                            
                            <div class="row" style="margin-left: 1em; margin-bottom: 2em;">
                            <a id="btnnuevoseguro">                            
                                 <div class="col-lg-2">
                                     <button class="btn btn-success" onclick="return false;"><i class="fa fa-plus"></i> &nbsp;&nbsp;Nuevo</button>
                                 </div>                                             
                           </a> 
                            </div>
                            
                         <div id="divnuevoseguro" style="display: none;" >              
                        <div class="col-lg-9 col-md-9 col-xs-9">
                                 <div class="col-lg-4 col-md-4 col-xs-6">                                                
                                    <label>N&deg; Poliza</label>
                                    <div class="form-group input-group">                                            
                                            <span class="input-group-addon"><i class="fa fa-info"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form->get('poliza'));
                                            ?>                                             
                                    </div>                                                 
                                </div>  
                                <div class="col-lg-4 col-md-4 col-xs-6">                                                
                                    <label>Riesgo</label>
                                    <div class="form-group input-group">                                            
                                            <span class="input-group-addon"><i class="fa fa-info"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form->get('riesgo'));
                                            ?>                                             
                                    </div>                                                 
                                </div>  
                                <div class="col-lg-4 col-md-4 col-xs-6">                                                
                                    <label>Valor Prima</label>                                    
                                    <div class="form-group input-group">                                            
                                            <span class="input-group-addon"><i class="fa fa-dollar"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form->get('valor_prima'));
                                            ?>                                             
                                    </div>                                                 
                                </div>
                                <div class="col-lg-4 col-md-4 col-xs-6">                                                
                                    <label>N&deg; Cuotas</label>
                                    <div class="form-group input-group">                                            
                                            <span class="input-group-addon"><i class="fa fa-calendar"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form->get('cuotas'));
                                            ?>                                             
                                    </div>                                                 
                                </div> 
                                <div class="col-lg-4 col-md-4 col-xs-6">                                                
                                    <label>Inicio Cobertura</label>
                                    <div class="form-group input-group">                                            
                                            <span class="input-group-addon"><i class="fa fa-calendar"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form->get('vigencia'));
                                            ?>                                             
                                    </div>                                                 
                                </div>
                                 <div class="col-lg-4 col-md-4 col-xs-6">                                                
                                    <label>Fin Cobertura</label>
                                    <div class="form-group input-group">                                            
                                            <span class="input-group-addon"><i class="fa fa-calendar"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form->get('vigenciafin'));
                                            ?>                                             
                                    </div>                                                 
                                </div>
                                                                                                                                                                                                                   
                        </div> 
                             
                        <div class="col-lg-3 col-md-3 col-xs-3"> 
                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                <div class="col-lg-6 col-md-6 col-xs-12">                                
                                    <div class="drag-drop" style="margin-top: 25px;">
                                          <?php                                             
                                              echo $this->formRow($this->form->get('filepoliza'));
                                            ?> 
                                             <span class="fa-stack fa-2x">
                                                <i class="fa fa-cloud fa-stack-2x bottom pulsating"></i>
                                                <i class="fa fa-circle fa-stack-1x top medium"></i>
                                                <i class="fa fa-arrow-circle-up fa-stack-1x top"></i>
                                            </span>
                                        <span class="desc">A&ntilde;adir P&oacute;liza</span>
                                    </div>                        
                                </div> 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                        </div>
                        <div class="col-lg-12 col-md-12 col-xs-12">
                                        <div class="form-group">
                                        <label>Detalles</label>
                                        <div class="form-group">                                            
                                            <?php                                             
                                              echo $this->formRow($this->form->get('detalle'));
                                            ?>                                            
                                        </div>
                                        </div>
                                </div>  
                        <div class="col-lg-12 col-md-12 col-xs-12" style="text-align: center;">   
                                                                                  
                                                <?php                                             
                                              echo $this->formRow($this->form->get('sendseg'));
                                            ?> 
                                                                                      
                               </div>
                              </div>        
                </div> 
                     
                <?php echo $this->form()->closeTag()?>          
                            <div class="col-lg-12">
<!--CAMARAS-->                  <h4> <i class="fa fa-video-camera"></i>  &nbsp; &nbsp;<a data-toggle="collapse" data-parent="#accordion2" href="#camaras">C&aacute;maras</a></h4>
                            </div>
                <div id="camaras" class="panel-collapse collapse">
                        <?php 
                                        $form2 = $this->form;
                                        $form2->prepare();
                                        $form2->setAttributes(array(
                                        'action' => $this->url."/admin/infocom/guardarcamara",
                                        'method' => 'post'                                    
                                        ));
                                        echo $this->form()->openTag($form2);
                                        echo $this->formRow($this->form2->get('id_pk'));
                                        ?>
                        <div class="col-lg-6 col-md-6 col-xs-12">
                                 <div class="col-lg-6 col-md-6 col-xs-12">                                                
                                    <label>Camaras de Seguridad</label>
                                    <div class="form-group input-group">                                            
                                            <span class="input-group-addon"><i class="fa fa-video-camera"></i>
                                            </span>
                                            <?php                                             
                                              echo $this->formRow($this->form2->get('camaras'));
                                            ?>                                            
                                    </div>                                                 
                                </div>                                                                                                                      
                                <div class="col-lg-6 col-md-6 col-xs-12">
                                    <div class="form-group" style="margin-top: 30px;">
                                            <label>Graban? : &nbsp;</label>
                                            <label class="radio-inline">
                                                <?php                                             
                                              echo $this->formRow($this->form2->get('graban'));
                                            ?>
                                            </label>
                                            <label class="radio-inline">
                                                <?php                                             
                                              echo $this->formRow($this->form2->get('graban2'));
                                            ?>
                                            </label>
                                    </div>  
                                </div>                                                                                                                                                                                             
                        </div> 
                                
                        <div class="col-lg-6 col-md-6 col-xs-12">                                                                                                                                                                                          
                                <div class="col-lg-12 col-md-6 col-xs-12">
                                    <div class="form-group">
                                            <label>Reglas de Televigilancia</label>
                                            <?php                                             
                                              echo $this->formRow($this->form2->get('reglas'));
                                            ?>
                                    </div>
                                </div>
                        </div> 
                        <div class="row" style="text-align: center;">   
                                        <div class="col-lg-12">                                          
                                                 <?php                                             
                                              echo $this->formRow($this->form2->get('sendcam'));
                                            ?>
                                        </div>                                              
                               </div> 
                                      
                </div>
                <?php echo $this->form()->closeTag()?>
                <div class="col-lg-12">
            <h4> <i class="fa fa-fire"></i>  &nbsp; &nbsp;<a data-toggle="collapse" data-parent="#accordion2" href="#extintores">Incendios y Sismos</a></h4>
                            </div>
                <div id="extintores" class="panel-collapse collapse">
                        <div class="col-lg-6 col-md-6 col-xs-12">
                                <div class="col-lg-4 col-md-12 col-xs-12">
                                    <div class="form-group">
                                            <label>Red Seca: &nbsp;&nbsp;</label>
                                            <label class="radio-inline">
                                                <input type="radio" name="optionsRadiosInline1" id="optionsRadiosInline1" value="option1" checked>Si
                                            </label>
                                            <label class="radio-inline">
                                                <input type="radio" name="optionsRadiosInline1" id="optionsRadiosInline2" value="option2">No
                                            </label>
                                        </div>  
                                </div>
                                <div class="col-lg-4 col-md-12 col-xs-12">
                                    <div class="form-group">
                                            <label>Red H&uacute;meda: &nbsp;&nbsp;</label>
                                            <label class="radio-inline">
                                                <input type="radio" name="optionsRadiosInline2" id="optionsRadiosInline1" value="option3" checked>Si
                                            </label>
                                            <label class="radio-inline">
                                                <input type="radio" name="optionsRadiosInline2" id="optionsRadiosInline2" value="option4">No
                                            </label>
                                        </div>  
                                </div>
                                <div class="col-lg-4 col-md-12 col-xs-12">
                                    <div class="form-group">
                                           <label>Rociadores:</label>
                                           <label class="radio-inline">
                                               <input type="radio" name="optionsRadiosInline3" id="optionsRadiosInline1" value="option1" checked>Si
                                           </label>
                                           <label class="radio-inline">
                                               <input type="radio" name="optionsRadiosInline3" id="optionsRadiosInline2" value="option2">No
                                           </label>
                                       </div>  
                                </div>
                                 <div class="col-lg-6 col-md6 col-xs-12">                                                
                                    <label>Extintores</label>                                    <div class="form-group input-group">                                            
                                           <span class="input-group-addon"><i class="fa fa-fire-extinguisher"></i>
                                           </span>
                                           <input type="number" class="form-control" placeholder="Cantidad" required="true" style="max-width: 80%;"/>                                            
                                   </div>                                                 
                               </div>
                               <div class="col-lg-6 col-md-6 col-xs-12">                                                
                                   <label>Detectores Humo</label>
                                   <div class="form-group input-group">                                            
                                           <span class="input-group-addon"><i class="fa fa-fire"></i>
                                           </span>
                                           <input type="number" class="form-control" placeholder="Cantidad" required="true" style="max-width: 80%;"/>                                            
                                   </div>                                                 
                               </div>                                                                                                                                                                                                                                                                                                                                                    
                       </div> 
                       <div class="col-lg-6 col-md-12 col-xs-12">
                        
                       <div class="col-lg-12 col-md-6 col-xs-12">                                                                                                                                                                                          
                               <div class="col-lg-12 col-md-6 col-xs-12">
                                   <div class="form-group">
                                           <label>Otros</label>
                                           <textarea class="form-control" placeholder="Escriba aqui..." rows="3"></textarea>
                                   </div>
                               </div>
                               <div class="col-lg-3 col-md-3 col-xs-3"> 
                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                               <div class="col-lg-6 col-md-6 col-xs-12">                                
                                   <div class="drag-drop" style="margin-top: 25px;">
                                         <input type="file" multiple="multiple"/> 
                                            <span class="fa-stack fa-2x">
                                               <i class="fa fa-cloud fa-stack-2x bottom pulsating"></i>
                                               <i class="fa fa-circle fa-stack-1x top medium"></i>
                                               <i class="fa fa-arrow-circle-up fa-stack-1x top"></i>
                                           </span>
                                       <span class="desc">Plan de Evacuaci&oacute;n</span>
                                    <div>                        
                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                        </div>
                        </div>
                        </div> 
                        <div class="row" style="text-align: center;">   
                                        <div class="col-lg-12">                                          
                                                 <button type="button" class="btn btn-success btn-circle btn-lg" style="margin-top: 30px;"><i class="fa fa-save"></i></button>
                                        </div>                                              
                               </div>                                                                                                                                     
                        </div>
                        <div class="col-lg-12">
            <h4> <i class="fa fa-key"></i> &nbsp;&nbsp;<a data-toggle="collapse" data-parent="#accordion2" href="#accesos">Accesos</a></h4>
                            </div>
            </div>                                        
        </div>   
    </div>  
</div>

<script>
toastr.options = {
  "positionClass": "toast-top-center",
}
$("#btnnuevoseguro").click(function(){  
  $("#divnuevoseguro").fadeIn(800);
  $("#btnnuevoseguro").fadeOut(800); 
})
$("#seguro").click(function(){
	$.ajax( {  
        url : '<?php echo $this->basePath()."/admin/infocom/seguro"?>',
		type : 'post',
        beforeSend : function() {
            var table = document.getElementById("stabla1");            
           for(var i = table.rows.length - 1; i > 0; i--)
            {
            table.deleteRow(i);
            }
            },        
		success : function(response) { 
		  
          for (i=0; i<response.seg.length; i++) {
          if(response.seg[i].estado=='0'){var estadoseg="<i class='fa fa-check fa-2x'></i>";}else{var estadoseg="<i class='fa fa-close fa-2x'></i>";}
          $("#segtable").append("<tr><td>"+response.seg[i].poliza+"</td><td>"+response.seg[i].riesgo+"</td><td>$ "+response.seg[i].valor_prima+"</td><td>0/"+response.seg[i].cuotas+"</td><td>"+response.seg[i].vigenciafin+"</td><td>"+estadoseg+"</td><td> <a href='javascript:void(0)' onclick='verDatosSeg("+response.seg[i].id+","+response.seg[i].estado+");' data-toggle='modal' data-target='#myModal'><i class='fa fa-eye fa-2x'></i></a></td></tr>");
          
          }        
		}
	});   
}
);
$("#form1").submit(function(e)
{
    var postData = $(this).serializeArray();
    var formURL = $(this).attr("action");
    $.ajax(
    {
        url : formURL,
        type: "POST",
        data : postData,
        dataType : 'json',
        success : function(response) {                    
          toastr.success(response.descripcion);          
          $('.panel-collapse.in').collapse('toggle'); 
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {
            $("#mostrarSeg").html('<div id="respuesta" class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>Error en el env&iacute;o de datos al servidor</div>')      
        }
    });
    e.preventDefault(); //STOP default action
    e.unbind(); //unbind. to stop multiple form submit.
});
</script>                             