<div class="row">        
    <div class="col-lg-12">
        <div class="panel panel-green">
            <div class="panel-body">
                        <div class="panel-group" id="accordion2">
                            <div class="col-lg-12">
<!--SEGUROS-->               <h4> <i class="fa fa-shield"></i>  &nbsp; &nbsp;<a onclick="OpenSeguro()" data-toggle="collapse" data-parent="#accordion2" href="#seguros">Seguros del Condominio</a></h4>
                            </div>                            
                <div id="seguros" class="row panel-collapse collapse">
                      
                        <div class="col-lg-12">
                             <div class="table-responsive">
                                <table id="stabla1" class="table table-hover" style="text-align: center;">
                                    <thead>
                                        <tr>
                                            <th>N&deg; Poliza</th>
                                            <th>Riesgo</th>
                                            <th>Prima Mensual</th>
                                            <th>Prox. Cuota</th>
                                            <th>Cobertura</th>
                                            <th>Estado</th>
                                            <th>Ver P&oacute;liza</th>
                                        </tr>
                                    </thead>
                                    <tbody id="segtable" class="text-center">
                                    </tbody>
                                </table>
                            </div> 
                            </div>
                            
                            <div class="row" style="margin-left: 1em; margin-bottom: 2em;">
                            <a id="btnnuevoseguro">                            
                                 <div class="col-lg-2">
                                     <button class="btn btn-success" onclick="return false;"><i class="fa fa-plus"></i> &nbsp;&nbsp;Nuevo</button>
                                 </div>                                             
                           </a> 
                            </div>
                            
                         <div id="divnuevoseguro" style="display: none;" >              

                        </div> 
       
                </div>                                      
                            <div class="col-lg-12">
<!--CAMARAS-->                  <h4> <i class="fa fa-video-camera"></i>  &nbsp; &nbsp;<a id="camara" data-toggle="collapse" data-parent="#accordion2" href="#camaras">C&aacute;maras</a></h4>
                            </div>
                <div id="camaras" class="panel-collapse collapse">
                       
                                      
                </div>
                <?php echo $this->form()->closeTag()?>
               
                <div class="col-lg-12">
<!--Plan Emergencia-->  <h4> <i class="fa fa-ambulance"></i>  &nbsp; &nbsp;
        <a id="plan_emergencia" data-toggle="collapse" data-parent="#accordion2" href="#planes">Plan de Emergencia</a></h4>
                </div>
                
                <div id="planes" class="panel-collapse collapse">  
                       
                        <div class="col-lg-12">
                             <div class="table-responsive">
                                <table id="ptabla1" class="table table-hover" style="text-align: center;">
                                    <thead>
                                        <tr>
                                            <th>N&deg; Poliza</th>
                                            <th>Fecha ingreso</th>                                                                                                                                    
                                            <th>Estado</th>
                                            <th>Ver P&oacute;liza</th>
                                        </tr>
                                    </thead>
                                    <tbody id="plantable" class="text-center">
                                    </tbody>
                                </table>
                            </div> 
                            </div>
                        
                        
                        
                        <form id="form_plan" action="<?php echo $this->basePath()."/admin/infocom/emergencia"?>" method="post">
                        <input type="hidden" id="url_plan" name="url_plan" value="" />                      
                       <div class="col-lg-4  udt">
                            <br />
                            <a>
                                <a class="btn btn-success"><i id="icnAdjuntarPlan" class="fa fa-file"></i> Adjuntar Plan de Emergencia</a>      
                            <input type="file" name="fileplan" onchange="selecciona2()" required="required" id="fileplan">                                                                                                                                                                                                                                                                              
                            </a> 
                        </div>   
                        <div class="col-md-12">
                            <span id="mostrarnombre2"></span>
                          </div>                     
                        <div class="row" style="text-align: center;">   
                                        <div class="col-lg-12">                                          
                                                 <input id="sendplan" type="button" class="btn btn-success btn-circle btn-lg" style="margin-top: 30px;" value="Guardar Plan"/>
                                        </div>                                              
                        </div>   
                                                
                         </form>                                                                                                                                  
                </div>
               
            </div>                                        
        </div>   
    </div>  
</div>
</div>
</div>
</div>

<script type="text/javascript" >
toastr.options = {
  "positionClass": "toast-top-center",
}
$("#btnnuevoseguro").click(function(){  
    $.ajax({
        url:'<?php echo $this->basePath()."/admin/infocom/formseguro"?>',
        success: function(response){
            $("#divnuevoseguro").html(response);
            $("#divnuevoseguro").fadeIn(800);       
            $("#btnnuevoseguro").fadeOut(800);     
        }        
    });   
});
function OpenSeguro(){
	$.ajax( {  
        url : '<?php echo $this->basePath()."/admin/infocom/seguro"?>',
		type : 'post',
        beforeSend : function() {
            var table = document.getElementById("stabla1");            
           for(var i = table.rows.length - 1; i > 0; i--)
            {
            table.deleteRow(i);
            }
            },        
		success : function(response) { 		  
		  $("#segtable").append(response.tabla);
          /*for (i=0; i<response.seg.length; i++) {
          if(response.seg[i].estado=='0'){var estadoseg="<i class='fa fa-check fa-2x'></i>";}else{var estadoseg="<i class='fa fa-close fa-2x'></i>";}
          $("#segtable").append("<tr><td>"+response.seg[i].poliza+"</td><td>"+response.seg[i].riesgo+"</td><td>$ "+response.seg[i].valor_prima+"</td><td>0/"+response.seg[i].cuotas+"</td><td>"+response.seg[i].vigenciafin+"</td><td>"+estadoseg+"</td><td> <a href='javascript:void(0)' onclick='verDatosSeg("+response.seg[i].id+","+response.seg[i].estado+");' data-toggle='modal' data-target='#myModal'><i class='fa fa-eye fa-2x'></i></a></td></tr>");
          }      */  
		}
	});   
}

$("#camara").click(function(){
	$.ajax( {  
        url : '<?php echo $this->basePath()."/admin/infocom/camaras"?>',    
		beforeSend : function() {
          $("#camaras").html("");  
            }, 
        success : function(response) { 		  
		  $("#camaras").append(response);
		},
        error: function(jqXHR, textStatus, errorThrown) {
            toastr.error("Ups, ha ocurrido un error inesperado, favor contacta con soporte");
        }
	});   
});
function nuevoProveedor(){
    $.ajax({
        url: '<?php echo $this->basePath()."/admin/infocom/nuevoasegurador"?>',
        success: function(response){
            $("#mostrarDatos").html(response)
        },
        error: function(jqXHR, textStatus, errorThrown) {
            toastr.error("Ups, ha ocurrido un error inesperado, favor contacta con soporte");
        }
        
    })
    
}
function loadImg(){
    $("#sendseg").attr('disabled','disabled');
    $("#filepoliza").add('class','btn-warning');                                        
    $("#sendseg").val('Subiendo imagen...');
    $("#icnAdjuntarPoliza").attr("class","fa fa-spinner fa-spin");    
}  
function unloadImg(){
    $("#sendseg").removeAttr('disabled');
    $("#filepoliza").add('class','btn-success');                                        
    $("#sendseg").val('Adjuntar Boleta');
    $("#icnAdjuntarPoliza").attr("class","fa fa-file"); 
    $("#sendseg").val('Guardar Seguro');      
}   
function formatMonto(){  
    var format = $("#valor_prima").val().replace(/\./g,'').replace(/\B(?=(\d{3})+(?!\d))/g, ".")
    $("#valor_prima").val(format);
    $("#valor_prima").val(format);
}
function selecciona(){
    if(document.getElementById('filepoliza').files[0].size<2500000){  	                        
            var file_data = $('#filepoliza').prop('files')[0];
            var parametros = new FormData();                  
                           parametros.append('fileData', file_data);
                           $.ajax( {
                                    contentType:false,
                                    processData:false,	
                                    cache:false,
                                    data : parametros,
                                    url : '<?php echo $this->basePath()."/admin/infocom/segurofile"?>',
                                    type : 'post',
                                    beforeSend : function() {
                                        loadImg();
                                    },
                                    success : function(response) {
                                        if(response.status == "nok"){
                                            toastr.warning(response.desc);
                                            unloadImg()
                                        }else{
                                            toastr.success(response.desc);       
                                            $("#sendseg").removeAttr('disabled');                                                                                                                            
                                            $("#sendseg").val('Guardar Seguro');                                        
                                            document.getElementById("mostrarnombre").innerHTML="Archivo subido OK: [<strong>"+document.getElementById('filepoliza').files[0].name+"</strong>]";
                                            $("#url_poliza").val(response.name);   
                                            $("#icnAdjuntarPoliza").attr("class","fa fa-check"); 
                                        }
                                                                                                              
                                    },      
                            });
        
    }else{
     document.getElementById("mostrarnombre").innerHTML="<font color='red'>Error Ha superado el limite permitido (2Mb): [<strong>"+document.getElementById('filepoliza').files[0].name+"</strong>] NOK</font>";
    }
}
function loadImg2(){
    $("#sendplan").attr('disabled','disabled');
    $("#fileplan").add('class','btn-warning');                                        
    $("#sendplan").val('Subiendo imagen...');
    $("#icnAdjuntarPlan").attr("class","fa fa-spinner fa-spin");    
}  
function unloadImg2(){
    $("#sendplan").removeAttr('disabled');
    $("#fileplan").add('class','btn-success');                                        
    $("#sendplan").val('Adjuntar Boleta');
    $("#icnAdjuntarPlan").attr("class","fa fa-file"); 
    $("#sendplan").val('Guardar Plan');      
}  
function selecciona2(){
    if(document.getElementById('fileplan').files[0].size<4500000){  	                        
            var file_data = $('#fileplan').prop('files')[0];
            var parametros = new FormData();                  
                           parametros.append('fileData', file_data);
                           $.ajax( {
                                    contentType:false,
                                    processData:false,	
                                    cache:false,
                                    data : parametros,
                                    url : '<?php echo $this->basePath()."/admin/infocom/emergenciafile"?>',
                                    type : 'post',
                                    beforeSend : function() {
                                        loadImg2();
                                    },
                                    success : function(response) {
                                        if(response.status == "nok"){
                                            toastr.warning(response.desc);
                                            unloadImg2()
                                        }else{
                                            toastr.success(response.desc);       
                                            $("#sendplan").removeAttr('disabled');                                                                                                                            
                                            $("#sendplan").val('Guardar Plan');  
                                            $("#url_plan").val(response.name);                                      
                                            document.getElementById("mostrarnombre2").innerHTML="Archivo subido OK: [<strong>"+document.getElementById('fileplan').files[0].name+"</strong>]";                                             
                                            $("#icnAdjuntarPlan").attr("class","fa fa-check"); 
                                        }
                                                                                                              
                                    },      
                            });
        
    }else{
     document.getElementById("mostrarnombre2").innerHTML="<font color='red'>Error Ha superado el limite permitido (2Mb): [<strong>"+document.getElementById('filepoliza').files[0].name+"</strong>] NOK</font>";
    }
}
$("#sendplan").click(function()
{
    var postData = $("#form_plan").serializeArray();
    var formURL = $("#form_plan").attr("action");
    $.ajax(
    {
        url : formURL,
        type: "POST",
        data : postData,
        dataType : 'json',
        success : function(response) {                    
          toastr.success(response.desc);          
          $('.panel-collapse.in').collapse('toggle');                               
          $('html, body').animate({ scrollTop: 0 }, 'slow');          
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {
            toastr.error("Ups, ha ocurrido un error inesperado, favor contacta con soporte");
        }
    });  
    
    
});
$("#plan_emergencia").click(function(){
	$.ajax( {  
        url : '<?php echo $this->basePath()."/admin/infocom/emergencia"?>',
		type : 'post',
        beforeSend : function() {
            var table = document.getElementById("ptabla1");            
           for(var i = table.rows.length - 1; i > 0; i--)
            {
            table.deleteRow(i);
            }
            },        
		success : function(response) { 		  
		  $("#plantable").append(response.tabla);        
		}
	});   
}
);
</script>                             