
	<div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <tbody>
                                        <tr class="odd gradeX">
                                            <td>Nro Ticket: </td>
                                            <td><label><?php echo $this->lista[0]['id']?></label></td>
                                        </tr>
                                        <tr class="odd gradeX">
                                            <td>Departamento: </td>
                                            <td><label><?php echo $this->lista[0]['dpto']?></label></td>
                                        </tr>
                                        <tr class="odd gradeX">
                                            <td>Para: </td>
                                            <td><label><?php echo $this->lista[0]['receptor']?></label></td>
                                        </tr>
                                        <tr class="odd gradeX">
                                            <td>Asunto: </td>
                                            <td><label><?php echo $this->lista[0]['asunto']?></label></td>
                                        </tr>
                                        <tr class="odd gradeX">
                                            <td>Descripcion: </td>
                                            <td><label><?php echo $this->lista[0]['descripcion']?></label></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
      </div>




