<h2 class="page-header"><a href="<?php echo $this->basePath()?>/conserje"><i class="fa fa-arrow-circle-left fa-1x"></i></a>   Seleccione su opci&oacute;n </h2>
<br /><br />
<div class="row">
            <a href="<?php echo $this->basePath()?>/conserje/reclamo/nuevo">
               <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-9 text-left">
                                    <div class="huge">Ingresar</div>
                                    <div class="huge">Reclamo</div>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Seleccionar</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                             </a>
                    </div>
                </div>
               

            <a href="<?php echo $this->basePath()?>/conserje/reclamo/consultar">
               <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-9 text-left">
                                    <div class="huge">Ver</div>
                                    <div class="huge">Reclamos</div>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Seleccionar</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                            </a>
                    </div>
                </div>                            

</div>