<h2 class="page-header"><a href="<?php echo $this->basePath()?>/conserje/reclamo">
<i class="fa fa-arrow-circle-left fa-1x"></i></a> <?php echo $this->titulo ?> </h2>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="panel panel-info">
                     <div class="panel-heading">
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <?php 
                                    $form = $this->form;
                                    $form->prepare();
                                    $form->setAttributes(array(
                                    'action' =>$this->url.'/conserje/reclamo/nuevo',
                                    'method' => 'post'
                                    ));
                                    echo $this->form()->openTag($form);
                                    echo $this->formRow($this->form->get('id_pk'));
                                    ?>
                                        <div class="form-group">
                                            <label>Departamento</label>
                                            <?php                                             
                                              echo $this->formRow($this->form->get('id_dpto'));
                                            ?>
                                        </div>
                                        <div class="form-group">
                                            <label>Para</label>
                                            <?php 
                                              echo $this->formInput($this->form->get('receptor'));
                                            ?>                                            
                                        </div> 
                                        <div class="form-group">
                                            <label>Asunto</label>
                                            <?php 
                                              echo $this->formRow($this->form->get('id_tipo_asunto'));
                                            ?>
                                        </div>                                                                                  
                                        <div class="form-group">
                                            <label>Descripcion</label>                                            
                                            <?php 
                                              echo $this->formRow($this->form->get('descripcion'));
                                            ?>
                                        </div>                                    
                                        <div class="form-group">
                                        <p class="help-block">Su reclamo sera notificado por nuestro sistema al Administrador</p>            
                                        <?php
                                         echo " ".$this->formRow($this->form->get('reset'));
                                         echo " ".$this->formRow($this->form->get('send'));
                                        ?>
                                        </div>
                                    <?php echo $this->form()->closeTag()?>
                                </div>
                                <!-- /.col-lg-6 (nested) -->
                                <div class="col-lg-6">                                   
                                </div>
                                <!-- /.col-lg-6 (nested) -->
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
    <script type="text/javascript">                    
//<![CDATA[
        bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
  //]]>
  </script>