<div class="row">
				<div class="col-md-12 ">
					<!-- BEGIN SAMPLE FORM PORTLET-->
					<div class="portlet box blue-madison">
						<div class="portlet-title blue-madison">
							<div class="caption">
								<i class="fa fa-briefcase"></i>  Biblioteca del condominio  
							</div>                            
						</div>
                        <div class="portlet-body"> 
                        <div class="tiles">
													<a href="/files/ley.pdf" target="_blank">
                                                    <div class="tile bg-blue">
														<div class="tile-body">
															<i class="fa fa-legal"></i>
														</div>
														<div class="tile-object">
															<div class="name">
																 Ley 19.537
															</div>
															<div class="number">
															</div>
														</div>
													</div>
                                                    </a>
                                                    <div class="tile bg-blue">
														<div class="tile-body">
															<i class="fa fa-cogs"></i>
														</div>
														<div class="tile-object">
															<div class="name">
																 Reglamento Interno
															</div>
															<div class="number">
															</div>
														</div>
													</div>
                        </div>
 
                        </div>
      </div>
     </div>
    </div>