          <div class="panel-collapse collapse">
                                    <?php 
                                        $form = $this->form;
                                        $form->prepare();
                                        $form->setAttributes(array(
                                        'action' => $this->url."/admin/infocom/guardarlavanderia",
                                        'method' => 'post',
                                        'id' => 'form',                                    
                                        ));
                                        // echo$this->form()->openTag($form);
                                        // echo$this->formRow($this->form->get('id_pk'));
                                        ?> 
                                    <div class="col-lg-12 col-md-12 col-xs-12">
                                    <div class="form-group">
                                            <label>Habilitada:&nbsp;&nbsp;  </label>
                                            <label class="radio-inline">
                                                <?php                                             
                                              // echo$this->formRow($this->form->get('estadolav1'));
                                                ?>
                                            </label>
                                           <label class="radio-inline">
                                                <?php                                             
                                              // echo$this->formRow($this->form->get('estadolav2'));
                                                ?>
                                            </label>                                               
                                        </div>  
                                        </div>
                                    <div class="col-lg-3 col-md-3 col-xs-6">                                    
                                        <div class="form-group">
                                        <label>Lavadoras:</label>
                                        <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-instagram"></i>
                                            </span>
                                            <?php                                             
                                              // echo$this->formRow($this->form->get('lavadoras'));
                                            ?>                                             
                                        </div>
                                         </div>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-xs-6">
                                        <div class="form-group">
                                        <label>Secadoras:</label>
                                        <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-instagram"></i>
                                            </span>
                                            <?php                                             
                                              // echo$this->formRow($this->form->get('secadoras'));
                                            ?>                                             
                                        </div>
                                        </div>
                                        </div>  
                                        <div class="col-lg-3 col-md-6 col-xs-6">
                                            <div class="form-group">
                                                <label>Valor:</label>
                                                <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-dollar"></i>
                                            </span>
                                               <?php                                             
                                              // echo$this->formRow($this->form->get('valor'));
                                                ?>                                              
                                            </div>
                                             </div>
                                        </div>
                                        <div class="col-lg-12 col-md-12 ">
                                        <div class="form-group">
                                            <label>Horario: &nbsp;</label>
                                        </div> 
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-xs-6">                                         
                                        <div class="form-group">
                                        <label>Desde:</label>
                                        <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-clock-o"></i>
                                            </span>
                                            <?php                                             
                                              // echo$this->formRow($this->form->get('horario'));
                                                ?>                                             
                                        </div>
                                         </div>
                                        </div> 
                                        <div class="col-lg-3 col-md-3 col-xs-6"> 
                                        <div class="form-group">
                                        <label>Hasta:</label>
                                        <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-clock-o"></i>
                                            </span>
                                            <?php                                             
                                              // echo$this->formRow($this->form->get('horariofin'));
                                            ?>                                            
                                        </div>
                                         </div>
                                        </div>  
                                        <div class="col-lg-6 col-md-6">
                                        <div class="form-group">
                                            <label>Reglas y/o Comentarios</label>
                                            <?php                                             
                                              // echo$this->formRow($this->form->get('reglas'));
                                            ?>
                                        </div>
                                        </div>                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                        <div class="row" style="text-align: center;">   
                                        <div class="col-lg-12 col-md-12">                                          
                                                 <?php                                             
                                              // echo$this->formRow($this->form->get('sendlav'));
                                                ?>
                                                 </div>                                              
                                        </div>
                                    </div>
<?php // echo$this->form()->closeTag()?>   