<div class="row">
				<div class="col-md-12 ">
					<!-- BEGIN SAMPLE FORM PORTLET-->
					<div class="portlet box blue-madison">
						<div class="portlet-title blue-madison">
							<div class="caption">
								<i class="fa fa-envelope"></i>  Mi Buz&oacute;n
							</div>                            
						</div>
                        <div class="portlet-body"> 
						
                <div class="col-lg-12">
                <h3 class="page-header" ><i class="fa fa-list-alt" style="font-size: 20px;"></i> &nbsp;&nbsp;Mensajes sin Responder</h3>    
                </div>
                    
                        
                        
                        	<table class="table table-striped table-bordered table-hover" id="sample_1">
							<thead>
                                <tr>
                                    <td> N&deg;</td>
                                    <td><i class="fa fa-calendar"></i> Fecha</td>
                                    <td><i class="fa fa-home"></i> Departamento</td>
                                    <td><i class="fa fa-tag"></i> Asunto</td>                                    
                                    <td><i class="fa fa-plus"></i> Detalles</td>                                
                                </tr>
							</thead>
							<tbody>
                                <tr>
                                    <td>025</td>
                                    <td>27-11-2015</td>
                                    <td>603</td>
                                    <td>Gastos Comunes</td>                                    
                                    <td><a> Abrir</a></td>                                
                                </tr>
                                <tr>
                                    <td>027</td>
                                    <td>21-11-2015</td>
                                    <td>603</td>
                                    <td>Asamblea</td>                                    
                                    <td><a> Abrir</a></td>                                
                                </tr>
                                <tr>
                                    <td>035</td>
                                    <td>28-11-2015</td>
                                    <td>603</td>
                                    <td>Salvo Conducto</td>                                    
                                    <td>
                                        <a onclick="detalleMs()"> 
                                            Abrir
                                        </a>
                                    </td>                                
                                </tr>
							</tbody>
							</table>
                            
                <div class="col-lg-12">
                <h3 class="page-header" ><i class="fa fa-history" style="font-size: 20px;"></i> &nbsp;&nbsp;Mensajes respondidos</h3>    
                </div>
                    
                        
                        
                        	<table class="table table-striped table-bordered table-hover" id="sample_1">
							<thead>
                                <tr>
                                    <td> N&deg;</td>
                                    <td><i class="fa fa-calendar"></i> Fecha</td>
                                    <td><i class="fa fa-home"></i> Departamento</td>
                                    <td><i class="fa fa-tag"></i> Asunto</td>                                    
                                    <td><i class="fa fa-plus"></i> Detalles</td>                                
                                </tr>
							</thead>
							<tbody>
                                <tr>
                                    <td>025</td>
                                    <td>27-11-2015</td>
                                    <td>603</td>
                                    <td>Gastos Comunes</td>                                    
                                    <td><a> Abrir</a></td>                                
                                </tr>
                                <tr>
                                    <td>027</td>
                                    <td>21-11-2015</td>
                                    <td>603</td>
                                    <td>Asamblea</td>                                    
                                    <td><a> Abrir</a></td>                                
                                </tr>
                                <tr>
                                    <td>035</td>
                                    <td>28-11-2015</td>
                                    <td>603</td>
                                    <td>Salvo Conducto</td>                                    
                                    <td><a> Abrir</a></td>                                
                                </tr>
							</tbody>
							</table>
                            
                        </div>
      </div>
     </div>
    </div>
<script>
function detalleMs(){
$.ajax({
    url:<?php echo $this->basePath()."/admin/comunicacion/detallemensaje"?>,
    data:,
    before:,
    success:,
    error:,                        
});        
}
</script>        