<div class="row">
				<div class="col-md-12 ">
					<!-- BEGIN SAMPLE FORM PORTLET-->
					<div class="portlet box blue-madison">
						<div class="portlet-title blue-madison">
							<div class="caption">
								<i class="fa fa-bullhorn"></i>  Reclamos del condominio
							</div>                            
						</div>
                        <div class="portlet-body"> 

                            
                        </div>
      </div>
     </div>
    </div>