<div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-primary">
                        <div class="panel-body">
                            <div class="row"> 
                                <div class="col-lg-4 text-center">    .                                  
                                        <img src="<?php echo $this->basePath()?>/img/foto_perfil/avatar.png"  class="img-circle">                                        
                                </div>                                                                                                                                                                                             
                                <div class="col-lg-8">    .
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                              <td>N&deg; Dpto</td>
                                              <td>Titular</td>
                                              <td>Condici&oacute;n</td>
                                              <td>G Comunes</td>
                                            </tr>
                                        </thead>
                                
                                        <tbody>                                        
                                            <td>201</td>
                                            <td>Juan Soto</td>
                                            <td>Propietario</td>
                                            <td>Moroso</td>                                        
                                        </tbody>
                                    </table>                                                                                                                        
                                </div>                                                              
                        </div>                         
                        <!-- /.panel-body -->
                    </div>                    
                    <!-- /.panel -->
                </div>
                 <div class="row text-center">
                                <a class="btn btn-danger" data-dismiss='modal'> Salir</a>
                        </div>
                <!-- /.col-lg-12 -->
            </div>