<h2 class="page-header">Conserjer&iacute;a en L&iacute;nea</h2>
<br/> <br/>
<section id="menu_conserje">
<div class="row">
  <a href="<?php echo $this->basePath()?>/conserje/visita">
                <div class="col-lg-4 col-md-6 col-sm-4">
                    <div class="panel panel-red">
                        <div class="panel-heading heading-conserje">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-book fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Libro</div>
                                    <div class="huge">Visitas</div>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Abrir Libro</span>                            
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
                </a>  
  <!--a href="<?php echo $this->basePath()?>/conserje/reclamo">
                <div class="col-lg-4 col-md-6 col-sm-4">
                    <div class="panel panel-red">
                        <div class="panel-heading heading-conserje">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-exclamation-circle fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Libro</div>
                                    <div class="huge">Reclamos</div>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalles</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                    </div>
                </div>
                </a-->  
 <a href="<?php echo $this->basePath()?>/conserje/encomienda">               
                <div class="col-lg-4 col-md-6 col-sm-4">
                    <div class="panel panel-red">
                        <div class="panel-heading heading-conserje">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-book fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Libro</div>
                                    <div class="huge">Encomiendas</div>                                    
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Abrir Libro</span>                                
                                <div class="clearfix"></div>
                            </div>
                         
                    </div>
                </div>
 </a>                 
 <a href="<?php echo $this->basePath()?>/conserje/notificacion">               
                <div class="col-lg-4 col-md-6 col-sm-4">
                    <div class="panel panel-red">
                        <div class="panel-heading heading-conserje">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-paper-plane fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Notificar</div>
                                    <div class="huge">Comunidad</div>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalles</span>                                
                                <div class="clearfix"></div>
                            </div>
                         
                    </div>
                </div>
     </a>
 <a href="<?php echo $this->basePath()?>/conserje/quincho">               
                <div class="col-lg-4 col-md-6 col-sm-4">
                    <div class="panel panel-red">
                        <div class="panel-heading heading-conserje">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-cutlery fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Libro</div>
                                    <div class="huge">Quinchos</div>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalles</span>                                
                                <div class="clearfix"></div>
                            </div>
                       
                    </div>
                </div>
                 </a>
 <!--a href="<?php echo $this->basePath()?>/conserje/multa">               
                <div class="col-lg-4 col-md-6 col-sm-4">
                    <div class="panel panel-red">
                        <div class="panel-heading heading-conserje">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-user-secret fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Libro</div>
                                    <div class="huge">Multas</div>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalles</span>                                
                                <div class="clearfix"></div>
                            </div>
                       
                    </div>
                </div>
                 </a-->
 <!--a href="<?php echo $this->basePath()?>/conserje/circular">               
                <div class="col-lg-4 col-md-6 col-sm-4">
                    <div class="panel panel-red">
                        <div class="panel-heading heading-conserje">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-file fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Libro</div>
                                    <div class="huge">Circulares</div>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalles</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                       
                    </div>
                </div>
                 </a-->                                                      
  <!--<a href="<?php echo $this->basePath()?>/conserje/estadistica">               
                <div class="col-lg-4 col-md-6 col-sm-4">
                    <div class="panel panel-blue">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-bar-chart-o fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Estadisticas</div>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalles</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                       
                    </div>
                </div>
                 </a>-->
 <!--<a href="<?php echo $this->basePath()?>/conserje/comentario">               
                <div class="col-lg-4 col-md-6 col-sm-4">
                    <div class="panel panel-blue">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-comment fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Dejanos un</div>
                                    <div class="huge">Comentario!</div>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalles</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        
                    </div>
                </div>
                </a>-->
 </section>