<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="es">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
<meta charset="utf-8"/>
<title>Ingresar al Sistema | becheck</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta content="" name="description"/>
<meta content="" name="author"/>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath()?>/metronic/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath()?>/metronic/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath()?>/metronic/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath()?>/metronic/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL STYLES -->
<link href="<?php echo $this->basePath()?>/metronic/global/plugins/select2/select2.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath()?>/metronic/admin/pages/css/login-soft.css" rel="stylesheet" type="text/css"/>
<!-- END PAGE LEVEL SCRIPTS -->
<!-- BEGIN THEME STYLES -->
<link href="<?php echo $this->basePath()?>/metronic/global/css/components-rounded.css" id="style_components" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath()?>/metronic/global/css/plugins.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath()?>/metronic/admin/layout/css/layout.css" rel="stylesheet" type="text/css"/>
<link id="style_color" href="<?php echo $this->basePath()?>/metronic/admin/layout/css/themes/default.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath()?>/metronic/admin/layout/css/custom.css" rel="stylesheet" type="text/css"/>
<!-- END THEME STYLES -->
<link href="<?php echo $this->basePath()?>/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon"/>

<script src="<?php echo $this->basePath()?>/metronic/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath()?>/metronic/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath()?>/metronic/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath()?>/metronic/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath()?>/metronic/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath()?>/metronic/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?php echo $this->basePath()?>/metronic/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath()?>/metronic/global/plugins/backstretch/jquery.backstretch.min.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath()?>/metronic/global/plugins/select2/select2.min.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?php echo $this->basePath()?>/metronic/global/scripts/metronic.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath()?>/metronic/admin/layout/scripts/layout.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath()?>/metronic/admin/layout/scripts/demo.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath()?>/metronic/admin/pages/scripts/login-soft.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath()?>/js/md5.js"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
jQuery(document).ready(function() {     
  Metronic.init(); // init metronic core components
Layout.init(); // init current layout
  Login.init();
  Demo.init();
       // init background slide images
       $.backstretch([
        "<?php echo $this->basePath()?>/metronic/admin/pages/media/bg/1.jpg",
        "<?php echo $this->basePath()?>/metronic/admin/pages/media/bg/4.jpg",
        "<?php echo $this->basePath()?>/metronic/admin/pages/media/bg/3.jpg",
        "<?php echo $this->basePath()?>/metronic/admin/pages/media/bg/4.jpg"
        ], {
          fade: 1000,
          duration: 6000
    }
    );
});
</script>
</head>

  <?php echo $this->content; ?>

</html>


