 <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->basePath()?>/usuario">Comunidad Santa Rosa</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <a href="#">
                                <div>
                                    <strong>Operacion</strong>
                                    <span class="pull-right text-muted">
                                        <em>Ayer</em>
                                    </span>
                                </div>
                                <div>Se carga la tabla maestra de proveedores</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Leer Todos los mensajes</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-messages -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-tasks">
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i>Nuevo Corte de Energia 20/11/2014 a las 10 - 12 Horas
                                    <span class="pull-right text-muted small">Hace 4 minutos</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-facebook fa-fw"></i> 3 Nuevos Seguidores
                                    <span class="pull-right text-muted small">Hace 1 hora</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Ver todas las Notificaciones</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="<?php echo $this->basePath()?>/application/perfil"><i class="fa fa-user fa-fw"></i> Perfil</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Ajustes</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="<?php echo $this->basePath()?>/application/login/salir"><i class="fa fa-sign-out fa-fw"></i> Salir</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Buscar..."/>
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button" onclick="alert('En Construcción...');">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a class="<?php echo $this->inicio?>" href="<?php echo $this->basePath()?>/usuario"><i class="fa fa-home fa-fw"></i> Inicio</a>
                        </li>                        
                        <li class="<?php echo $this->gcomun?>">
                            <a class="<?php echo $this->gcomunprincipal?>" href="<?php echo $this->basePath()?>/usuario/reclamo"><i class="fa fa-money fa-fw"></i> Gastos Comunes<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a class="<?php echo $this->gcomunnuevo?>" href="<?php echo $this->basePath()?>/usuario/gcomunes/nuevo"><i class="fa fa-arrow-circle-right fa-fw"></i> Nuevo Gasto</a>
                                </li>
                                <li>
                                    <a class="<?php echo $this->reclamoconsultar?>" href="<?php echo $this->basePath()?>/usuario/reclamo/consultar"><i class="fa fa-arrow-circle-right fa-fw"></i> Ver Reclamos</a>
                                </li>
                                <li>
                                    <a class="<?php echo $this->reclamoestadistica?>" href="<?php echo $this->basePath()?>/usuario/reclamo/estadistica"><i class="fa fa-arrow-circle-right fa-fw"></i> Estadisticas</a>
                                </li>                                
                            </ul>
                        </li>
                        <li class="<?php echo $this->sugerencia?>">
                            <a class="<?php echo $this->sugerenciaprincipal?>" href="<?php echo $this->basePath()?>/usuario/sugerencia"><i class="fa fa-tasks fa-fw"></i> Libro Sugerencias<span class="fa arrow"></span></a>
                              <ul class="nav nav-second-level">
                                <li>
                                    <a class="<?php echo $this->sugerencianuevo?>" href="<?php echo $this->basePath()?>/usuario/sugerencia/nuevo"><i class="fa fa-arrow-circle-right fa-fw"></i> Nuevo</a>
                                </li>
                                <li>
                                    <a class="<?php echo $this->sugerenciaconsultar?>" href="<?php echo $this->basePath()?>/usuario/sugerencia/consultar"><i class="fa fa-arrow-circle-right fa-fw"></i>Consultar</a>
                                </li>
                                <li>
                                    <a class="<?php echo $this->sugerenciaestadistica?>" href="<?php echo $this->basePath()?>/usuario/sugerencia/estadistica"><i class="fa fa-arrow-circle-right fa-fw"></i> Estadisticas</a>
                                </li>                                
                            </ul>
                        <li>
                            <a href="<?php echo $this->basePath()?>/application/login/salir"><i class="fa fa-sign-out fa-fw"></i>Salir</a>
                        </li>                                                  
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>