
<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.5
Version: 4.1.0
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->
    <head>
        <meta charset="utf-8"/>
        <title>M&oacute;dulo Admin | becheck.cl</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <meta content="" name="description"/>
        <meta content="" name="author"/>
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="<?php echo $this->basePath() ?>/img/check.ico" rel="shortcut icon" type="image/vnd.microsoft.icon"/>
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath() ?>/metronic/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath() ?>/metronic/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath() ?>/metronic/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath() ?>/metronic/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath() ?>/metronic/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css"/>
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
        <link href="<?php echo $this->basePath() ?>/metronic/global/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath() ?>/metronic/global/plugins/fullcalendar/fullcalendar.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath() ?>/metronic/global/plugins/jqvmap/jqvmap/jqvmap.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath() ?>/metronic/global/plugins/morris/morris.css" rel="stylesheet" type="text/css">
        <!-- END PAGE LEVEL PLUGIN STYLES -->
        <!-- BEGIN PAGE STYLES -->
        <link href="<?php echo $this->basePath() ?>/metronic/admin/pages/css/tasks.css" rel="stylesheet" type="text/css"/>
        <!-- END PAGE STYLES -->
        <!-- BEGIN THEME STYLES -->
        <!-- DOC: To use 'rounded corners' style just load 'components-rounded.css' stylesheet instead of 'components.css' in the below style tag -->
        <link href="<?php echo $this->basePath() ?>/metronic/global/css/components-rounded.css" id="style_components" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath() ?>/metronic/global/css/plugins.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath() ?>/metronic/admin/layout4/css/layout.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath() ?>/metronic/admin/layout4/css/themes/light.css" rel="stylesheet" type="text/css" id="style_color"/>
        <link href="<?php echo $this->basePath() ?>/metronic/admin/layout4/css/custom.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath() ?>/metronic/global/plugins/bootstrap-toastr/toastr.min.css"/ rel="stylesheet" type="text/css" >
              <link href="<?php echo $this->basePath() ?>/metronic/admin.css" rel="stylesheet" type="text/css" >
        <link href="<?php echo $this->basePath() ?>/metronic/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/>


        <link href="<?php echo $this->basePath() ?>/css/dnd.css" rel="stylesheet" type="text/css">


        <!-- END THEME STYLES -->
        <link rel="shortcut icon" href="favicon.ico"/>

        <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
        <!-- BEGIN CORE PLUGINS -->
        <!--[if lt IE 9]>
        <script src="<?php echo $this->basePath() ?>/metronic/global/plugins/respond.min.js"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/global/plugins/excanvas.min.js"></script> 
        <![endif]-->


        <script src="<?php echo $this->basePath() ?>/metronic/global/plugins/jquery.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
        <!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
        <script src="<?php echo $this->basePath() ?>/metronic/global/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
        <!-- END CORE PLUGINS -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <!-- IMPORTANT! fullcalendar depends on jquery-ui.min.js for drag & drop support -->
        <script src="<?php echo $this->basePath() ?>/metronic/global/plugins/morris/morris.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/global/plugins/morris/raphael-min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/global/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <script src="<?php echo $this->basePath() ?>/metronic/global/scripts/metronic.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/admin/layout4/scripts/layout.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/admin/layout2/scripts/quick-sidebar.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/admin/layout4/scripts/demo.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/admin/pages/scripts/index3.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/admin/pages/scripts/tasks.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/global/plugins/bootstrap-toastr/toastr.min.js"></script>
        <script src="<?php echo $this->basePath() ?>/metronic/admin/pages/scripts/ui-toastr.js"></script>

        <!-- END PAGE LEVEL SCRIPTS -->
        <script>
            jQuery(document).ready(function () {
                Metronic.init(); // init metronic core componets
                Layout.init(); // init layout
                Demo.init(); // init demo features
                QuickSidebar.init(); // init quick sidebar    
                Tasks.initDashboardWidget(); // init tash dashboard widget  
                UIToastr.init();
                TableAdvanced.init();

            });
        </script>
        <!-- END JAVASCRIPTS -->
    </head>
    <!-- END HEAD -->
    <!-- BEGIN BODY -->
    <!-- DOC: Apply "page-header-fixed-mobile" and "page-footer-fixed-mobile" class to body element to force fixed header or footer in mobile devices -->
    <!-- DOC: Apply "page-sidebar-closed" class to the body and "page-sidebar-menu-closed" class to the sidebar menu element to hide the sidebar by default -->
    <!-- DOC: Apply "page-sidebar-hide" class to the body to make the sidebar completely hidden on toggle -->
    <!-- DOC: Apply "page-sidebar-closed-hide-logo" class to the body element to make the logo hidden on sidebar toggle -->
    <!-- DOC: Apply "page-sidebar-hide" class to body element to completely hide the sidebar on sidebar toggle -->
    <!-- DOC: Apply "page-sidebar-fixed" class to have fixed sidebar -->
    <!-- DOC: Apply "page-footer-fixed" class to the body element to have fixed footer -->
    <!-- DOC: Apply "page-sidebar-reversed" class to put the sidebar on the right side -->
    <!-- DOC: Apply "page-full-width" class to the body element to have full width page without the sidebar menu -->
    <body class="page-header-fixed page-sidebar-closed-hide-logo page-sidebar-closed-hide-logo">
        <!-- BEGIN HEADER -->
        <div class="page-header navbar navbar-fixed-top">
            <!-- BEGIN HEADER INNER -->
            <div class="page-header-inner">
                <!-- BEGIN LOGO -->
                <div class="page-logo">
                    <a href="">
                        <img src="<?php echo $this->basePath() ?>/metronic/admin/layout4/img/logo-light3.png" alt="logo" class="logo-default"/>
                    </a>
                    <div class="menu-toggler sidebar-toggler">
                        <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
                    </div>
                </div>
                <!-- END LOGO -->
                <!-- BEGIN RESPONSIVE MENU TOGGLER -->

                <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
                </a>
                <!-- END RESPONSIVE MENU TOGGLER -->
                <!-- BEGIN PAGE ACTIONS -->
                <!-- DOC: Remove "hide" class to enable the page header actions -->
                <div class="page-actions">
                    <div class="btn-group ">
                        <button type="button" class="btn red-haze btn-sm dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <span class="hidden-sm hidden-xs">Atajos&nbsp;</span><i class="fa fa-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="javascript:;">
                                    <i class="fa fa-dollar"></i> Nuevo Ingreso</a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <i class="fa fa-dollar"></i> Nuevo Egreso</a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <i class="fa fa-paper-plane"></i> Nueva Circular</a>
                            </li>					
                        </ul>
                    </div>
                </div>

                <!--
                
                
                -->






                <!-- END PAGE ACTIONS -->
                <!-- BEGIN PAGE TOP -->
                <div class="page-top hidden-xs">
                    <!-- BEGIN HEADER SEARCH BOX -->
                    <!-- DOC: Apply "search-form-expanded" right after the "search-form" class to have half expanded search box -->
                    <form class="search-form" action="extra_search.html" method="GET">
                        <div class="input-group">
                            <input type="text" class="form-control input-sm" placeholder="Buscar Dpto..." name="query">
                            <span class="input-group-btn">
                                <a class="btn submit"><i class="icon-magnifier"></i></a>
                            </span>
                        </div>
                    </form>
                    <!-- END HEADER SEARCH BOX -->
                    <!-- BEGIN TOP NAVIGATION MENU -->
                    <div class="top-menu ">
                        <ul class="nav navbar-nav pull-right">
                            <li class="separator hide">
                            </li>
                            <!-- END TODO DROPDOWN -->
                            <!-- BEGIN USER LOGIN DROPDOWN -->
                            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->


                            <li class="dropdown dropdown-user dropdown-dark">
                                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                    <span class="username username-hide-on-mobile">
                                        Tom&aacute;s Cornejo </span>
                                    <!-- DOC: Do not remove below empty space(&nbsp;) as its purposely used -->
                                    <img alt="" class="img-circle" src="<?php echo $this->basePath() ?>/metronic/admin/layout4/img/avatar9.jpg"/>
                                </a>

                                <ul class="dropdown-menu dropdown-menu-default">
                                    <li>
                                        <a href="extra_profile.html">
                                            <i class="icon-user"></i> Mi Perfil </a>
                                    </li>							                            
                                    <li class="divider">
                                    </li>
                                    <li>
                                        <a href="extra_lock.html">
                                            <i class="icon-lock"></i> Pantalla de bloqueo </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() . "/application/login/salir" ?>">
                                            <i class="icon-key"></i> Salir </a>
                                    </li>
                                </ul>
                            </li>


                            <!-- END USER LOGIN DROPDOWN -->
                            <!-- BEGIN USER LOGIN DROPDOWN -->
                            <li class="dropdown dropdown-extended quick-sidebar-toggler">
                                <span class="sr-only">Toggle Quick Sidebar</span>
                                <i class="icon-logout"></i>
                            </li>
                            <!-- END USER LOGIN DROPDOWN -->
                        </ul>

                    </div>
                    <!-- END TOP NAVIGATION MENU -->

                    <!-- </div> -->

                    <!-- END PAGE TOP -->
                </div>

                <ul class="nav navbar-nav pull-right visible-xs">
                    <li class="separator ">
                    </li>
                    <!-- END TODO DROPDOWN -->
                    <!-- BEGIN USER LOGIN DROPDOWN -->
                    <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->


                    <li class="dropdown dropdown-user dropdown-dark">
                        <a href="javascript:;" 
                           class="dropdown-toggle" data-toggle="dropdown" 
                           data-hover="dropdown" data-close-others="true">

                            <!-- DOC: Do not remove below empty space(&nbsp;) as its purposely used -->
                            <img alt="" class="img-circle" src="<?php echo $this->basePath() ?>/metronic/admin/layout4/img/avatar9.jpg"/>
                        </a>

                        <ul class="dropdown-menu dropdown-menu-default">
                            <li>
                                <a href="extra_profile.html">
                                    <i class="icon-user"></i> Mi Perfil </a>
                            </li>							                            
                            <li class="divider">
                            </li>
                            <li>
                                <a href="extra_lock.html">
                                    <i class="icon-lock"></i> Pantalla de bloqueo </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->basePath() . "/application/login/salir" ?>">
                                    <i class="icon-key"></i> Salir </a>
                            </li>
                        </ul>
                    </li>


                    <!-- END USER LOGIN DROPDOWN -->
                    <!-- BEGIN USER LOGIN DROPDOWN  -->
                    <!--
                    <li class="dropdown dropdown-extended quick-sidebar-toggler">
        <span class="sr-only">Toggle Quick Sidebar</span>
        <i class="icon-logout"></i>
    </li>
                    -->
                    <!-- END USER LOGIN DROPDOWN -->
                </ul>


                <!-- END HEADER INNER -->
            </div>
            <!-- END HEADER -->
            <div class="clearfix">
            </div>
            <!-- BEGIN CONTAINER -->
            <div class="page-container">
                <!-- BEGIN SIDEBAR -->
                <div class="page-sidebar-wrapper">
                    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
                    <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
                    <div class="page-sidebar navbar-collapse collapse">
                        <!-- BEGIN SIDEBAR MENU -->
                        <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
                        <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
                        <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
                        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
                        <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
                        <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
                        <ul class="page-sidebar-menu " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                            <li class="start active ">
                                <a href="<?php echo $this->basePath() ?>/usuario">
                                    <i class="icon-home"></i>
                                    <span class="title">Inicio</span>
                                </a>
                            </li>
                            <!-- MI CONDOMINIO -->
                            <li>
                                <a href="javascript:;">
                                    <i class="fa fa-bullhorn"></i>
                                    <span class="title">Comunicaci&oacute;n</span>
                                    <span class="arrow "></span>
                                </a>
                                <ul class="sub-menu">
                                    <li>
                                        <a href="<?php echo $this->basePath() . "/usuario/comunicacion/reclamo" ?>">
                                            <i class="fa fa-cogs"></i>
                                            Reclamos</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() . "/admin/infocom/unidades" ?>">
                                            <i class="fa fa-home"></i>
                                            Unidades</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() . "/admin/infocom/residentes" ?>">
                                            <i class="fa fa-users"></i>
                                            Residentes</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() . "/admin/infocom/instalaciones" ?>">
                                            <i class="fa fa-cog"></i>
                                            Instalaciones</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() . "/admin/infocom/seguridad" ?>">
                                            <i class="fa fa-lock"></i>
                                            Seguridad</a>
                                    </li>
                                </ul>
                            </li>
                            <!-- FIN MI CONDOMINIO -->

                            <!-- COMUNICACION -->
                            <li>
                                <a href="javascript:;">
                                    <i class="fa fa-bullhorn"></i>
                                    <span class="title">Comunicaci&oacute;n</span>
                                    <span class="arrow "></span>
                                </a>
                                <ul class="sub-menu">
                                    <li>
                                        <a href="<?php echo $this->basePath() . "/admin/comunicacion/mensajes" ?>">
                                            <i class="fa fa-envelope"></i>
                                            Mis Mensajes</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() . "/admin/comunicacion/circulares" ?>">
                                            <i class="fa fa-list-alt"></i>
                                            Circulares</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() . "/admin/comunicacion/biblioteca" ?>">
                                            <i class="fa fa-bookmark"></i>
                                            Biblioteca</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() . "/admin/comunicacion/reclamos" ?>">
                                            <i class="fa fa-bullhorn"></i>
                                            Reclamos</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() . "/admin/comunicacion/sugerencias" ?>">
                                            <i class="fa fa-bell"></i>
                                            Sugerencias</a>
                                    </li>
                                </ul>
                            </li>
                            <!-- FIN COMUNICACION -->

                            <!-- FINANZAS -->
                            <li>
                                <a>
                                    <i class="fa fa-dollar"></i>
                                    <span class="title">Finanzas</span>
                                    <span class="arrow "></span>
                                </a>
                                <ul class="sub-menu">
                                    <li>
                                        <a href="<?php echo $this->basePath() . "/admin/finanzas/resumen" ?>">
                                            <i class="fa fa-clipboard"></i>
                                            Resumen</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() . "/admin/finanzas/gastocomun" ?>">
                                            <i class="fa fa-users"></i>
                                            Gasto Comn&uacute;n</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() . "/admin/finanzas/ingresos" ?>">
                                            <i class="fa fa-download"></i>
                                            Ingresos</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() . "/admin/finanzas/egresos" ?>">
                                            <i class="fa fa-upload"></i>
                                            Egresos</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() . "/admin/finanzas/proveedores" ?>">
                                            <i class="fa fa-truck"></i>
                                            Proveedores</a>
                                    </li>
                                    <li>
                                        <a href="ecommerce_products_edit.html">
                                            <i class="fa fa-cogs"></i>
                                            Ajustes</a>
                                    </li>
                                </ul>
                            </li>
                            <!-- FIN FINANZAS -->

                            <!-- MANTENCIONES -->
                            <li>
                                <a>
                                    <i class="fa fa-wrench"></i>
                                    <span class="title">Mantenciones</span>
                                    <span class="arrow "></span>
                                </a>
                                <ul class="sub-menu">
                                    <li>
                                        <a href="ecommerce_index.html">
                                            <i class="fa fa-clipboard"></i>
                                            Notas de Mantenci&oacute;n</a>
                                    </li>
                                    <li>
                                        <a href="ecommerce_orders.html">
                                            <i class="fa fa-bookmark"></i>
                                            Tareas</a>
                                    </li>
                                    <li>
                                        <a href="ecommerce_orders_view.html">
                                            <i class="fa fa-clock-o"></i>
                                            Relojes</a>
                                    </li>
                                    <li>
                                        <a href="ecommerce_products.html">
                                            <i class="fa fa-calendar"></i>
                                            Calendario</a>
                                    </li>
                                    <li>
                                        <a href="ecommerce_products_edit.html">
                                            <i class="fa fa-tags"></i>
                                            Inventario</a>
                                    </li>
                                </ul>
                            </li>
                            <!-- FIN MANTENCIONES -->     


                            <!-- MANTENCIONES -->
                            <li>
                                <a>
                                    <i class="fa fa-users"></i>
                                    <span class="title">Personal</span>
                                    <span class="arrow "></span>
                                </a>
                                <ul class="sub-menu">
                                    <li>
                                        <a href="ecommerce_index.html">
                                            <i class="fa fa-clipboard"></i>
                                            Resumen</a>
                                    </li>
                                    <li>
                                        <a href="ecommerce_orders.html">
                                            <i class="fa fa-bookmark"></i>
                                            Conserjer&iacute;a</a>
                                    </li>
                                    <li>
                                        <a href="ecommerce_orders_view.html">
                                            <i class="fa fa-trash"></i>
                                            Aseo y Hornato</a>
                                    </li>
                                    <li>
                                        <a href="ecommerce_products_edit.html">
                                            <i class="fa fa-list-alt"></i>
                                            Liquidaciones</a>
                                    </li>
                                </ul>
                            </li>
                            <!-- FIN MANTENCIONES -->                               				
                        </ul>
                        <!-- END SIDEBAR MENU -->
                    </div>
                </div>
                <!-- END SIDEBAR -->
                <div class="page-content-wrapper">
                    <div class="page-content">

                        <?php echo $this->content; ?>

                    </div>
                </div>
            </div>
            <!-- END CONTAINER -->
            <!-- BEGIN FOOTER -->
            
            <div class="page-footer">
               <div class="page-footer-inner">
                    2014 &copy; Metronic by keenthemes. <a href="http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes" title="Purchase Metronic just for 27$ and get lifetime updates for free" target="_blank">Purchase Metronic!</a>
                </div>
                <div class="scroll-to-top">
                    <i class="icon-arrow-up"></i>
                </div>
            </div>
            <!-- END FOOTER -->
    </body>
    <!-- END BODY -->
</html>
<script>
    toastr.options = {
        "positionClass": "toast-top-center",
    }
    
    function submenu(x) {
        var pag = x;
          $.ajax({            
            url: '<?php echo $this->basePath() . "/usuario/'+pag+'" ?>',
            type: 'post',
            success: function (response) {                             
                $('#menu_usuario').fadeIn('slow');
                $("#menu_usuario").html(response);

            }
        });
        }
        
  
</script>