<form id="formpartida">
<div class="row">     
<br /> <br />    
                <div class="col-lg-12 col-md-12 ">
                    <div class="panel panel-primary">
                      <div class="panel-heading" ><i class="fa fa-check"></i>&nbsp;&nbsp;Seleccione meses que realizar&aacute; mantenciones  
                        </div>
                        <div class="panel-body">                                                                                
                            <div class="col-lg-12" style="margin-bottom: 1em;">                            
                                <p style="color: #000;text-align: left; font-size: 18px;">
                                    <i class="fa fa-tint"></i>
                                    &nbsp; <?php echo $this->partida[0]["nombre"];?>
                                </p>                            
                            </div>                                                        
                            <table class="table table-striped">
                                    <thead> 
                                        <tr>                                            
                                            <th>Frecuencia</th>
                                            <th>Acci&oacute;n</th>
                                            <th>Ene</th>
                                            <th>Feb</th>
                                            <th>Mar</th>
                                            <th>Abr</th>
                                            <th>May</th>
                                            <th>Jun</th>
                                            <th>Jul</th>
                                            <th>Ago</th>
                                            <th>Sep</th>
                                            <th>Oct</th>
                                            <th>Nov</th>
                                            <th>Dic</th>                                            
                                        </tr>
                                    </thead>                                                                                                             
                                    <tbody style="text-align: center;">                                    
                                        <tr>                                          
                                        <input type="hidden" name="id_pk" value="<?php echo $this->partida[0]["id"];?>"/>                                         
                                            <td><?php echo $this->partida[0]["frecuencia"];?></td>
                                            <td><?php echo $this->partida[0]["accion"];?></td>
                                            <td><input <?php if($this->partida[0]["Jan"]=="on"){echo "checked";};?> type="checkbox" name="Jan"/></td>
											<td><input <?php if($this->partida[0]["Feb"]=="on"){echo "checked";};?> type="checkbox" name="Feb"/></td>
											<td><input <?php if($this->partida[0]["Mar"]=="on"){echo "checked";};?> type="checkbox" name="Mar"/></td>
											<td><input <?php if($this->partida[0]["Abr"]=="on"){echo "checked";};?> type="checkbox" name="Abr"/></td>
											<td><input <?php if($this->partida[0]["May"]=="on"){echo "checked";};?> type="checkbox" name="May"/></td>
											<td><input <?php if($this->partida[0]["Jun"]=="on"){echo "checked";};?> type="checkbox" name="Jun"/></td>
											<td><input <?php if($this->partida[0]["Jul"]=="on"){echo "checked";};?> type="checkbox" name="Jul"/></td>
											<td><input <?php if($this->partida[0]["Aug"]=="on"){echo "checked";};?> type="checkbox" name="Aug"/></td>
											<td><input <?php if($this->partida[0]["Sep"]=="on"){echo "checked";};?> type="checkbox" name="Sep"/></td>
											<td><input <?php if($this->partida[0]["Oct"]=="on"){echo "checked";};?> type="checkbox" name="Oct"/></td>
											<td><input <?php if($this->partida[0]["Nov"]=="on"){echo "checked";};?> type="checkbox" name="Nov"/></td>
											<td><input <?php if($this->partida[0]["Dec"]=="on"){echo "checked";};?> type="checkbox" name="Dec"/></td>                                            
                                        </tr>   
                                                                  
                                    </tbody>
                                </table>                            
</div>
</div>

<div class="col-lg-12 col-md-12 text-center">
<a  class="btn btn-info" onclick="closeModal()"><i class="fa fa-reply"></i> &nbsp;Salir</a>
&nbsp;
<a class="btn btn-danger  <?php echo $this->displayelim;?>" onclick="eliminaPartida('<?php echo $this->partida[0]["id"];?>')"><i class="fa fa-trash"></i> &nbsp;Eliminar</a>
&nbsp;
<button  class="btn btn-success" type="submit"><i class="fa fa-download"></i> &nbsp;Guardar</button>
</div>
 
</div>
</div>
</form>

<!-- MODAL Eliminar Partida -->

<div class="modal fade bs-example-modal-sm" id="elimninarpart" data-backdrop="static" tabindex="1" role="dialog" aria-labelledby="myLargeModalLabel2" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div  class="modal-content">
        <div class="modal-body text-center" >
        <div id="todoelimina">
            <div class="col-lg-12" style="text-align: center;">
                <div class="col-lg-12" style="padding: 20px;"><i class="fa fa-warning fa-3x"></i></div>
                    <h4>Se eliminar&aacute; la partida del programa</h4><br />
            </div>
            
                    <button class="btn btn-info" data-dismiss="modal"><i class="fa fa-reply"></i>&nbsp;&nbsp; Atras</button>&nbsp;&nbsp;&nbsp;&nbsp;
                    <button id="btneliminarpart" class="btn btn-danger"><i class="fa fa-trash"></i>&nbsp;&nbsp; Eliminar</button>           
        </div>
         </div> 
        </div>                 
    </div>              
</div>

<!-- FIN MODAL Eliminar Partida -->
<script>
function eliminaPartida(id){
      var parametros = {'id' : id};
    	$.ajax( {
		data : parametros,
        url : '<?php echo $this->basePath()."/admin/mantenciones/eliminarpartida"?>',
		type : 'post',
		beforeSend : function() {
		//	$("#loading2").modal('show');    
	    //  $("#mostrareditar").html("<img src='<?php echo $this->basePath()?>/img/loading.gif'/>");            
		},
		success : function(response) {
		 //Habilitamos click!
        //    $("#loading").html("");
			$("#mostrareditar").html(response);
		} 
	});
}
function eliminaPartida(id,t){    
    if (t>0){
var parametros = {'id' : id};
 $.ajax( {     
        data : parametros,
        url : '<?php echo $this->basePath()."/admin/mantenciones/eliminarpartida"?>',
		type : 'post',  
		success : function(response) { 
	    $('#todoelimina').css("display","none");
        $('#rsptaelim').css("display","block");
        $('#descrpelim').text(response.descripcion);
        setTimeout(function(){
        $("#elimninarpart").modal('hide');
        $("#modaleditar").modal('hide');  
        $("#calendario").click();             
        },1800);    
                                              
  }   
}); 
    }else{
$('#elimninarpart').modal('show'); 
$('#btneliminarpart').click(function(){eliminaPartida(id,1)});
}         
}
$("#formpartida").submit(function(e){ 
 var postData = $(this).serializeArray();      
   $.ajax( {     
        data : postData,
        url : '<?php echo $this->basePath()."/admin/mantenciones/guardarpartida"?>',
		type : 'post',  
		success : function(response) {        
          if(response.status == 'ok'){          
           $("#modaleditar").modal('hide'); 
           toastr.success("Cambios guardados exitosamente");
                               
          }
        }    
});
    e.preventDefault();      
});
</script>                          