<h2 class="page-header"><a href="<?php echo $this->basePath()?>/conserje"><i class="fa fa-arrow-circle-left fa-1x"></i></a> Tu opinion si importa! </h2>

            <div class="row">

                <div class="col-lg-12">

                    <div class="panel panel-info">

                     <div class="panel-heading">

                        </div>



                        <div class="panel-body">

                            <div class="row">

                                <div class="col-lg-6">

                                    <form role="form">

                                        <div class="form-group">

                                            <label>¿Que crees que podria mejorar en tu comunidad?</label>
                                            
                                             <textarea class="form-control" rows="3" placeholder="Escribe aqui..." required="true"></textarea>

                                        </div>

                                        <div class="form-group">
                                                
                                             <label>¿Alguna Duda o Consulta?</label>
                                            
                                             <textarea class="form-control" rows="3" placeholder="Escribe aqui..." required="true"></textarea>

                                        </div> 

                                        <div class="form-group">

                                            <label>Dejanos tu correo, te responderemos!</label>

                                                <div class="form-group input-group"> 
                                           
                                                <span class="input-group-addon">@</span>
                                                <input class="form-control" type="email" required="true"/>
                                        
                                            </div>

                                        </div>                                                                                  

                                        <div class="form-group">

                                            <label>Muchas Gracias</label>

                                        </div>                                    


                                        <div class="form-group">
                                        
                                        
                                        <button type="reset" class="btn btn-danger">Cancelar</button>

                                        <button type="submit" class="btn btn-success">Enviar</button>

                                        </div>

                                    </form>

                                </div>

                                <!-- /.col-lg-6 (nested) -->

                                <div class="col-lg-6">

                                   

                                </div>

                                <!-- /.col-lg-6 (nested) -->

                            </div>

                            <!-- /.row (nested) -->

                        </div>

                        <!-- /.panel-body -->

                    </div>

                    <!-- /.panel -->

                </div>

                <!-- /.col-lg-12 -->

            </div>

            <!-- /.row -->