<h2 class="page-header"><a href="<?php echo $this->basePath()?>/conserje"><i class="fa fa-arrow-circle-left fa-1x"></i></a>   Seleccione su opci&oacute;n </h2>
<br /><br />
<section id="menu_conserje">
<div class="row">
            <a href="<?php echo $this->basePath()?>/conserje/visita/registrar">
               <div class="col-lg-3 col-md-6 col-sm-4">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <div>
                                    <i class="fa fa-user-plus fa-3x" style="color: #fff; "></i>
                                    </div>                                    
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                                <div class="col-xs-12 text-center">
                                        <div class="huge">Nueva visita</div>                                        
                                    </div>                            
                                <div class="clearfix"></div>
                            </div>
                            
                    </div>
                </div>
            </a> 
            
            <a href="<?php echo $this->basePath()?>/conserje/visita/verestac">
               <div class="col-lg-3 col-md-6 col-sm-4">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <div>
                                    <i class="fa fa-car fa-3x" style="color: #fff; "></i>
                                    </div>                                    
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                                <div class="col-xs-12 text-center">
                                        <div class="huge">Mapa estacionamientos</div>                                        
                                    </div>                            
                                <div class="clearfix"></div>
                            </div>
                            
                    </div>
                </div>
            </a> 

            <!--a href="<?php echo $this->basePath()?>/conserje/visita/verestac">
               <div class="col-lg-3 col-md-6 col-sm-4">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                 <div class="col-xs-12">
                                    <div class="col-xs-3" style="margin-top: 12px;">
                                    <i class="fa fa-table fa-3x" style="color: #fff; "></i>
                                    </div>
                                    <div class="col-xs-9 text-center">
                                        <div class="huge">Mapa</div>
                                        <div class="huge">Estacionamientos</div>
                                    </div>
                                </div>
                            </div>
                        </div-->
                            <!--div class="panel-footer">
                                <span class="pull-left">Seleccionar</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                            </a>
                    </div>
                </div-->
                
            <!--a href="<?php echo $this->basePath()?>/conserje/visita">
               <div class="col-lg-3 col-md-6 col-sm-4">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                 <div class="col-xs-12">
                                    <div class="col-xs-3" style="margin-top: 12px;">
                                    <i class="fa fa-file-text fa-3x" style="color: #fff; "></i>
                                    </div>
                                    <div class="col-xs-9 text-center">
                                        <div class="huge">Informe</div>
                                        <div class="huge">Hist&oacute;rico</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                            </a>
                    </div>
                </div-->                             

</div>
</section>

<div class="row">
<div class="col-lg-9" style="margin-top: 25px;">
                    <div class="panel panel-info">
                        <div class="panel-heading" style="background: #428bca; color: #fff;">
                           <i class="fa fa-history" style="color: #fff;"></i>&nbsp;&nbsp; Ultimas Visitas Registradas
                        </div>
                        <div class="panel-body">
                             <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>Dpto</th>
                                            <th>Visitante</th>
                                            <th>Fecha / Hora de ingreso</th>
                                            <th>Autom&oacute;vil</th>
                                            <th>Patente</th>
                                            <th>Estado</th>
                                        </tr>
                                    </thead>
                                    <tbody style="text-align: center;">
                                        <?php echo $this->info ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                       
                    </div>
                </div>

</div>

