<div class="row">      
                <div class="col-lg-12">                
                    <div class="panel panel-primary">
                      <div class="panel-heading" style="color: #fff; font-size: 18px;">
                        <i class="fa fa-calendar"></i>&nbsp;&nbsp;
                            Calendario de Mantenciones del condominio
                            <div  style="float: right;"> 
                             <a>
                                <button id="popover" class="fa fa-info-circle" style="cursor: pointer;color: #fff;" tabindex="0" data-container="body" data-toggle="popover" data-placement="left"  style="cursor: pointer;" ></i></button>
                             </a>
                            </div> 
                        </div>
                        <div class="panel-body">
                        
                            <div class="panel-group" id="accordionMant">
                            
                            <div class="row" style="margin-bottom: 1em;">
                            <div class="col-md-12">
                            <a data-toggle="collapse" data-parent="#accordionMant" href="#instsanitarias" style="text-decoration: none;"  >
                                <p style="color: #000;text-align: left; font-size: 18px;">
                                    <i class="fa fa-tint"></i>
                                    &nbsp; Instalaciones Sanitarias
                                </p>
                            </a>
                            </div>
                            </div>
                            
                            <div id="instsanitarias" class="table-responsive panel-collapse collapse">                                                                                            
                            <table class="table table-striped">                      
                                    <thead> 
                                        <tr>
                                            <th>Partida</th>
                                            <th>Frecuencia</th>
                                            <th>Acci&oacute;n</th>
                                            <th>Ene</th>
                                            <th>Feb</th>
                                            <th>Mar</th>
                                            <th>Abr</th>
                                            <th>May</th>
                                            <th>Jun</th>
                                            <th>Jul</th>
                                            <th>Ago</th>
                                            <th>Sep</th>
                                            <th>Oct</th>
                                            <th>Nov</th>
                                            <th>Dic</th>
                                        </tr>
                                    </thead>                                                                    
                                    <tbody style="text-align: center;">
                                     <?php for ($i=0;$i<count($this->partidas);$i++){?>
                                    <?php    if ($this->partidas[$i]['categoria']=="Instalaciones Sanitarias"){    ?>
                                        <tr>
                                            <td><?php echo $this->partidas[$i]["nombre"];?></td>
                                            <td><?php echo $this->partidas[$i]["frecuencia"];?></td>
                                            <td><?php echo $this->partidas[$i]["accion"];?></td>
                                            <td><?php if($this->partidas[$i]["Jan"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Feb"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Mar"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Apr"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["May"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jun"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jul"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Aug"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Sep"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Oct"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Nov"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Dec"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>                                            
                                        </tr> 
                             <?php    }}   ?>
                                    </tbody>
                                </table>
                            </div>
                           
                           <div class="row" style="margin-bottom: 1em;">
                            <div class="col-md-12">
                            <a data-toggle="collapse" data-parent="#accordionMant" href="#instelect" style="text-decoration: none;"  >
                                <p style="color: #000;text-align: left; font-size: 18px;">
                                    <i class="fa fa-bolt"></i>
                                    &nbsp; &nbsp;&nbsp;Instalaci&oacute;n el&eacute;ctrica y corrientes d&eacute;biles
                                </p>
                            </a>
                            </div>
                            </div>
                            
                            <div id="instelect" class="table-responsive panel-collapse collapse ">
                            <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Partida</th>
                                            <th>Frecuencia</th>
                                            <th>Acci&oacute;n</th>
                                            <th>Ene</th>
                                            <th>Feb</th>
                                            <th>Mar</th>
                                            <th>Abr</th>
                                            <th>May</th>
                                            <th>Jun</th>
                                            <th>Jul</th>
                                            <th>Ago</th>
                                            <th>Sep</th>
                                            <th>Oct</th>
                                            <th>Nov</th>
                                            <th>Dic</th>                                            
                                        </tr>
                                    </thead> 
                                    <?php for ($i=0;$i<count($this->partidas);$i++){?>                                  
                                    <tbody style="text-align: center;">
                                    <?php    if ($this->partidas[$i]['categoria']=="Instalacion electrica y corrientes debiles"){    ?>
                                        <tr>
                                            <td><?php echo $this->partidas[$i]["nombre"];?></td>
                                            <td><?php echo $this->partidas[$i]["frecuencia"];?></td>
                                            <td><?php echo $this->partidas[$i]["accion"];?></td>
                                            <td><?php if($this->partidas[$i]["Jan"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Feb"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Mar"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Apr"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["May"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jun"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jul"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Aug"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Sep"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Oct"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Nov"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Dec"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>                                            
                                        </tr> 
                             <?php    }}    ?>
                                    </tbody>
                                </table>
                            </div>
                            
                            <div class="row" style="margin-bottom: 1em;">
                            <div class="col-md-12">
                            <a data-toggle="collapse" data-parent="#accordionMant" href="#calefaccion" style="text-decoration: none;"  >
                                <p style="color: #000;text-align: left; font-size: 18px;">
                                    <i class="fa fa-fire"></i>
                                    &nbsp; &nbsp;Calefacci&oacute;n 
                                </p>
                            </a>
                            </div>
                            </div>
                            
                            <div id="calefaccion" class="table-responsive panel-collapse collapse ">
                            <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Partida</th>
                                            <th>Frecuencia</th>
                                            <th>Acci&oacute;n</th>
                                            <th>Ene</th>
                                            <th>Feb</th>
                                            <th>Mar</th>
                                            <th>Abr</th>
                                            <th>May</th>
                                            <th>Jun</th>
                                            <th>Jul</th>
                                            <th>Ago</th>
                                            <th>Sep</th>
                                            <th>Oct</th>
                                            <th>Nov</th>
                                            <th>Dic</th>                                            
                                        </tr>
                                    </thead> 
                                    <?php for ($i=0;$i<count($this->partidas);$i++){?>                                  
                                    <tbody style="text-align: center;">
                                    <?php    if ($this->partidas[$i]['categoria']=="Calefaccion"){    ?>
                                        <tr>
                                            <td><?php echo $this->partidas[$i]["nombre"];?></td>
                                            <td><?php echo $this->partidas[$i]["frecuencia"];?></td>
                                            <td><?php echo $this->partidas[$i]["accion"];?></td>
                                            <td><?php if($this->partidas[$i]["Jan"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Feb"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Mar"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Apr"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["May"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jun"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jul"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Aug"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Sep"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Oct"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Nov"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Dec"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>                                            
                                        </tr>  
                             <?php    }}    ?>
                                    </tbody>
                                </table>
                            </div>
                            
                            <div class="row" style="margin-bottom: 1em;">
                            <div class="col-md-12">
                            <a data-toggle="collapse" data-parent="#accordionMant" href="#ascensores" style="text-decoration: none;"  >
                                <p style="color: #000;text-align: left; font-size: 18px;">
                                    <i class="fa fa-building-o"></i>
                                    &nbsp; &nbsp;Ascensores 
                                </p>
                            </a>
                            </div>
                            </div>
                            
                            
                            <div id="ascensores" class="table-responsive panel-collapse collapse ">
                            <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Partida</th>
                                            <th>Frecuencia</th>
                                            <th>Acci&oacute;n</th>
                                            <th>Ene</th>
                                            <th>Feb</th>
                                            <th>Mar</th>
                                            <th>Abr</th>
                                            <th>May</th>
                                            <th>Jun</th>
                                            <th>Jul</th>
                                            <th>Ago</th>
                                            <th>Sep</th>
                                            <th>Oct</th>
                                            <th>Nov</th>
                                            <th>Dic</th>                                            
                                        </tr>
                                    </thead> 
                                    <?php for ($i=0;$i<count($this->partidas);++$i){?>                                  
                                    <tbody style="text-align: center;">
                                    <?php    if (utf8_encode($this->partidas[$i]['categoria'])=="Ascensores"){    ?>
                                        <tr>
                                            <td><?php echo $this->partidas[$i]["nombre"];?></td>
                                            <td><?php echo $this->partidas[$i]["frecuencia"];?></td>
                                            <td><?php echo $this->partidas[$i]["accion"];?></td>
                                            <td><?php if($this->partidas[$i]["Jan"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Feb"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Mar"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Apr"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["May"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jun"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jul"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Aug"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Sep"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Oct"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Nov"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Dec"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>                                            
                                        </tr> 
                             <?php    }}    ?>
                                    </tbody>
                                </table>
                            </div>
                            
                             <div class="row" style="margin-bottom: 1em;">
                            <div class="col-md-12">
                            <a data-toggle="collapse" data-parent="#accordionMant" href="#ascensores" style="text-decoration: none;"  >
                                <p style="color: #000;text-align: left; font-size: 18px;">
                                    <i class="fa fa-fire-extinguisher"></i>
                                    &nbsp; &nbsp;Instalaci&oacute;n prevenci&oacute;n Incendios 
                                </p>
                            </a>
                            </div>
                            </div>
                            
                             <div id="incendios" class="table-responsive panel-collapse collapse ">
                            <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Partida </th>
                                            <th>Frecuencia</th>
                                            <th>Acci&oacute;n</th>
                                            <th>Ene</th>
                                            <th>Feb</th>
                                            <th>Mar</th>
                                            <th>Abr</th>
                                            <th>May</th>
                                            <th>Jun</th>
                                            <th>Jul</th>
                                            <th>Ago</th>
                                            <th>Sep</th>
                                            <th>Oct</th>
                                            <th>Nov</th>
                                            <th>Dic</th>                                            
                                        </tr>
                                    </thead> 
                                    <?php for ($i=0;$i<count($this->partidas);$i++){?>                                  
                                    <tbody style="text-align: center;">
                                    <?php    if ($this->partidas[$i]['categoria']=="Instalacion prevencion Incendios"){    ?>
                                        <tr>
                                            <td><?php echo $this->partidas[$i]["nombre"];?></td>
                                            <td><?php echo $this->partidas[$i]["frecuencia"];?></td>
                                            <td><?php echo $this->partidas[$i]["accion"];?></td>
                                            <td><?php if($this->partidas[$i]["Jan"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Feb"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Mar"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Apr"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["May"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jun"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jul"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Aug"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Sep"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Oct"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Nov"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Dec"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>                                            
                                        </tr> 
                             <?php    }}    ?>
                                    </tbody>
                                </table>
                            </div>
                            
                             <div class="row" style="margin-bottom: 1em;">
                            <div class="col-md-12">
                            <a data-toggle="collapse" data-parent="#accordionMant" href="#basura" style="text-decoration: none;"  >
                                <p style="color: #000;text-align: left; font-size: 18px;">
                                    <i class="fa fa-trash"></i>
                                    &nbsp; &nbsp;Recolecci&oacute;n de basuras
                                </p>
                            </a>
                            </div>
                            </div>                                     
                            
                            <div id="basura" class="table-responsive panel-collapse collapse ">
                            <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Partida</th>
                                            <th>Frecuencia</th>
                                            <th>Acci&oacute;n</th>
                                            <th>Ene</th>
                                            <th>Feb</th>
                                            <th>Mar</th>
                                            <th>Abr</th>
                                            <th>May</th>
                                            <th>Jun</th>
                                            <th>Jul</th>
                                            <th>Ago</th>
                                            <th>Sep</th>
                                            <th>Oct</th>
                                            <th>Nov</th>
                                            <th>Dic</th>                                            
                                        </tr>
                                    </thead> 
                                    <?php for ($i=0;$i<count($this->partidas);$i++){?>                                  
                                    <tbody style="text-align: center;">
                                    <?php    if ($this->partidas[$i]['categoria']=="Recoleccion de basuras"){    ?>
                                        <tr>
                                            <td><?php echo $this->partidas[$i]["nombre"];?></td>
                                            <td><?php echo $this->partidas[$i]["frecuencia"];?></td>
                                            <td><?php echo $this->partidas[$i]["accion"];?></td>
                                            <td><?php if($this->partidas[$i]["Jan"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Feb"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Mar"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Apr"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["May"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jun"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jul"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Aug"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Sep"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Oct"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Nov"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Dec"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>                                            
                                        </tr>  
                             <?php    }}    ?>
                                    </tbody>
                                </table>
                            </div>
                            
                             <div class="row" style="margin-bottom: 1em;">
                            <div class="col-md-12">
                            <a data-toggle="collapse" data-parent="#accordionMant" href="#lluvias" style="text-decoration: none;"  >
                                <p style="color: #000;text-align: left; font-size: 18px;">
                                    <i class="fa fa-umbrella"></i>
                                    &nbsp; &nbsp;Aguas Lluvias
                                </p>
                            </a>
                            </div>
                            </div>  
                            
                            <div id="lluvias" class="table-responsive panel-collapse collapse ">
                            <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Partida</th>
                                            <th>Frecuencia</th>
                                            <th>Acci&oacute;n</th>
                                            <th>Ene</th>
                                            <th>Feb</th>
                                            <th>Mar</th>
                                            <th>Abr</th>
                                            <th>May</th>
                                            <th>Jun</th>
                                            <th>Jul</th>
                                            <th>Ago</th>
                                            <th>Sep</th>
                                            <th>Oct</th>
                                            <th>Nov</th>
                                            <th>Dic</th>                                            
                                        </tr>
                                    </thead> 
                                    <?php for ($i=0;$i<count($this->partidas);$i++){?>                                  
                                    <tbody style="text-align: center;">
                                    <?php    if ($this->partidas[$i]['categoria']=="Aguas Lluvias"){    ?>
                                        <tr>
                                            <td><?php echo $this->partidas[$i]["nombre"];?></td>
                                            <td><?php echo $this->partidas[$i]["frecuencia"];?></td>
                                            <td><?php echo $this->partidas[$i]["accion"];?></td>
                                            <td><?php if($this->partidas[$i]["Jan"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Feb"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Mar"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Apr"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["May"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jun"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jul"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Aug"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Sep"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Oct"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Nov"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Dec"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>                                          
                                        </tr> 
                             <?php    }}    ?>
                                    </tbody>
                                </table>
                            </div>
                            
                            <div class="row" style="margin-bottom: 1em;">
                            <div class="col-md-12">
                            <a data-toggle="collapse" data-parent="#accordionMant" href="#lavanderia" style="text-decoration: none;"  >
                                <p style="color: #000;text-align: left; font-size: 18px;">
                                    <i class="fa fa-instagram"></i>
                                    &nbsp; &nbsp;Lavander&iacute;a 
                                </p>
                            </a>
                            </div>
                            </div>  
                            
                            <div id="lavanderia" class="table-responsive panel-collapse collapse ">
                            <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Partida</th>
                                            <th>Frecuencia</th>
                                            <th>Acci&oacute;n</th>
                                            <th>Ene</th>
                                            <th>Feb</th>
                                            <th>Mar</th>
                                            <th>Abr</th>
                                            <th>May</th>
                                            <th>Jun</th>
                                            <th>Jul</th>
                                            <th>Ago</th>
                                            <th>Sep</th>
                                            <th>Oct</th>
                                            <th>Nov</th>
                                            <th>Dic</th>                                            
                                        </tr>
                                    </thead> 
                                    <?php for ($i=0;$i<count($this->partidas);$i++){?>                                  
                                    <tbody style="text-align: center;">
                                    <?php    if ($this->partidas[$i]['categoria']=="Lavanderia"){    ?>
                                        <tr>
                                            <td><?php echo $this->partidas[$i]["nombre"];?></td>
                                            <td><?php echo $this->partidas[$i]["frecuencia"];?></td>
                                            <td><?php echo $this->partidas[$i]["accion"];?></td>
                                            <td><?php if($this->partidas[$i]["Jan"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Feb"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Mar"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Apr"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["May"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jun"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jul"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Aug"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Sep"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Oct"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Nov"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Dec"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>                                            
                                        </tr> 
                             <?php    }}    ?>
                                    </tbody>
                                </table>
                            </div>
                            
                            <div class="row" style="margin-bottom: 1em;">
                            <div class="col-md-12">
                            <a data-toggle="collapse" data-parent="#accordionMant" href="#jardines" style="text-decoration: none;"  >
                                <p style="color: #000;text-align: left; font-size: 18px;">
                                    <i class="fa fa-tree"></i>
                                    &nbsp; &nbsp;Jardines 
                                </p>
                            </a>
                            </div>
                            </div> 
                            
                            <div id="jardines" class="table-responsive panel-collapse collapse ">
                            <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Partida</th>
                                            <th>Frecuencia</th>
                                            <th>Acci&oacute;n</th>
                                            <th>Ene</th>
                                            <th>Feb</th>
                                            <th>Mar</th>
                                            <th>Abr</th>
                                            <th>May</th>
                                            <th>Jun</th>
                                            <th>Jul</th>
                                            <th>Ago</th>
                                            <th>Sep</th>
                                            <th>Oct</th>
                                            <th>Nov</th>
                                            <th>Dic</th>                                            
                                        </tr>
                                    </thead> 
                                    <?php for ($i=0;$i<count($this->partidas);$i++){?>                                  
                                    <tbody style="text-align: center;">
                                    <?php    if ($this->partidas[$i]['categoria']=="Jardines"){    ?>
                                        <tr>
                                            <td><?php echo $this->partidas[$i]["nombre"];?></td>
                                            <td><?php echo $this->partidas[$i]["frecuencia"];?></td>
                                            <td><?php echo $this->partidas[$i]["accion"];?></td>
                                            <td><?php if($this->partidas[$i]["Jan"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Feb"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Mar"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Apr"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["May"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jun"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jul"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Aug"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Sep"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Oct"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Nov"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Dec"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>                                            
                                        </tr> 
                             <?php    }}    ?>
                                    </tbody>
                                </table>
                            </div>
                            
                            <div class="row" style="margin-bottom: 1em;">
                            <div class="col-md-12">
                            <a data-toggle="collapse" data-parent="#accordionMant" href="#pavimento" style="text-decoration: none;"  >
                                <p style="color: #000;text-align: left; font-size: 18px;">
                                    <i class="fa fa-road"></i>
                                    &nbsp; &nbsp;Pavimentos y Aguas Lluvias  
                                </p>
                            </a>
                            </div>
                            </div>                                                        
                            
                            <div id="pavimento" class="table-responsive panel-collapse collapse ">
                            <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Partida</th>
                                            <th>Frecuencia</th>
                                            <th>Acci&oacute;n</th>
                                            <th>Ene</th>
                                            <th>Feb</th>
                                            <th>Mar</th>
                                            <th>Abr</th>
                                            <th>May</th>
                                            <th>Jun</th>
                                            <th>Jul</th>
                                            <th>Ago</th>
                                            <th>Sep</th>
                                            <th>Oct</th>
                                            <th>Nov</th>
                                            <th>Dic</th>                                            
                                        </tr>
                                    </thead> 
                                    <?php for ($i=0;$i<count($this->partidas);$i++){?>                                  
                                    <tbody style="text-align: center;">
                                    <?php    if ($this->partidas[$i]['categoria']=="Pavimentos y Aguas Lluvias"){    ?>
                                        <tr>
                                            <td><?php echo $this->partidas[$i]["nombre"];?></td>
                                            <td><?php echo $this->partidas[$i]["frecuencia"];?></td>
                                            <td><?php echo $this->partidas[$i]["accion"];?></td>
                                            <td><?php if($this->partidas[$i]["Jan"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Feb"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Mar"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Apr"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["May"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jun"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jul"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Aug"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Sep"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Oct"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Nov"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Dec"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>                                            
                                        </tr> 
                             <?php    }}    ?>
                                    </tbody>
                                </table>
                            </div>
                            
                            <div class="row" style="margin-bottom: 1em;">
                            <div class="col-md-12">
                            <a data-toggle="collapse" data-parent="#accordionMant" href="#iluminacion" style="text-decoration: none;"  >
                                <p style="color: #000;text-align: left; font-size: 18px;">
                                    <i class="fa fa-lightbulb-o"></i>
                                    &nbsp; &nbsp;Iluminaci&oacute;n  
                                </p>
                            </a>
                            </div>
                            </div>
           
                            <div id="iluminacion" class="table-responsive panel-collapse collapse ">
                            <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Partida</th>
                                            <th>Frecuencia</th>
                                            <th>Acci&oacute;n</th>
                                            <th>Ene</th>
                                            <th>Feb</th>
                                            <th>Mar</th>
                                            <th>Abr</th>
                                            <th>May</th>
                                            <th>Jun</th>
                                            <th>Jul</th>
                                            <th>Ago</th>
                                            <th>Sep</th>
                                            <th>Oct</th>
                                            <th>Nov</th>
                                            <th>Dic</th>                                            
                                        </tr>
                                    </thead> 
                                    <?php for ($i=0;$i<count($this->partidas);$i++){?>                                  
                                    <tbody style="text-align: center;">
                                    <?php    if ($this->partidas[$i]['categoria']=="Iluminacion"){    ?>
                                        <tr>
                                            <td><?php echo $this->partidas[$i]["nombre"];?></td>
                                            <td><?php echo $this->partidas[$i]["frecuencia"];?></td>
                                            <td><?php echo $this->partidas[$i]["accion"];?></td>
                                            <td><?php if($this->partidas[$i]["Jan"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Feb"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Mar"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Apr"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["May"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jun"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Jul"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Aug"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Sep"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Oct"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Nov"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>
											<td><?php if($this->partidas[$i]["Dec"]=="on"){echo "<i class='fa fa-check'></i>";}?></td>                                            
                                        </tr>  
                             <?php    }}    ?>
                                    </tbody>
                                </table>
                            </div>
                            

                    </div>    

                </div>                                        

            </div>                                        

        </div> 
    </div>      
        <div class="modal fade bs-example-modal-lg" id="modaleditar" tabindex="-2" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
               <div class="modal-dialog modal-lg">
                 <div class="modal-content">
                          <div class="col-lg-12 text-right" style="margin-top: 9px;"> <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-close"></i></button></div>                          
                           <div id="mostrareditar" class="modal-body">Hello</div>
                 </div>
                 <!-- /.modal-content -->
                </div>
               <!-- /.modal-dialog -->
        </div>
        
        <div class="modal fade bs-example-modal-lg" id="modalnueva" tabindex="-2" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
               <div class="modal-dialog modal-lg">
                 <div class="modal-content">
                          <div class="col-lg-12 text-right" style="margin-top: 9px;"> <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-close"></i></button></div>                          
                           <div id="mostrareditar" class="modal-body">Hello</div>
                 </div>
                 <!-- /.modal-content -->
                </div>
               <!-- /.modal-dialog -->
        </div>
<script>
function editarPartida(id){
  var parametros = {'id' : id};
    	$.ajax( {
		data : parametros,
        url : '<?php echo $this->basePath()."/admin/mantenciones/editarpartida"?>',
		type : 'post',
		beforeSend : function() {
		//	$("#loading2").modal('show');    
		  $("#mostrareditar").html("<img src='<?php echo $this->basePath()?>/img/loading.gif'/>");            
		},
		success : function(response) {
		 //Habilitamos click!
        //    $("#loading").html("");
			$("#mostrareditar").html(response);
		} 
	});
    
}
function nuevaPartida(categoria){
var parametros = {'categoria' : categoria};
    $.ajax( {
		data : parametros,
        url : '<?php echo $this->basePath()."/admin/mantenciones/nuevapartida"?>',
		type : 'post',
		beforeSend : function() {
		//	$("#loading2").modal('show');    
		  $("#mostrareditar").html("<img src='<?php echo $this->basePath()?>/img/loading.gif'/>");            
		},
		success : function(response) {
		 //Habilitamos click!
        //    $("#loading").html("");
			$("#mostrareditar").html(response);
		} 
	});
    
}
</script>         