<?php
//LLamaremos a la session
use Zend\Session\Container;
$sid = new Container('base');
$modulo = $sid->offsetGet('modulo');
?>

<h2 class="page-header text-center">Seleccione M&oacute;dulo</h2>
<br/> <br/>
<div class="row">
<?php for($i=0;$i<count($modulo);$i++){
    $path_url = $this->basePath().'/'.$modulo[$i]['url'];
    $icon = $modulo[$i]['icon'];
    $nombre = $modulo[$i]['nombre'];
?>
  <a href="<?php echo $path_url ?>">
                <div class="col-lg-3 col-md-6 col-xs-12">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="<?php echo $icon ?>"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">M&oacute;dulo</div>
                                    <div class="huge"><?php echo $nombre?></div>
                                </div>
                            </div>
                        </div>
                            <div class="panel-footer">
                                <span class="pull-left">Ingresar</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
<?php }?>

                
 